{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "bluetooth",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.Jasonchenlijian",
          "module": "FastBle",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "bluetooth-master-SNAPSHOT.aar",
          "url": "bluetooth-master-SNAPSHOT.aar",
          "size": 71568,
          "sha512": "055ef08ae46806bb7e2a0f9ff50ca73acc4f51aef609883bcc22c60d6c1178b97a3370d07df8b8790fdbd96f652b4df9ccc34b63a998297c4dae480a26ce028c",
          "sha256": "f9db69d51ecdeb8b64fe9e6875dfd32d9d91fa351a43145e19f188c5d51ab665",
          "sha1": "2b2b7ca257fbfeec71859010cfd2103c3c9c709c",
          "md5": "9ff2c2e34e9fd38ac9f22c98fe26838b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.github.Jasonchenlijian",
          "module": "FastBle",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "bluetooth-master-SNAPSHOT.aar",
          "url": "bluetooth-master-SNAPSHOT.aar",
          "size": 71568,
          "sha512": "055ef08ae46806bb7e2a0f9ff50ca73acc4f51aef609883bcc22c60d6c1178b97a3370d07df8b8790fdbd96f652b4df9ccc34b63a998297c4dae480a26ce028c",
          "sha256": "f9db69d51ecdeb8b64fe9e6875dfd32d9d91fa351a43145e19f188c5d51ab665",
          "sha1": "2b2b7ca257fbfeec71859010cfd2103c3c9c709c",
          "md5": "9ff2c2e34e9fd38ac9f22c98fe26838b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bluetooth-master-SNAPSHOT-sources.jar",
          "url": "bluetooth-master-SNAPSHOT-sources.jar",
          "size": 12401,
          "sha512": "60005aa61e677f302be20be6a606bbb4a6e3d16c2602ac858b560e82f0321b39915f244e28c3a6b896bbe1883e6fc55b8a552d84abeb2e88c7821e211d0a3f9d",
          "sha256": "31b9e36fcc0660679359fa0f65002cac09085d636d5e3748c8512497260d2ee3",
          "sha1": "5adc74d476b0e4246841ed5bd8e90bd91f8e3009",
          "md5": "23e7fbfc88471033bdd04f4438a0bcd1"
        }
      ]
    }
  ]
}
