{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "doodle",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "doodle-hingin-SNAPSHOT.aar",
          "url": "doodle-hingin-SNAPSHOT.aar",
          "size": 283688,
          "sha512": "5372a35f7bd4f14070cf4034c8bd58d83c6b5d5bcebc192ef20fd6b92889ab4b5d3681db1d5d734226d2d46b7faf3a1a1c5be3edb6083473674488c03494e67f",
          "sha256": "e92df8224ec4e1316978e448285ed09f11f4999539904e85e85f5b28bf83dc07",
          "sha1": "0790b2d0a7cc116ccfb9e8cc603efab93fcd151f",
          "md5": "5bb237663585a06cc7ff82b97e05a70f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "doodle-hingin-SNAPSHOT.aar",
          "url": "doodle-hingin-SNAPSHOT.aar",
          "size": 283688,
          "sha512": "5372a35f7bd4f14070cf4034c8bd58d83c6b5d5bcebc192ef20fd6b92889ab4b5d3681db1d5d734226d2d46b7faf3a1a1c5be3edb6083473674488c03494e67f",
          "sha256": "e92df8224ec4e1316978e448285ed09f11f4999539904e85e85f5b28bf83dc07",
          "sha1": "0790b2d0a7cc116ccfb9e8cc603efab93fcd151f",
          "md5": "5bb237663585a06cc7ff82b97e05a70f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "doodle-hingin-SNAPSHOT-sources.jar",
          "url": "doodle-hingin-SNAPSHOT-sources.jar",
          "size": 104243,
          "sha512": "72cd704291a05ff3a2070e9c0d37226e15f23f7bdf3b64bb65a5860ac9bceb53dbd3eef20392fb5ee80b88c1771cd3c52cf54ba4fb5c0f5580069efe60ebf4cb",
          "sha256": "ab39a98e325759b8dc3a027622e9cce275e6d8d457fcfa0c6087ca775c4b03d0",
          "sha1": "2aacd2d5a64e1c4b1513fd514fb0b2b108e1dcc1",
          "md5": "03e4f014a5f1136191738e432c3fac2b"
        }
      ]
    }
  ]
}
