{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "doodle",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "doodle-hingin-SNAPSHOT.aar",
          "url": "doodle-hingin-SNAPSHOT.aar",
          "size": 283708,
          "sha512": "175cb9c7b449b3558a37454840be6d0199ea26700db126301563ecb70992b8c24a361d72fb2743c046512708b0dfa62d3ab74a5512dbcb725df1c1bd8e0f0375",
          "sha256": "9dc19f8872ebb92828f55955d1a7b7ee3175a09fa454d66ef64536b0ce619096",
          "sha1": "75b9abc1a8127a8908a4104e2b3e8c8896c2b62b",
          "md5": "19f5a99cc04c4bab925cfb02a966d7cf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "doodle-hingin-SNAPSHOT.aar",
          "url": "doodle-hingin-SNAPSHOT.aar",
          "size": 283708,
          "sha512": "175cb9c7b449b3558a37454840be6d0199ea26700db126301563ecb70992b8c24a361d72fb2743c046512708b0dfa62d3ab74a5512dbcb725df1c1bd8e0f0375",
          "sha256": "9dc19f8872ebb92828f55955d1a7b7ee3175a09fa454d66ef64536b0ce619096",
          "sha1": "75b9abc1a8127a8908a4104e2b3e8c8896c2b62b",
          "md5": "19f5a99cc04c4bab925cfb02a966d7cf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "doodle-hingin-SNAPSHOT-sources.jar",
          "url": "doodle-hingin-SNAPSHOT-sources.jar",
          "size": 104243,
          "sha512": "72cd704291a05ff3a2070e9c0d37226e15f23f7bdf3b64bb65a5860ac9bceb53dbd3eef20392fb5ee80b88c1771cd3c52cf54ba4fb5c0f5580069efe60ebf4cb",
          "sha256": "ab39a98e325759b8dc3a027622e9cce275e6d8d457fcfa0c6087ca775c4b03d0",
          "sha1": "2aacd2d5a64e1c4b1513fd514fb0b2b108e1dcc1",
          "md5": "03e4f014a5f1136191738e432c3fac2b"
        }
      ]
    }
  ]
}
