{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "doodle",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "doodle-hingin-SNAPSHOT.aar",
          "url": "doodle-hingin-SNAPSHOT.aar",
          "size": 283708,
          "sha512": "b4d2bc250d8fe90cd6a148668fb875824ed22b077a748ce20bbe46f4e73efa6b1c7b37ba9520147fd603c9057369d52b59bbfecc59fa84ad76243f518b7b517a",
          "sha256": "cf3639dd635f05868532e1711b9c9611876add05031c5cdaf3ad8149b6b401dc",
          "sha1": "b47ecb6aaa6397fc86a007d470742f1019bfac25",
          "md5": "87e7fee22e4b1842ec2cc51872bbeada"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "doodle-hingin-SNAPSHOT.aar",
          "url": "doodle-hingin-SNAPSHOT.aar",
          "size": 283708,
          "sha512": "b4d2bc250d8fe90cd6a148668fb875824ed22b077a748ce20bbe46f4e73efa6b1c7b37ba9520147fd603c9057369d52b59bbfecc59fa84ad76243f518b7b517a",
          "sha256": "cf3639dd635f05868532e1711b9c9611876add05031c5cdaf3ad8149b6b401dc",
          "sha1": "b47ecb6aaa6397fc86a007d470742f1019bfac25",
          "md5": "87e7fee22e4b1842ec2cc51872bbeada"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "doodle-hingin-SNAPSHOT-sources.jar",
          "url": "doodle-hingin-SNAPSHOT-sources.jar",
          "size": 104243,
          "sha512": "72cd704291a05ff3a2070e9c0d37226e15f23f7bdf3b64bb65a5860ac9bceb53dbd3eef20392fb5ee80b88c1771cd3c52cf54ba4fb5c0f5580069efe60ebf4cb",
          "sha256": "ab39a98e325759b8dc3a027622e9cce275e6d8d457fcfa0c6087ca775c4b03d0",
          "sha1": "2aacd2d5a64e1c4b1513fd514fb0b2b108e1dcc1",
          "md5": "03e4f014a5f1136191738e432c3fac2b"
        }
      ]
    }
  ]
}
