{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "camerax",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation-ktx",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "camerax-hingin-SNAPSHOT.aar",
          "url": "camerax-hingin-SNAPSHOT.aar",
          "size": 212566,
          "sha512": "e7e19df22a14c8b909452cd4584bdc149189fa2ea358cdc4246ac9edd70304abc7229447593f92a797df596e96bcc153b9c6ad96bb7d835aa78e886967cc30e3",
          "sha256": "520bf8ada304bb3c9f2ccfffc2dbf04f06c9a307401ad6d3a4ae7376ae844aa8",
          "sha1": "b4c287589cb380a5fd6e360b946ad1489a5006f6",
          "md5": "d155822fbe4a1d2723c864bbdd44b516"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "record",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation-ktx",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "camerax-hingin-SNAPSHOT.aar",
          "url": "camerax-hingin-SNAPSHOT.aar",
          "size": 212566,
          "sha512": "e7e19df22a14c8b909452cd4584bdc149189fa2ea358cdc4246ac9edd70304abc7229447593f92a797df596e96bcc153b9c6ad96bb7d835aa78e886967cc30e3",
          "sha256": "520bf8ada304bb3c9f2ccfffc2dbf04f06c9a307401ad6d3a4ae7376ae844aa8",
          "sha1": "b4c287589cb380a5fd6e360b946ad1489a5006f6",
          "md5": "d155822fbe4a1d2723c864bbdd44b516"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "camerax-hingin-SNAPSHOT-sources.jar",
          "url": "camerax-hingin-SNAPSHOT-sources.jar",
          "size": 84011,
          "sha512": "d6b783173f12457e5ef4f4526913b3a03758c1e2bdade6385382233aa5d466c1173e6f9aa98ca47cc04e2aaeb83668f45f3d8332928a73a0b18917c577c858f2",
          "sha256": "8c3432fd13b1c55ca9f08f26126300116de2119d1c479ba8341bd441c07b9ed5",
          "sha1": "62688298d70e2f97595b5b8fa18d562fb6b8b774",
          "md5": "8fd96e06633ad6dd137957b7e7038111"
        }
      ]
    }
  ]
}
