{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "andserver",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.yanzhenjie.andserver",
          "module": "api",
          "version": {
            "requires": "2.1.12"
          }
        },
        {
          "group": "javax.activation",
          "module": "javax.activation-api",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "andserver-hingin-SNAPSHOT.aar",
          "url": "andserver-hingin-SNAPSHOT.aar",
          "size": 115858,
          "sha512": "3ee7137155d77bda2d094e87de791cd43f6cf8cdfa5237980f47f55d09dedb141c752841a07b42f402ebd319ceb84f480645af416d2f59c7164572bf3f0253ac",
          "sha256": "ae018b9a1b66ebe961a7ce0230927072cfb037c1500a09d680496bbe3a5d62b9",
          "sha1": "2a44e7c017b156009b8bd8331c8f4338ac918591",
          "md5": "c673a89757ccd841fda438c2f9260173"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.yanzhenjie.andserver",
          "module": "api",
          "version": {
            "requires": "2.1.12"
          }
        },
        {
          "group": "javax.activation",
          "module": "javax.activation-api",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "andserver-hingin-SNAPSHOT.aar",
          "url": "andserver-hingin-SNAPSHOT.aar",
          "size": 115858,
          "sha512": "3ee7137155d77bda2d094e87de791cd43f6cf8cdfa5237980f47f55d09dedb141c752841a07b42f402ebd319ceb84f480645af416d2f59c7164572bf3f0253ac",
          "sha256": "ae018b9a1b66ebe961a7ce0230927072cfb037c1500a09d680496bbe3a5d62b9",
          "sha1": "2a44e7c017b156009b8bd8331c8f4338ac918591",
          "md5": "c673a89757ccd841fda438c2f9260173"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "andserver-hingin-SNAPSHOT-sources.jar",
          "url": "andserver-hingin-SNAPSHOT-sources.jar",
          "size": 33957,
          "sha512": "6fde9d82340e6c9c8011d226e2e914bc527ece71c9e182fa35069e87b625f779ed5e11742e13c0ec75abdc2fd0ef34ed08888962754945f0393f154aab4afd36",
          "sha256": "98d83831117f631d05de71bfd6a00565dcf4b36a275d2a73337f17f8c126b09c",
          "sha1": "e89efd7b400084f179936c3b7dbb4ecc755cd346",
          "md5": "56c8ba59ed8ace51f0ac93fd1d439e14"
        }
      ]
    }
  ]
}
