{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "andserver",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.yanzhenjie.andserver",
          "module": "api",
          "version": {
            "requires": "2.1.12"
          }
        },
        {
          "group": "javax.activation",
          "module": "javax.activation-api",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "andserver-hingin-SNAPSHOT.aar",
          "url": "andserver-hingin-SNAPSHOT.aar",
          "size": 115858,
          "sha512": "847bccf13d32a9ecc04cda951660ff721004a8cf60e5874bfe519a38f6900fe4ddfc71f7230e455806166bb9777b2a4be37b77a210625a1b78c00a7631b576c9",
          "sha256": "a0c3bc9a81ebb7e4f2f8dc5dba0b82f6601a7e837003791959cd62b4e7e8209a",
          "sha1": "28ad407f0ef650c539cb62cfe96e96514d65cf49",
          "md5": "fded61f5bc8b777e201d03f8c8d5c265"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.yanzhenjie.andserver",
          "module": "api",
          "version": {
            "requires": "2.1.12"
          }
        },
        {
          "group": "javax.activation",
          "module": "javax.activation-api",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "andserver-hingin-SNAPSHOT.aar",
          "url": "andserver-hingin-SNAPSHOT.aar",
          "size": 115858,
          "sha512": "847bccf13d32a9ecc04cda951660ff721004a8cf60e5874bfe519a38f6900fe4ddfc71f7230e455806166bb9777b2a4be37b77a210625a1b78c00a7631b576c9",
          "sha256": "a0c3bc9a81ebb7e4f2f8dc5dba0b82f6601a7e837003791959cd62b4e7e8209a",
          "sha1": "28ad407f0ef650c539cb62cfe96e96514d65cf49",
          "md5": "fded61f5bc8b777e201d03f8c8d5c265"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "andserver-hingin-SNAPSHOT-sources.jar",
          "url": "andserver-hingin-SNAPSHOT-sources.jar",
          "size": 33957,
          "sha512": "6fde9d82340e6c9c8011d226e2e914bc527ece71c9e182fa35069e87b625f779ed5e11742e13c0ec75abdc2fd0ef34ed08888962754945f0393f154aab4afd36",
          "sha256": "98d83831117f631d05de71bfd6a00565dcf4b36a275d2a73337f17f8c126b09c",
          "sha1": "e89efd7b400084f179936c3b7dbb4ecc755cd346",
          "md5": "56c8ba59ed8ace51f0ac93fd1d439e14"
        }
      ]
    }
  ]
}
