{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "dialog",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.LaserPeckerIst",
          "module": "ColorPickerView",
          "version": {
            "requires": "2.2.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "dialog-hingin-SNAPSHOT.aar",
          "url": "dialog-hingin-SNAPSHOT.aar",
          "size": 481056,
          "sha512": "884671fe3fba3db16acc339d3414964cedc441688ac40f2e0fcc6b24518abac1283544eb16a75bb99765557c9bad1b2948f399da6a6f743d98015c7796506777",
          "sha256": "128c548df49bfe55daab025086226cce04a27dc84eba141701e16766ca9f4043",
          "sha1": "97ea8a65ec37db86a6298423af69b480c8d9a76c",
          "md5": "26c2a92b5fe6094d015e5199fcfc78a0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "ColorPickerView",
          "version": {
            "requires": "2.2.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "dialog-hingin-SNAPSHOT.aar",
          "url": "dialog-hingin-SNAPSHOT.aar",
          "size": 481056,
          "sha512": "884671fe3fba3db16acc339d3414964cedc441688ac40f2e0fcc6b24518abac1283544eb16a75bb99765557c9bad1b2948f399da6a6f743d98015c7796506777",
          "sha256": "128c548df49bfe55daab025086226cce04a27dc84eba141701e16766ca9f4043",
          "sha1": "97ea8a65ec37db86a6298423af69b480c8d9a76c",
          "md5": "26c2a92b5fe6094d015e5199fcfc78a0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dialog-hingin-SNAPSHOT-sources.jar",
          "url": "dialog-hingin-SNAPSHOT-sources.jar",
          "size": 140171,
          "sha512": "3a7afed3544b40dcce96ad9b488979fa5e49ed6088a22c378b749436377230c1fb96792f0fa7db97d4ce125a5a49d9189fddd664c42efb7e148c6f4c86bb241f",
          "sha256": "4993b22fa51cbc013f08f43612af55a943794f80ae9dda96101d701e2f978de1",
          "sha1": "abbe121d25b9176542c9db9dd95faad33626e9b1",
          "md5": "28a4389a8b15b09dc365cbc0605305b7"
        }
      ]
    }
  ]
}
