{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "pager",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pager-master-SNAPSHOT.aar",
          "url": "pager-master-SNAPSHOT.aar",
          "size": 113490,
          "sha512": "dd5a124feff41a8626b641575e396aae3c57acbe4f89f16fe857cfa3d1fd6dd552e49efcb3beca991b5179a5a00a80206ffec5e6abd99fb0ea79af30a310afe0",
          "sha256": "ac005b8c412ca4b79ff5f05a77578fc77026b95cf961b90ba1c0ff86aadd9e4b",
          "sha1": "e68e492ce5b6a8b8bce05ec971750cd556b17957",
          "md5": "de5bf50ec755887c86bdc44ece9b3060"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pager-master-SNAPSHOT.aar",
          "url": "pager-master-SNAPSHOT.aar",
          "size": 113490,
          "sha512": "dd5a124feff41a8626b641575e396aae3c57acbe4f89f16fe857cfa3d1fd6dd552e49efcb3beca991b5179a5a00a80206ffec5e6abd99fb0ea79af30a310afe0",
          "sha256": "ac005b8c412ca4b79ff5f05a77578fc77026b95cf961b90ba1c0ff86aadd9e4b",
          "sha1": "e68e492ce5b6a8b8bce05ec971750cd556b17957",
          "md5": "de5bf50ec755887c86bdc44ece9b3060"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pager-master-SNAPSHOT-sources.jar",
          "url": "pager-master-SNAPSHOT-sources.jar",
          "size": 27195,
          "sha512": "a5a2d3bd1ba900d128f312d5af184e71e6dc3f24217bf26ee423dd4637171aec3e3fb5113296fa0204db2a04d746aa599d73f7b3079da5b7c4f574111e10470b",
          "sha256": "7557d320da7cc7a008012fa80ffdfa0ea0cdb8d98713ca9713a7c977c253432e",
          "sha1": "837d901b476a1b5ed98001bd360fddbc4c84dfc3",
          "md5": "0aad62dded835d90ac484580ddc6bbc2"
        }
      ]
    }
  ]
}
