{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "http",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.hwangjr.rxbus",
          "module": "rxbus",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.github.ikidou",
          "module": "TypeBuilder",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.AndroidStudioIst",
          "module": "ProgressManager",
          "version": {
            "requires": "1.5.0_fix4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "http-hingin-SNAPSHOT.aar",
          "url": "http-hingin-SNAPSHOT.aar",
          "size": 348631,
          "sha512": "4e4260897dc1d152ca0b4cd4c0358bcc6cc777c2aca5ee20db864ce01052b478f5c2fe82ed9fa47e00363f8fd810d9c3dd4aee41851650a1a4c3bedcfb194c59",
          "sha256": "ff709ab2cc3c4e6324b9e576d8c253cff87d384b0c70f0b3940151814d4ef435",
          "sha1": "d5fa61cd562ddb7de2fa5040693818437d9f0069",
          "md5": "3f52086f9ec9e6db293aa68b88f7bda1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.hwangjr.rxbus",
          "module": "rxbus",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.github.ikidou",
          "module": "TypeBuilder",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.AndroidStudioIst",
          "module": "ProgressManager",
          "version": {
            "requires": "1.5.0_fix4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "http-hingin-SNAPSHOT.aar",
          "url": "http-hingin-SNAPSHOT.aar",
          "size": 348631,
          "sha512": "4e4260897dc1d152ca0b4cd4c0358bcc6cc777c2aca5ee20db864ce01052b478f5c2fe82ed9fa47e00363f8fd810d9c3dd4aee41851650a1a4c3bedcfb194c59",
          "sha256": "ff709ab2cc3c4e6324b9e576d8c253cff87d384b0c70f0b3940151814d4ef435",
          "sha1": "d5fa61cd562ddb7de2fa5040693818437d9f0069",
          "md5": "3f52086f9ec9e6db293aa68b88f7bda1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "http-hingin-SNAPSHOT-sources.jar",
          "url": "http-hingin-SNAPSHOT-sources.jar",
          "size": 144687,
          "sha512": "0950a5bcac99415e8a837ccde0b15604607d04314366d29b09e881744c4c2cf4ffa427d9e3bbef866b89204fc06d5664b3c69f05700a883b80062ec09374e06b",
          "sha256": "5b7e5c5ab61c5c9d75b7b18fc0e3f680b88d01a6462d8f3ae98ac70d598ccb80",
          "sha1": "f7bedd49036e9456b7b1975fd92e115561b3b2f0",
          "md5": "2db67d2518881ba0cee30d904d5b2951"
        }
      ]
    }
  ]
}
