{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "http",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.hwangjr.rxbus",
          "module": "rxbus",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.github.ikidou",
          "module": "TypeBuilder",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.AndroidStudioIst",
          "module": "ProgressManager",
          "version": {
            "requires": "1.5.0_fix4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "http-hingin-SNAPSHOT.aar",
          "url": "http-hingin-SNAPSHOT.aar",
          "size": 347948,
          "sha512": "e2ba7380fed2c6fa9dc47e133ff5cea8578e67d1b3dd04ea9a2f2dd4952b5fe9c7eaff79831363df0efbd6d05359d97437897ff1cc0a312c7b4f7897a180501c",
          "sha256": "d379d707958712dbed0c7e7f655c89aa5fbdd6504fc8a7fd5b1807204c57f4bf",
          "sha1": "b6ecd92ccf187be819c8e6ce716a29b7ad17ca7e",
          "md5": "250dee89746b313fbb8ae02df6cccb13"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.hwangjr.rxbus",
          "module": "rxbus",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.github.ikidou",
          "module": "TypeBuilder",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.AndroidStudioIst",
          "module": "ProgressManager",
          "version": {
            "requires": "1.5.0_fix4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "http-hingin-SNAPSHOT.aar",
          "url": "http-hingin-SNAPSHOT.aar",
          "size": 347948,
          "sha512": "e2ba7380fed2c6fa9dc47e133ff5cea8578e67d1b3dd04ea9a2f2dd4952b5fe9c7eaff79831363df0efbd6d05359d97437897ff1cc0a312c7b4f7897a180501c",
          "sha256": "d379d707958712dbed0c7e7f655c89aa5fbdd6504fc8a7fd5b1807204c57f4bf",
          "sha1": "b6ecd92ccf187be819c8e6ce716a29b7ad17ca7e",
          "md5": "250dee89746b313fbb8ae02df6cccb13"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "http-hingin-SNAPSHOT-sources.jar",
          "url": "http-hingin-SNAPSHOT-sources.jar",
          "size": 143859,
          "sha512": "8f4a0fb0ab94efdb6869f1847e9f6ff9ee23805b22740dc30c917107ee98fafc3eb838a2687e5c19dda4a482f28dbafb5affdfb1a795b67d905f16950c89e29b",
          "sha256": "ec28048ac135b138e1493335f098db96ca03c5fc5e7845d3b853f9e2f39ef32f",
          "sha1": "1a1f47604193038b542295db3b98ce27e32ebf60",
          "md5": "98e2a5154a446dd60263d8ca0d66f33a"
        }
      ]
    }
  ]
}
