{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "bluetooth",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.Jasonchenlijian",
          "module": "FastBle",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "bluetooth-hingin-SNAPSHOT.aar",
          "url": "bluetooth-hingin-SNAPSHOT.aar",
          "size": 71579,
          "sha512": "fda552542b209674a827eb0e3b1f331c8841dd8dff7aeb4b66907d327d82112e12601ef7f01a7620ac338e322ed7b6a49dff628d195f5c570093464ba90ea6e4",
          "sha256": "3c1d8e23554f8894c9cf59c635439799427e41b0347259bb79e0bae635d9c4a8",
          "sha1": "8688370fcd152f950de659dfa2a6946f9f621216",
          "md5": "6d929b7cb5be8b5bcc2fb875d75af8b0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.Jasonchenlijian",
          "module": "FastBle",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "bluetooth-hingin-SNAPSHOT.aar",
          "url": "bluetooth-hingin-SNAPSHOT.aar",
          "size": 71579,
          "sha512": "fda552542b209674a827eb0e3b1f331c8841dd8dff7aeb4b66907d327d82112e12601ef7f01a7620ac338e322ed7b6a49dff628d195f5c570093464ba90ea6e4",
          "sha256": "3c1d8e23554f8894c9cf59c635439799427e41b0347259bb79e0bae635d9c4a8",
          "sha1": "8688370fcd152f950de659dfa2a6946f9f621216",
          "md5": "6d929b7cb5be8b5bcc2fb875d75af8b0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bluetooth-hingin-SNAPSHOT-sources.jar",
          "url": "bluetooth-hingin-SNAPSHOT-sources.jar",
          "size": 12401,
          "sha512": "60005aa61e677f302be20be6a606bbb4a6e3d16c2602ac858b560e82f0321b39915f244e28c3a6b896bbe1883e6fc55b8a552d84abeb2e88c7821e211d0a3f9d",
          "sha256": "31b9e36fcc0660679359fa0f65002cac09085d636d5e3748c8512497260d2ee3",
          "sha1": "5adc74d476b0e4246841ed5bd8e90bd91f8e3009",
          "md5": "23e7fbfc88471033bdd04f4438a0bcd1"
        }
      ]
    }
  ]
}
