{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "image",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view-androidx",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "image-hingin-SNAPSHOT.aar",
          "url": "image-hingin-SNAPSHOT.aar",
          "size": 63806,
          "sha512": "2702a0c1a9664caf3aec8e4f24afadbf5b95f53c74f6c595edd79840370767af08f4dbb709dc6ce27376fc8ce50bd64b56d865be15cb19511d63a3fe82a92787",
          "sha256": "81cd034d096dbfeac633288faac4f0bd97c763dfa960594621ebb7aca2729de7",
          "sha1": "40242aba6c9e9a4a0a094ae2847ed863a5af8338",
          "md5": "e6c603aa10088cf64c07705117d78e71"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view-androidx",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "image-hingin-SNAPSHOT.aar",
          "url": "image-hingin-SNAPSHOT.aar",
          "size": 63806,
          "sha512": "2702a0c1a9664caf3aec8e4f24afadbf5b95f53c74f6c595edd79840370767af08f4dbb709dc6ce27376fc8ce50bd64b56d865be15cb19511d63a3fe82a92787",
          "sha256": "81cd034d096dbfeac633288faac4f0bd97c763dfa960594621ebb7aca2729de7",
          "sha1": "40242aba6c9e9a4a0a094ae2847ed863a5af8338",
          "md5": "e6c603aa10088cf64c07705117d78e71"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "image-hingin-SNAPSHOT-sources.jar",
          "url": "image-hingin-SNAPSHOT-sources.jar",
          "size": 11377,
          "sha512": "4843b0be50819ef5c323ea3b9b0f416996e5e912b989df5bca3e7312c4f3ced4c4909a93b17062b9a4734fdbb81c08fcd28ead267652123cb70e08c86bdd7406",
          "sha256": "2ccb97dd749123b0c2a43dbe51203bdf05473c14767fcc5b36c805e829b39174",
          "sha1": "867ab9fac9313be81374d3da7b51dea1b4831434",
          "md5": "dd3b9e445581af707a59cd26b2b2d37d"
        }
      ]
    }
  ]
}
