{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "qrcode",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.angcyo",
          "module": "QrCodeZxingZbar",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "qrcode-master-SNAPSHOT.aar",
          "url": "qrcode-master-SNAPSHOT.aar",
          "size": 121853,
          "sha512": "09f3aab1b12ac0ae096a4e3ec123fad678ebe839226bfdf2131dd2e9de6316201f0a6dbbc9cf1330bb1ac27367922e5681296bae8c8a6f7d9686bc13ac8ca050",
          "sha256": "a51d42bedbf762ec33466a00f877b7fc13157b3c57a898a9fc1443b3f109f4d3",
          "sha1": "c3948da5cdc13d5bb61d41e610abf2cbc1f48dbd",
          "md5": "812e62e9de9c4c757f767e8c8f879fc7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "QrCodeZxingZbar",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "qrcode-master-SNAPSHOT.aar",
          "url": "qrcode-master-SNAPSHOT.aar",
          "size": 121853,
          "sha512": "09f3aab1b12ac0ae096a4e3ec123fad678ebe839226bfdf2131dd2e9de6316201f0a6dbbc9cf1330bb1ac27367922e5681296bae8c8a6f7d9686bc13ac8ca050",
          "sha256": "a51d42bedbf762ec33466a00f877b7fc13157b3c57a898a9fc1443b3f109f4d3",
          "sha1": "c3948da5cdc13d5bb61d41e610abf2cbc1f48dbd",
          "md5": "812e62e9de9c4c757f767e8c8f879fc7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "qrcode-master-SNAPSHOT-sources.jar",
          "url": "qrcode-master-SNAPSHOT-sources.jar",
          "size": 36885,
          "sha512": "7581cd29c0ebceb763b6d468e488a529b234e7741bb4e53be72541189351e1f3d262ae6cbd8bec184eeace2a6c42d653da9d14daa414e3b28bb7460b02feec1e",
          "sha256": "0237f40c19e05e43d5426e63e84c12c201f015a127e8c069fc7e0e0ee4a76be1",
          "sha1": "471e36f61614c840b20ae26b3c50eba0628a57d6",
          "md5": "a2eb93562d21e551158b8dce3ee04c40"
        }
      ]
    }
  ]
}
