{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "glide",
    "version": "2025081202",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "glide-2025081202.aar",
          "url": "glide-2025081202.aar",
          "size": 113180,
          "sha512": "1a5bb5f265985f47f5a7d6c265c863616707609002542b12100eae45beb52b6b0a0fd4e9cc9083adca04e024ae48d4d2562aba1ca9edfa4bc121730172ff7a1d",
          "sha256": "c514cb9b0abfe4717584eb060270755ad28d062d5f71e7c5015ae6c6c8d88124",
          "sha1": "80c517e52aad576a60e6a78d78cadc058fd4c1be",
          "md5": "4d7cc142077f64ebea2ed6afbfe77be1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "glide-2025081202.aar",
          "url": "glide-2025081202.aar",
          "size": 113180,
          "sha512": "1a5bb5f265985f47f5a7d6c265c863616707609002542b12100eae45beb52b6b0a0fd4e9cc9083adca04e024ae48d4d2562aba1ca9edfa4bc121730172ff7a1d",
          "sha256": "c514cb9b0abfe4717584eb060270755ad28d062d5f71e7c5015ae6c6c8d88124",
          "sha1": "80c517e52aad576a60e6a78d78cadc058fd4c1be",
          "md5": "4d7cc142077f64ebea2ed6afbfe77be1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "glide-2025081202-sources.jar",
          "url": "glide-2025081202-sources.jar",
          "size": 35125,
          "sha512": "561c084a971b41dd243355a3b89aa8277c056821481672dd6e7c3b9c63c13962435dd2da2eb2e0e7b12f1107b4211f812ecda6650094e2ca33394cdf3d4744b9",
          "sha256": "9771dd607e531f2f202effcf1972ec1e7f1cc7020a2525a6a01600fd07580973",
          "sha1": "7686197336ed922e9958b5fa82477200cecb44b9",
          "md5": "f6da959d53d02534f3f37ae704016be2"
        }
      ]
    }
  ]
}
