{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "lpDevice",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT.aar",
          "url": "lpDevice-hingin-SNAPSHOT.aar",
          "size": 13150964,
          "sha512": "e3f8bc91107d393c76e21b6fbce9a6383f0b63b97a2c7ca32af081a5ecf1fdd266907ea4d70ec982c40cb09dd5f4c41d1c39db186d5d1aac06fbca3f8f678540",
          "sha256": "dd7ed3076554f96c3ee8d78e8dce42c7ad2955b7b97f22b51a31e07b92b3f167",
          "sha1": "b0c07eacb9fcc5b7359f62b1eb7da3d7a1944035",
          "md5": "4bf5448d84e58d94f32545504bfa0d03"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "pager",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT.aar",
          "url": "lpDevice-hingin-SNAPSHOT.aar",
          "size": 13150964,
          "sha512": "e3f8bc91107d393c76e21b6fbce9a6383f0b63b97a2c7ca32af081a5ecf1fdd266907ea4d70ec982c40cb09dd5f4c41d1c39db186d5d1aac06fbca3f8f678540",
          "sha256": "dd7ed3076554f96c3ee8d78e8dce42c7ad2955b7b97f22b51a31e07b92b3f167",
          "sha1": "b0c07eacb9fcc5b7359f62b1eb7da3d7a1944035",
          "md5": "4bf5448d84e58d94f32545504bfa0d03"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT-sources.jar",
          "url": "lpDevice-hingin-SNAPSHOT-sources.jar",
          "size": 270149,
          "sha512": "bb1eaa6ca0a11959abb165c8a899af62bb0ca9c09bd67ce009107bb1f2f01b11fd91a0af30535352ccff1174ab2a2c659cae6aa1c729c7ca9923f59b2a987714",
          "sha256": "83194b17cefb10e962594e871cbb38166abe1da0d5d466112bd4b5f1cca5fb26",
          "sha1": "95017a23a0df6b159142793e78452b895916f61a",
          "md5": "cf50e2db3a1fc14380160f7604065c50"
        }
      ]
    }
  ]
}
