{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "lpDevice",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT.aar",
          "url": "lpDevice-hingin-SNAPSHOT.aar",
          "size": 11256224,
          "sha512": "954b4722be6dbcbc42e4fbbe14c5269ba81ec0e7d422b81b21707c8914f956cf8863700e5a06fb64dd4df3512d2c0e17de6c89db0ac2dc6f80217cbad54a43e1",
          "sha256": "a3029508f58f6eebd021cdd83b057e79c97f06a16af83fe809fa5e4e7603b936",
          "sha1": "cd42135b698033ce755b1719731fd4bb2628d4c8",
          "md5": "12ac2fe34bd0c42bdc64cd02ffa74120"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "pager",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT.aar",
          "url": "lpDevice-hingin-SNAPSHOT.aar",
          "size": 11256224,
          "sha512": "954b4722be6dbcbc42e4fbbe14c5269ba81ec0e7d422b81b21707c8914f956cf8863700e5a06fb64dd4df3512d2c0e17de6c89db0ac2dc6f80217cbad54a43e1",
          "sha256": "a3029508f58f6eebd021cdd83b057e79c97f06a16af83fe809fa5e4e7603b936",
          "sha1": "cd42135b698033ce755b1719731fd4bb2628d4c8",
          "md5": "12ac2fe34bd0c42bdc64cd02ffa74120"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT-sources.jar",
          "url": "lpDevice-hingin-SNAPSHOT-sources.jar",
          "size": 278759,
          "sha512": "49beeb34518087b3cf61aac17c7e32657cce8255af81fb9ec54592c299b8bae4be615b4babe88c1c4455dc8a1da44b1a24e7cb6562aec4430350c7c7a5d56239",
          "sha256": "0a697ef749648fa8c8276f929f7b5d8c91249e442f422f50e8e1a279abc90ac4",
          "sha1": "35029647f7eade26b3f4a16ac837d00310bde70e",
          "md5": "0e895349d02a0fc658d26860e2385a83"
        }
      ]
    }
  ]
}
