{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "lpDevice",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT.aar",
          "url": "lpDevice-hingin-SNAPSHOT.aar",
          "size": 13152280,
          "sha512": "a6e74f4e4acfab331b1ad389a69ff5b4963518ea01d853c71874d88811de0fd22592d540e8a4dd11a0c218dfb7e22fed8062fa5f2e551299541f9628a0d8c833",
          "sha256": "326559fe1a4402ce53a08d2ca88282ec3d616474675714bda5ab4d30ab5a8e58",
          "sha1": "6fef7c6c416b4e77d9cb1d58e5caa1ab8b9e4b82",
          "md5": "8d28ed97847cb67ef5bbc1cdefd26b56"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "pager",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT.aar",
          "url": "lpDevice-hingin-SNAPSHOT.aar",
          "size": 13152280,
          "sha512": "a6e74f4e4acfab331b1ad389a69ff5b4963518ea01d853c71874d88811de0fd22592d540e8a4dd11a0c218dfb7e22fed8062fa5f2e551299541f9628a0d8c833",
          "sha256": "326559fe1a4402ce53a08d2ca88282ec3d616474675714bda5ab4d30ab5a8e58",
          "sha1": "6fef7c6c416b4e77d9cb1d58e5caa1ab8b9e4b82",
          "md5": "8d28ed97847cb67ef5bbc1cdefd26b56"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT-sources.jar",
          "url": "lpDevice-hingin-SNAPSHOT-sources.jar",
          "size": 270489,
          "sha512": "9bfc2987423df345cb66285e509b070bf04182a453b24f5e441b7786a466066b7f8e9253de412365d2437bb95e09c84d638e48d55c103a7fae6d3cbecedd65ac",
          "sha256": "66929da1bca033bc91572814bf1cbfb11724a77d104e048b4a5291907584b922",
          "sha1": "36a35454fd62dcfb6673d6686f82e450c9f09074",
          "md5": "d5d58608b7de2f78b9e811153aca9b52"
        }
      ]
    }
  ]
}
