{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "lpDevice",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT.aar",
          "url": "lpDevice-hingin-SNAPSHOT.aar",
          "size": 13593841,
          "sha512": "f03aea5b9ff87767ba4e9e06aefbf7332072ecee93a0af5ee5ca3d68d2ffcec40c825e14ec6685024b6a678d679aad688b91e9547d4699cb801f86229c1b187d",
          "sha256": "76b0b46ffbcdecad038e88370394893ce5c5bd658d4ee9c5ede62664009241bc",
          "sha1": "555e54c4eb744a1ce05eb6dfd574a746dcd4f3cb",
          "md5": "d5b95b5f3b4ed8d0be3eddb2facb6397"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "pager",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT.aar",
          "url": "lpDevice-hingin-SNAPSHOT.aar",
          "size": 13593841,
          "sha512": "f03aea5b9ff87767ba4e9e06aefbf7332072ecee93a0af5ee5ca3d68d2ffcec40c825e14ec6685024b6a678d679aad688b91e9547d4699cb801f86229c1b187d",
          "sha256": "76b0b46ffbcdecad038e88370394893ce5c5bd658d4ee9c5ede62664009241bc",
          "sha1": "555e54c4eb744a1ce05eb6dfd574a746dcd4f3cb",
          "md5": "d5b95b5f3b4ed8d0be3eddb2facb6397"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lpDevice-hingin-SNAPSHOT-sources.jar",
          "url": "lpDevice-hingin-SNAPSHOT-sources.jar",
          "size": 274121,
          "sha512": "62edea177e8a079f6a1ed782e738d6969d4ff4b37dc01fc8aa4c3dd5ed4bc703174f78aae5db25838daf7e426b09b040e5fbf0d8dd4647cd8353738307248015",
          "sha256": "488ba9db8c24d58f3bf60722ba935e313f71e643a216d567ed504ef171b1a2b4",
          "sha1": "52c332130247bc96df68c0c129d5a80977ab155f",
          "md5": "04b990e41ab948ad3a2f0a13422b0b1b"
        }
      ]
    }
  ]
}
