{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "core",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "settingscompat",
          "version": {
            "requires": "1.1.4.1"
          },
          "excludes": [
            {
              "group": "androidx.appcompat",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "core-hingin-SNAPSHOT.aar",
          "url": "core-hingin-SNAPSHOT.aar",
          "size": 1135237,
          "sha512": "055657675a32d9e5b86842d7f11e65471593ab5dbd4fd7b257fb1e4c4aff009bf66ab1785c2f31119484c57fcb6efce14ce16ddd31d367302ef647b9f6d72115",
          "sha256": "cffcf31589bafac66d350743fecfa9349adeb8bd6cfea46209856ec3983ee508",
          "sha1": "fc986d47ed0591fd2a0163ee5862495f37fbf341",
          "md5": "01af80262bb3c41394a90ed7feeeb07d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.lsposed.hiddenapibypass",
          "module": "hiddenapibypass",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "settingscompat",
          "version": {
            "requires": "1.1.4.1"
          },
          "excludes": [
            {
              "group": "androidx.appcompat",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "core-hingin-SNAPSHOT.aar",
          "url": "core-hingin-SNAPSHOT.aar",
          "size": 1135237,
          "sha512": "055657675a32d9e5b86842d7f11e65471593ab5dbd4fd7b257fb1e4c4aff009bf66ab1785c2f31119484c57fcb6efce14ce16ddd31d367302ef647b9f6d72115",
          "sha256": "cffcf31589bafac66d350743fecfa9349adeb8bd6cfea46209856ec3983ee508",
          "sha1": "fc986d47ed0591fd2a0163ee5862495f37fbf341",
          "md5": "01af80262bb3c41394a90ed7feeeb07d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-hingin-SNAPSHOT-sources.jar",
          "url": "core-hingin-SNAPSHOT-sources.jar",
          "size": 264435,
          "sha512": "ba318d70b5d519bf3d2f9e19a9ba67cbe460b8d76aecab883d7a331204e1e924222848cb8fc2aa09725ed59df4b1d1a553eed7b61c7da7cc63fc581bd2c51be2",
          "sha256": "a96f23e42d5aad15da857cb4c665f3e08706c6a7536363b5e5992228d4a59cb1",
          "sha1": "54d4d5eacff7cc28ad16efd38191e2507f374a20",
          "md5": "7b9e65c6b0eaf0f0af1526c2a3f242c4"
        }
      ]
    }
  ]
}
