{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "core",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "settingscompat",
          "version": {
            "requires": "1.1.4.1"
          },
          "excludes": [
            {
              "group": "androidx.appcompat",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "core-hingin-SNAPSHOT.aar",
          "url": "core-hingin-SNAPSHOT.aar",
          "size": 1135227,
          "sha512": "82b9a762a2a40d876e0f8e4d077c82e5ae68c1d02b5418e657ff296295f786440838920bd1e02ed0392f6e9359b37749f6a1d74a26da7d7217b46eb0902edacd",
          "sha256": "555a93f935606ce470869f3c94dd9f39b220ff6eda121af43fc4cc657ab72335",
          "sha1": "88cf88fae27ab5e3ff8f3333eaf82f7e93efa872",
          "md5": "c87d3ae710a49ce4bd73b9a8b767d7af"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.lsposed.hiddenapibypass",
          "module": "hiddenapibypass",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "settingscompat",
          "version": {
            "requires": "1.1.4.1"
          },
          "excludes": [
            {
              "group": "androidx.appcompat",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "core-hingin-SNAPSHOT.aar",
          "url": "core-hingin-SNAPSHOT.aar",
          "size": 1135227,
          "sha512": "82b9a762a2a40d876e0f8e4d077c82e5ae68c1d02b5418e657ff296295f786440838920bd1e02ed0392f6e9359b37749f6a1d74a26da7d7217b46eb0902edacd",
          "sha256": "555a93f935606ce470869f3c94dd9f39b220ff6eda121af43fc4cc657ab72335",
          "sha1": "88cf88fae27ab5e3ff8f3333eaf82f7e93efa872",
          "md5": "c87d3ae710a49ce4bd73b9a8b767d7af"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-hingin-SNAPSHOT-sources.jar",
          "url": "core-hingin-SNAPSHOT-sources.jar",
          "size": 264435,
          "sha512": "ba318d70b5d519bf3d2f9e19a9ba67cbe460b8d76aecab883d7a331204e1e924222848cb8fc2aa09725ed59df4b1d1a553eed7b61c7da7cc63fc581bd2c51be2",
          "sha256": "a96f23e42d5aad15da857cb4c665f3e08706c6a7536363b5e5992228d4a59cb1",
          "sha1": "54d4d5eacff7cc28ad16efd38191e2507f374a20",
          "md5": "7b9e65c6b0eaf0f0af1526c2a3f242c4"
        }
      ]
    }
  ]
}
