{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "websocket",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "websocket-hingin-SNAPSHOT.aar",
          "url": "websocket-hingin-SNAPSHOT.aar",
          "size": 85264,
          "sha512": "952995b997006955724e4c3369d66abbcb1831416a5e6be5d1e36f32d94f1a22b180ce22e7627a5d00750f1196e1bdbe1dd362537534fb8dc79032d624862c6f",
          "sha256": "5c8e9daf8c5bf8d4137bb40e4e205f32c0cff86720f21a8f707e6b57580664c2",
          "sha1": "da800fb7c4491de36a53d15517e4dd318153dd79",
          "md5": "a018a00f5b7c58616eb00c1dfc36bff2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "websocket-hingin-SNAPSHOT.aar",
          "url": "websocket-hingin-SNAPSHOT.aar",
          "size": 85264,
          "sha512": "952995b997006955724e4c3369d66abbcb1831416a5e6be5d1e36f32d94f1a22b180ce22e7627a5d00750f1196e1bdbe1dd362537534fb8dc79032d624862c6f",
          "sha256": "5c8e9daf8c5bf8d4137bb40e4e205f32c0cff86720f21a8f707e6b57580664c2",
          "sha1": "da800fb7c4491de36a53d15517e4dd318153dd79",
          "md5": "a018a00f5b7c58616eb00c1dfc36bff2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "websocket-hingin-SNAPSHOT-sources.jar",
          "url": "websocket-hingin-SNAPSHOT-sources.jar",
          "size": 20371,
          "sha512": "b397fc88a42923ff2b6dd485bd7dd08c0216ab2e954bde1554dc3f5eb855bf23f42a080262b554643fd7a9ed93d5c2ee005f27b2ad7c20d5938e66798b53cbd1",
          "sha256": "28ae1e4e06d3efbfbb5e66b1a1e663eecca88a2b879d85a54d2ea2e4597d28ea",
          "sha1": "7a4e44d51a3873ff54d79257ead9676c811ed801",
          "md5": "c718031a9b1ababdf6d23c875486d1ea"
        }
      ]
    }
  ]
}
