{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "websocket",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "websocket-hingin-SNAPSHOT.aar",
          "url": "websocket-hingin-SNAPSHOT.aar",
          "size": 85274,
          "sha512": "d56900eb685788c7fcc7124184cc63f4c4f365296b942ff60de50077a384a68bb7722ea71ecb88ce7d9838f39a89aa5aef4cc58d77eb6a2b104a7b77ab2de54d",
          "sha256": "23d107a0a5924965202153f70caea820a87893ddf1f5dd5329e14ec21c870a14",
          "sha1": "a21d8ffeee2988c2dc34d05a23e7d3997dbac396",
          "md5": "24050b82127b3c09506223969238ef5d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "websocket-hingin-SNAPSHOT.aar",
          "url": "websocket-hingin-SNAPSHOT.aar",
          "size": 85274,
          "sha512": "d56900eb685788c7fcc7124184cc63f4c4f365296b942ff60de50077a384a68bb7722ea71ecb88ce7d9838f39a89aa5aef4cc58d77eb6a2b104a7b77ab2de54d",
          "sha256": "23d107a0a5924965202153f70caea820a87893ddf1f5dd5329e14ec21c870a14",
          "sha1": "a21d8ffeee2988c2dc34d05a23e7d3997dbac396",
          "md5": "24050b82127b3c09506223969238ef5d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "websocket-hingin-SNAPSHOT-sources.jar",
          "url": "websocket-hingin-SNAPSHOT-sources.jar",
          "size": 20371,
          "sha512": "b397fc88a42923ff2b6dd485bd7dd08c0216ab2e954bde1554dc3f5eb855bf23f42a080262b554643fd7a9ed93d5c2ee005f27b2ad7c20d5938e66798b53cbd1",
          "sha256": "28ae1e4e06d3efbfbb5e66b1a1e663eecca88a2b879d85a54d2ea2e4597d28ea",
          "sha1": "7a4e44d51a3873ff54d79257ead9676c811ed801",
          "md5": "c718031a9b1ababdf6d23c875486d1ea"
        }
      ]
    }
  ]
}
