{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "qrcode",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.angcyo",
          "module": "QrCodeZxingZbar",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "qrcode-hingin-SNAPSHOT.aar",
          "url": "qrcode-hingin-SNAPSHOT.aar",
          "size": 121869,
          "sha512": "b3382d328d4ffc506dbd679b36a4f600fc0d1a1871e30c7d143044565fcfa37b03d133e6c86aefe6c74c780c959ac0da7b6af4ce316178d561c6974048356c03",
          "sha256": "e8056831f23f135c9767ebc5b230bea404193a966506a68174366c19241cffba",
          "sha1": "b4c08167f7e15d2874a363cdc738cd812da7370f",
          "md5": "dc38c3b5ff75bab6a10b758156a3eb19"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "QrCodeZxingZbar",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "qrcode-hingin-SNAPSHOT.aar",
          "url": "qrcode-hingin-SNAPSHOT.aar",
          "size": 121869,
          "sha512": "b3382d328d4ffc506dbd679b36a4f600fc0d1a1871e30c7d143044565fcfa37b03d133e6c86aefe6c74c780c959ac0da7b6af4ce316178d561c6974048356c03",
          "sha256": "e8056831f23f135c9767ebc5b230bea404193a966506a68174366c19241cffba",
          "sha1": "b4c08167f7e15d2874a363cdc738cd812da7370f",
          "md5": "dc38c3b5ff75bab6a10b758156a3eb19"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "qrcode-hingin-SNAPSHOT-sources.jar",
          "url": "qrcode-hingin-SNAPSHOT-sources.jar",
          "size": 36885,
          "sha512": "7581cd29c0ebceb763b6d468e488a529b234e7741bb4e53be72541189351e1f3d262ae6cbd8bec184eeace2a6c42d653da9d14daa414e3b28bb7460b02feec1e",
          "sha256": "0237f40c19e05e43d5426e63e84c12c201f015a127e8c069fc7e0e0ee4a76be1",
          "sha1": "471e36f61614c840b20ae26b3c50eba0628a57d6",
          "md5": "a2eb93562d21e551158b8dce3ee04c40"
        }
      ]
    }
  ]
}
