{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "canvas2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT.aar",
          "url": "canvas2-hingin-SNAPSHOT.aar",
          "size": 384148,
          "sha512": "75412a8ca3d218f441ea1d60c92e126365fb12a530cdd6e4701b02ef4c6bcee072712d4f6f722b4a47dda1792b30c2180360f55d93030493c5bab00d7ae32fd8",
          "sha256": "13535c112ace12b45f9ab0ef46e5bebe2dbf67762e1f3b3b84240d434c5057cd",
          "sha1": "76eaf0b334bf8accddcd91593e5095a8fcef73c2",
          "md5": "869aa6b809d62325d175e63a5cdb7d9a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT.aar",
          "url": "canvas2-hingin-SNAPSHOT.aar",
          "size": 384148,
          "sha512": "75412a8ca3d218f441ea1d60c92e126365fb12a530cdd6e4701b02ef4c6bcee072712d4f6f722b4a47dda1792b30c2180360f55d93030493c5bab00d7ae32fd8",
          "sha256": "13535c112ace12b45f9ab0ef46e5bebe2dbf67762e1f3b3b84240d434c5057cd",
          "sha1": "76eaf0b334bf8accddcd91593e5095a8fcef73c2",
          "md5": "869aa6b809d62325d175e63a5cdb7d9a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT-sources.jar",
          "url": "canvas2-hingin-SNAPSHOT-sources.jar",
          "size": 241479,
          "sha512": "35d2f8b23bce97b7365989e0b646bdbff31222cc84bd265465d2b9e49cd417d30cdd1096ea54cd43a221d4d1dae1e3c0ab5856ba8b8de4a957d349b8c25ddb75",
          "sha256": "68102bee5ad675442deba1b830ed797b0ff3bbe05bdc13993a2fdb71d90f4970",
          "sha1": "bc1c6307388445d645d57310c7cbf70ff9e88943",
          "md5": "962cb6e11943b3a0243426ca48049c29"
        }
      ]
    }
  ]
}
