{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "canvas2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT.aar",
          "url": "canvas2-hingin-SNAPSHOT.aar",
          "size": 391099,
          "sha512": "8b7c8c0428875340530563ce106a0738b58d08c3354a9d7a240403af52609b326b317daa73aea031ed9a5d68926195fd12086f99f1ebefcb1770cad3461152a2",
          "sha256": "c518ab364149c96d215a77aedb30577a5ba059c112d3968a8ffd57dd05f28c38",
          "sha1": "ca60a7575643f2caaeeb74f615f8cbd886b67c4c",
          "md5": "af052addb9379d4e3da8400cc6d11cb9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT.aar",
          "url": "canvas2-hingin-SNAPSHOT.aar",
          "size": 391099,
          "sha512": "8b7c8c0428875340530563ce106a0738b58d08c3354a9d7a240403af52609b326b317daa73aea031ed9a5d68926195fd12086f99f1ebefcb1770cad3461152a2",
          "sha256": "c518ab364149c96d215a77aedb30577a5ba059c112d3968a8ffd57dd05f28c38",
          "sha1": "ca60a7575643f2caaeeb74f615f8cbd886b67c4c",
          "md5": "af052addb9379d4e3da8400cc6d11cb9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT-sources.jar",
          "url": "canvas2-hingin-SNAPSHOT-sources.jar",
          "size": 245567,
          "sha512": "873260cb1672c888ffb1f7469a0bbfc7e5f1c552b44bdb0a6345b35a19655aec90190e07d0ffc21d0d316ba870f4a2a1f01f6a93d1fee8b63d2bdec5815e80a5",
          "sha256": "51b2ae49984d7f990025eef888da670c7eff068813a22d0d77e2cc21a2a26a93",
          "sha1": "de25e1122ee3b1e4f3a222afcddc5a337b072d8d",
          "md5": "63a99c01122f7385ca5fe2eb4a31e575"
        }
      ]
    }
  ]
}
