{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "canvas2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT.aar",
          "url": "canvas2-hingin-SNAPSHOT.aar",
          "size": 383805,
          "sha512": "595957d3b800faad70b4be9312206f8f00e8df6fe3b314fed0a10daff0dcbe8194787435aada5debb9811027d26e0aca097d721f5031b57acdcf76f83e9cdde4",
          "sha256": "7c6b0506e0e32e7683439adc85e31d3b9b0ef4426f16d6c3ef9ae9a1d785c4de",
          "sha1": "4d956df964ae88eec00ff3f12bf62ed7f821346c",
          "md5": "55ba59cdcdc65710b46d2c97b4b8983e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT.aar",
          "url": "canvas2-hingin-SNAPSHOT.aar",
          "size": 383805,
          "sha512": "595957d3b800faad70b4be9312206f8f00e8df6fe3b314fed0a10daff0dcbe8194787435aada5debb9811027d26e0aca097d721f5031b57acdcf76f83e9cdde4",
          "sha256": "7c6b0506e0e32e7683439adc85e31d3b9b0ef4426f16d6c3ef9ae9a1d785c4de",
          "sha1": "4d956df964ae88eec00ff3f12bf62ed7f821346c",
          "md5": "55ba59cdcdc65710b46d2c97b4b8983e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT-sources.jar",
          "url": "canvas2-hingin-SNAPSHOT-sources.jar",
          "size": 241293,
          "sha512": "11e45b4621dde36b6a035512e744bbb45956d3ad78227cae8648a5221083d8d81f783958714380f9ba1fd72ac83d32b579df21d49f3f4585998cefd88c8ad544",
          "sha256": "2fd2f27a07ba1289a2b930b0801fe6d9babb5f0bea55bdda2a83cb034c1c455a",
          "sha1": "4fc878391300b2acd438883aaf6ee22e001675d6",
          "md5": "7aa8128bb8b4ca1a4255d647389523f2"
        }
      ]
    }
  ]
}
