{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "canvas2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT.aar",
          "url": "canvas2-hingin-SNAPSHOT.aar",
          "size": 392119,
          "sha512": "c51c7ea8b1533bda74e7b64f24bda47353e15360063a03564b4c719dc50185342a9ed2a15358fbe9f2b01520d2162319636ca3fe4219433d5253dcaa72baa445",
          "sha256": "6f2aa8aa83be6ed2ce2fe6468440b61231393cfed404103fd6efedcf99205dd5",
          "sha1": "162358e31fe9e11e13b3461909509586cf5d288c",
          "md5": "3c4a9634c738d2f2676d73aa796adb08"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT.aar",
          "url": "canvas2-hingin-SNAPSHOT.aar",
          "size": 392119,
          "sha512": "c51c7ea8b1533bda74e7b64f24bda47353e15360063a03564b4c719dc50185342a9ed2a15358fbe9f2b01520d2162319636ca3fe4219433d5253dcaa72baa445",
          "sha256": "6f2aa8aa83be6ed2ce2fe6468440b61231393cfed404103fd6efedcf99205dd5",
          "sha1": "162358e31fe9e11e13b3461909509586cf5d288c",
          "md5": "3c4a9634c738d2f2676d73aa796adb08"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "canvas2-hingin-SNAPSHOT-sources.jar",
          "url": "canvas2-hingin-SNAPSHOT-sources.jar",
          "size": 246225,
          "sha512": "ea347ed83f6fc34fe8dc0e4091a13ae90df97fa8effb9c7aae9ab53c40e1d47237ec134a4559feb77ba233feaf330d738aa0b9c6f5d85e32aa05fd30feaa26dd",
          "sha256": "add488ffee1afc6d1ca04025c052dfc02aed4ce9cbe907bb80d3293c6e109e6e",
          "sha1": "a17c59ca288069848002ea9bec7959db2a1311ad",
          "md5": "2330f8ff985d564068418eb0a9c1bb9a"
        }
      ]
    }
  ]
}
