{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "opencv",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "opencv-hingin-SNAPSHOT.aar",
          "url": "opencv-hingin-SNAPSHOT.aar",
          "size": 13256278,
          "sha512": "8d964697efed4992cbb8db5bb55d5e231687b4e253d40e5721d5038698b01a9328ac8986bee052764a1225f9a4633715d612a38e150d5876c2e36ad12820c99a",
          "sha256": "a3491730f37d804ed5247375fef8d1b28cef4904ea52cfc239b168571e60342c",
          "sha1": "d01947622046e23711fb7432ed0bb6556dc3e899",
          "md5": "df69f3a5cebb5864173348771fef2871"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "opencv-hingin-SNAPSHOT.aar",
          "url": "opencv-hingin-SNAPSHOT.aar",
          "size": 13256278,
          "sha512": "8d964697efed4992cbb8db5bb55d5e231687b4e253d40e5721d5038698b01a9328ac8986bee052764a1225f9a4633715d612a38e150d5876c2e36ad12820c99a",
          "sha256": "a3491730f37d804ed5247375fef8d1b28cef4904ea52cfc239b168571e60342c",
          "sha1": "d01947622046e23711fb7432ed0bb6556dc3e899",
          "md5": "df69f3a5cebb5864173348771fef2871"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "opencv-hingin-SNAPSHOT-sources.jar",
          "url": "opencv-hingin-SNAPSHOT-sources.jar",
          "size": 9469,
          "sha512": "9bc0e9e9b8c974ff29cbb1b8dd472ee8bef17686c9abd1efc5e72db4a87c3cbd160e2b8beb383c6838cb3cd52cf53d70d822e8e0fff8b371f80d4f455d0773a9",
          "sha256": "35089c8ad9d5a8b2fc5d4231746cc97e2c35f950ea9d4eb48a42482670487206",
          "sha1": "88fddabc24a7701d40ca7064410f70a2c8dc051b",
          "md5": "cbb5c27630b5f309048f9a74c677a6c7"
        }
      ]
    }
  ]
}
