{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "opencv",
    "version": "20250524",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "opencv-20250524.aar",
          "url": "opencv-20250524.aar",
          "size": 13262531,
          "sha512": "6460c9f3a1cf5aa7eb30a554fff93c4a462c6a39930307aaa5ef65390ee8f58ccf9f53c7b455ef8108249ec514d854ec875e5be0d53b28400b78a5a4423c81e0",
          "sha256": "a52cf609fb9f51c30f5f276dc919f4c6af56417dc90785527ddd502d5fe56df1",
          "sha1": "b093e25ced6b70b1136355a054bf732bba15729f",
          "md5": "c553904a3e0f15444d4ea62e07ed3ca8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "opencv-20250524.aar",
          "url": "opencv-20250524.aar",
          "size": 13262531,
          "sha512": "6460c9f3a1cf5aa7eb30a554fff93c4a462c6a39930307aaa5ef65390ee8f58ccf9f53c7b455ef8108249ec514d854ec875e5be0d53b28400b78a5a4423c81e0",
          "sha256": "a52cf609fb9f51c30f5f276dc919f4c6af56417dc90785527ddd502d5fe56df1",
          "sha1": "b093e25ced6b70b1136355a054bf732bba15729f",
          "md5": "c553904a3e0f15444d4ea62e07ed3ca8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "opencv-20250524-sources.jar",
          "url": "opencv-20250524-sources.jar",
          "size": 9469,
          "sha512": "9bc0e9e9b8c974ff29cbb1b8dd472ee8bef17686c9abd1efc5e72db4a87c3cbd160e2b8beb383c6838cb3cd52cf53d70d822e8e0fff8b371f80d4f455d0773a9",
          "sha256": "35089c8ad9d5a8b2fc5d4231746cc97e2c35f950ea9d4eb48a42482670487206",
          "sha1": "88fddabc24a7701d40ca7064410f70a2c8dc051b",
          "md5": "cbb5c27630b5f309048f9a74c677a6c7"
        }
      ]
    }
  ]
}
