{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fragment",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-hingin-SNAPSHOT.aar",
          "url": "fragment-hingin-SNAPSHOT.aar",
          "size": 302094,
          "sha512": "f45e1994b256b686e9b436f0ac54bf301e8a84930212c0dad53b0c2ebe410ccaaaf6d37b93e3a2566e8da11382f17697abee768408ba87bee661e72b890fc1fb",
          "sha256": "05e7c9faf559a6af3317a08a1f4f1285c5182000c3dbfb321428e0e11ed5feee",
          "sha1": "a0cabdf0f7f838f1d913516ce553ebac93195d6e",
          "md5": "8d338089dbfb075302cc6032b5e73be5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-hingin-SNAPSHOT.aar",
          "url": "fragment-hingin-SNAPSHOT.aar",
          "size": 302094,
          "sha512": "f45e1994b256b686e9b436f0ac54bf301e8a84930212c0dad53b0c2ebe410ccaaaf6d37b93e3a2566e8da11382f17697abee768408ba87bee661e72b890fc1fb",
          "sha256": "05e7c9faf559a6af3317a08a1f4f1285c5182000c3dbfb321428e0e11ed5feee",
          "sha1": "a0cabdf0f7f838f1d913516ce553ebac93195d6e",
          "md5": "8d338089dbfb075302cc6032b5e73be5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fragment-hingin-SNAPSHOT-sources.jar",
          "url": "fragment-hingin-SNAPSHOT-sources.jar",
          "size": 114953,
          "sha512": "28e2eae515a897ae6b238519f970557edfef7b1a61cb0200ccb2df3d49ae02496f370937a207ce44dc3952b4a43507b5a3ef245e6cdb5e6b5a9ed1c4af0c8c06",
          "sha256": "0a780bb22cfe3e96f6428d694504a6d6211039aa80ba173e07e84daaffc78000",
          "sha1": "c4aa14b494183e68eb397049dc58ee8bb793d0a8",
          "md5": "2f895e4600e89133530329ef9ba69326"
        }
      ]
    }
  ]
}
