{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fragment",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-hingin-SNAPSHOT.aar",
          "url": "fragment-hingin-SNAPSHOT.aar",
          "size": 302084,
          "sha512": "514141367cc92f9fcc40f835b6f1f920395237ece5fc617acfdfb4f0e4343f934b475cd2904ecd08aa648a0b46c6386c5d62ce39c3ef750a8ff51e8fd799c97b",
          "sha256": "dc2ac6b0687cc0bf791fe3514cb39098d423cb8d5e2d9b5117754bda8190fe58",
          "sha1": "0485ff1aa0a5844e2eb1050cf3fa19a81348c89a",
          "md5": "a4712dde41334861a552402e49b498c6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-hingin-SNAPSHOT.aar",
          "url": "fragment-hingin-SNAPSHOT.aar",
          "size": 302084,
          "sha512": "514141367cc92f9fcc40f835b6f1f920395237ece5fc617acfdfb4f0e4343f934b475cd2904ecd08aa648a0b46c6386c5d62ce39c3ef750a8ff51e8fd799c97b",
          "sha256": "dc2ac6b0687cc0bf791fe3514cb39098d423cb8d5e2d9b5117754bda8190fe58",
          "sha1": "0485ff1aa0a5844e2eb1050cf3fa19a81348c89a",
          "md5": "a4712dde41334861a552402e49b498c6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fragment-hingin-SNAPSHOT-sources.jar",
          "url": "fragment-hingin-SNAPSHOT-sources.jar",
          "size": 114953,
          "sha512": "28e2eae515a897ae6b238519f970557edfef7b1a61cb0200ccb2df3d49ae02496f370937a207ce44dc3952b4a43507b5a3ef245e6cdb5e6b5a9ed1c4af0c8c06",
          "sha256": "0a780bb22cfe3e96f6428d694504a6d6211039aa80ba173e07e84daaffc78000",
          "sha1": "c4aa14b494183e68eb397049dc58ee8bb793d0a8",
          "md5": "2f895e4600e89133530329ef9ba69326"
        }
      ]
    }
  ]
}
