{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "image",
    "version": "2025081202",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view-androidx",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "image-2025081202.aar",
          "url": "image-2025081202.aar",
          "size": 63818,
          "sha512": "6810fdd72e73fd4dca1aa7caab81e16a34e8cbbe584ed9ead336f2b8779349c3e528604266d1b5b48d31eca4831dfac168bb01bed76d12320b7cc6500a1d3a38",
          "sha256": "1723893227c710e1860bdc6256f38b8d496fea90d2259f457283cc5686c6d4a7",
          "sha1": "f42623a53431d986bf28642dc2d15f075e41fabf",
          "md5": "475e424c5520d0ca951b4083eda89b91"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view-androidx",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "image-2025081202.aar",
          "url": "image-2025081202.aar",
          "size": 63818,
          "sha512": "6810fdd72e73fd4dca1aa7caab81e16a34e8cbbe584ed9ead336f2b8779349c3e528604266d1b5b48d31eca4831dfac168bb01bed76d12320b7cc6500a1d3a38",
          "sha256": "1723893227c710e1860bdc6256f38b8d496fea90d2259f457283cc5686c6d4a7",
          "sha1": "f42623a53431d986bf28642dc2d15f075e41fabf",
          "md5": "475e424c5520d0ca951b4083eda89b91"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "image-2025081202-sources.jar",
          "url": "image-2025081202-sources.jar",
          "size": 11377,
          "sha512": "4843b0be50819ef5c323ea3b9b0f416996e5e912b989df5bca3e7312c4f3ced4c4909a93b17062b9a4734fdbb81c08fcd28ead267652123cb70e08c86bdd7406",
          "sha256": "2ccb97dd749123b0c2a43dbe51203bdf05473c14767fcc5b36c805e829b39174",
          "sha1": "867ab9fac9313be81374d3da7b51dea1b4831434",
          "md5": "dd3b9e445581af707a59cd26b2b2d37d"
        }
      ]
    }
  ]
}
