{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "coroutine",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-hingin-SNAPSHOT.aar",
          "url": "coroutine-hingin-SNAPSHOT.aar",
          "size": 41260,
          "sha512": "f74324529410548beaa6bbff2e4cacfcf94d5b39ff04cc694096bd5280853615aded613b645ca28d259d9cb89ec905c6fd6ee3432f1381638b59ceeb0b7651ab",
          "sha256": "936875ce21e7fd212443bcbc72d33e54b453c26e0311f49387599e10c539a042",
          "sha1": "6a68bae9ab81a4f17d26b9c1ed113b58819fe2c2",
          "md5": "3f119c20d408a681174ea5ab056c0b73"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-hingin-SNAPSHOT.aar",
          "url": "coroutine-hingin-SNAPSHOT.aar",
          "size": 41260,
          "sha512": "f74324529410548beaa6bbff2e4cacfcf94d5b39ff04cc694096bd5280853615aded613b645ca28d259d9cb89ec905c6fd6ee3432f1381638b59ceeb0b7651ab",
          "sha256": "936875ce21e7fd212443bcbc72d33e54b453c26e0311f49387599e10c539a042",
          "sha1": "6a68bae9ab81a4f17d26b9c1ed113b58819fe2c2",
          "md5": "3f119c20d408a681174ea5ab056c0b73"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "coroutine-hingin-SNAPSHOT-sources.jar",
          "url": "coroutine-hingin-SNAPSHOT-sources.jar",
          "size": 8205,
          "sha512": "c102719b1a731682b32cc08f938c37e2a8f9682806190afb5b42e92aaa87479b0ed2c1892f37eb12fa9c8cfb6fc6f6e10e12f819d4a7d1f868ab3de486be3790",
          "sha256": "d1ab8db3c19e573913fcf7f50f165dd92da8b38db444361af9bc16cf0a6b4476",
          "sha1": "a539fb4ac2e08ba51c221191033ff26618f441b7",
          "md5": "2dc2cb525a231a687b061c0c0e22111f"
        }
      ]
    }
  ]
}
