{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "vector",
    "version": "2025081203",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.LaserPeckerIst",
          "module": "sharp",
          "version": {
            "requires": "1.1.3.40"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "Android-Kabeja",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "vector-2025081203.aar",
          "url": "vector-2025081203.aar",
          "size": 123229,
          "sha512": "3ff1c36c81327f767c79856161f3fdcaca7e0e847b33ebe752914822db1d147623beed8449afc7b227e227777c73c29dbd5113a977c89b6523ad1e3b55924013",
          "sha256": "5eaf0bde5725c2310d0af61e12fc08d237d84bc95577e5cf69314e6bf6599157",
          "sha1": "e7ecc4c663d3105bbfe358cb289a810c8266b2b9",
          "md5": "aba0568e5fc7b649ae52b60fc0cf68ee"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "sharp",
          "version": {
            "requires": "1.1.3.40"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "Android-Kabeja",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "vector-2025081203.aar",
          "url": "vector-2025081203.aar",
          "size": 123229,
          "sha512": "3ff1c36c81327f767c79856161f3fdcaca7e0e847b33ebe752914822db1d147623beed8449afc7b227e227777c73c29dbd5113a977c89b6523ad1e3b55924013",
          "sha256": "5eaf0bde5725c2310d0af61e12fc08d237d84bc95577e5cf69314e6bf6599157",
          "sha1": "e7ecc4c663d3105bbfe358cb289a810c8266b2b9",
          "md5": "aba0568e5fc7b649ae52b60fc0cf68ee"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "vector-2025081203-sources.jar",
          "url": "vector-2025081203-sources.jar",
          "size": 76781,
          "sha512": "814f0f319169284854e002896658cc7ef1d8f66fd6a50dd505ee3482c19d5d1c80b30d7f64fe75a1aa8b9c7f14e0ee4c5129a889d529a2f660a4297d199def08",
          "sha256": "927ca8d930ea398d40a05753227cd201a537567af897f4b5fcee29233cb0c6ff",
          "sha1": "8e2ea39660a06049548df9da17ef7f09258235ee",
          "md5": "85617266dc591d5b52651cba363d1630"
        }
      ]
    }
  ]
}
