{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "github",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bus",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "ViewPagerLayoutManager",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.github.XHGInc",
          "module": "FloatWindow",
          "version": {
            "requires": "1.0.9.5"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "ColorPicker",
          "version": {
            "requires": "1.1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "github-hingin-SNAPSHOT.aar",
          "url": "github-hingin-SNAPSHOT.aar",
          "size": 151125,
          "sha512": "61cb225b31b70c94ab3b28ec59c2873f9685953efe20ac623622b9f2f0280510ff80b880a2847dbf507b070644c6e5ff5c70d563dc8176e9ca030bd4585b26b9",
          "sha256": "60fcb261fcb3af407c19e67d7410e361aac407fdef758c48cec8e63a191b5a94",
          "sha1": "0f776a929d0a4dcbf4c699bf5c78c0c3ec2857b7",
          "md5": "63db8dd7cc78a4fad14b0b73f1c7e076"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bus",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "ViewPagerLayoutManager",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.github.XHGInc",
          "module": "FloatWindow",
          "version": {
            "requires": "1.0.9.5"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "ColorPicker",
          "version": {
            "requires": "1.1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "github-hingin-SNAPSHOT.aar",
          "url": "github-hingin-SNAPSHOT.aar",
          "size": 151125,
          "sha512": "61cb225b31b70c94ab3b28ec59c2873f9685953efe20ac623622b9f2f0280510ff80b880a2847dbf507b070644c6e5ff5c70d563dc8176e9ca030bd4585b26b9",
          "sha256": "60fcb261fcb3af407c19e67d7410e361aac407fdef758c48cec8e63a191b5a94",
          "sha1": "0f776a929d0a4dcbf4c699bf5c78c0c3ec2857b7",
          "md5": "63db8dd7cc78a4fad14b0b73f1c7e076"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "github-hingin-SNAPSHOT-sources.jar",
          "url": "github-hingin-SNAPSHOT-sources.jar",
          "size": 76343,
          "sha512": "bc2334937b95328adc7d4a87c42d47b7a8e6ec7254e2496625c2f0ce0f4227a3e24daadacecde954ed67dd999845d6d198bfb4a1eb58a7942e51374fd2d55458",
          "sha256": "dfcb8cda8c9b0661f46a54bcdf692ee6867cc7aca7b313ba4e691a84a9e80793",
          "sha1": "3be5d61251853d37bf192e7a8f4957f1b93e8fb6",
          "md5": "3b1c9248a20d22bd48bf7b337048b45c"
        }
      ]
    }
  ]
}
