{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "picker",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "UICoreDemo.UICore",
          "module": "camera",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.angcyo",
          "module": "pager",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "picker-hingin-SNAPSHOT.aar",
          "url": "picker-hingin-SNAPSHOT.aar",
          "size": 353031,
          "sha512": "3f7803ccf85d5f26a0bae60a5c93dd8485c7b6552f2fe431cc1eb8c9b76c245f35a2e3b9685d5d47396c44be17342418e57c5ebfb727c163bb34c4427702688e",
          "sha256": "13ce6bc77189d0ddf33fcb4a51b0fffeadc56dc6385dc8d0321dff37dc3ca3f3",
          "sha1": "942d2f0f8f73b5cc5e3bec5c8b3771c433d870a7",
          "md5": "2c27d55dcc499f5cdc0c67faee5415cb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.angcyo",
          "module": "record",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.yalantis",
          "module": "ucrop",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "UICoreDemo.UICore",
          "module": "camera",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.angcyo",
          "module": "pager",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "picker-hingin-SNAPSHOT.aar",
          "url": "picker-hingin-SNAPSHOT.aar",
          "size": 353031,
          "sha512": "3f7803ccf85d5f26a0bae60a5c93dd8485c7b6552f2fe431cc1eb8c9b76c245f35a2e3b9685d5d47396c44be17342418e57c5ebfb727c163bb34c4427702688e",
          "sha256": "13ce6bc77189d0ddf33fcb4a51b0fffeadc56dc6385dc8d0321dff37dc3ca3f3",
          "sha1": "942d2f0f8f73b5cc5e3bec5c8b3771c433d870a7",
          "md5": "2c27d55dcc499f5cdc0c67faee5415cb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "picker-hingin-SNAPSHOT-sources.jar",
          "url": "picker-hingin-SNAPSHOT-sources.jar",
          "size": 80739,
          "sha512": "30e92badb8c027026e54fe36d59394017ef98f0b078a54470e4b5b6aec1b672073cdedd547051689df8fc90473a2bbbdb42aac5b0be35391b2cf5a68a23d85f2",
          "sha256": "983c65a8bfc4789e0ca5dbd67583668a4a830eb1de15ff81d21b27adf608bad3",
          "sha1": "7303227b3b22fd540d8be3e8e2698a00fb150641",
          "md5": "331d5e7617817453c98cf2abcfccdaba"
        }
      ]
    }
  ]
}
