{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "pager",
    "version": "2025081202",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "pager-2025081202.aar",
          "url": "pager-2025081202.aar",
          "size": 113537,
          "sha512": "fbffc35cd8b3582c1f6f832518587d3140fdfffb6691ff9c43919782afaed670b7016b2205afd22cf599477180922c0dea9026d25b7fb278ca7f3fcf3f31e538",
          "sha256": "ea6b49d95099655ed40b496fd6085a433e805d0f5255d36535234e5dd7d9e6c4",
          "sha1": "a0df2344d5261817ec5c18e9020defcdaf904bdd",
          "md5": "80c90f2c307631f97101e052968155e1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "2025081202"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "pager-2025081202.aar",
          "url": "pager-2025081202.aar",
          "size": 113537,
          "sha512": "fbffc35cd8b3582c1f6f832518587d3140fdfffb6691ff9c43919782afaed670b7016b2205afd22cf599477180922c0dea9026d25b7fb278ca7f3fcf3f31e538",
          "sha256": "ea6b49d95099655ed40b496fd6085a433e805d0f5255d36535234e5dd7d9e6c4",
          "sha1": "a0df2344d5261817ec5c18e9020defcdaf904bdd",
          "md5": "80c90f2c307631f97101e052968155e1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pager-2025081202-sources.jar",
          "url": "pager-2025081202-sources.jar",
          "size": 27195,
          "sha512": "a5a2d3bd1ba900d128f312d5af184e71e6dc3f24217bf26ee423dd4637171aec3e3fb5113296fa0204db2a04d746aa599d73f7b3079da5b7c4f574111e10470b",
          "sha256": "7557d320da7cc7a008012fa80ffdfa0ea0cdb8d98713ca9713a7c977c253432e",
          "sha1": "837d901b476a1b5ed98001bd360fddbc4c84dfc3",
          "md5": "0aad62dded835d90ac484580ddc6bbc2"
        }
      ]
    }
  ]
}
