{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "engrave2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1682267,
          "sha512": "8d6540e1688fd07e2681be067f8bb362ed8439ae83c99cfd8f50644b68bb90d01ff53adb79be0133e56c9d1bb4b557a2a28678728a602b9108ae245cb60efa6a",
          "sha256": "6cf7619f00035f1dd058c16b02ccedff52fa1f7d8c2ce1cad465dedb797f1b47",
          "sha1": "986f0eb65090f697d004472553f3b74bf6283329",
          "md5": "b21da849c4dc20dbb25768372b6ff079"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1682267,
          "sha512": "8d6540e1688fd07e2681be067f8bb362ed8439ae83c99cfd8f50644b68bb90d01ff53adb79be0133e56c9d1bb4b557a2a28678728a602b9108ae245cb60efa6a",
          "sha256": "6cf7619f00035f1dd058c16b02ccedff52fa1f7d8c2ce1cad465dedb797f1b47",
          "sha1": "986f0eb65090f697d004472553f3b74bf6283329",
          "md5": "b21da849c4dc20dbb25768372b6ff079"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT-sources.jar",
          "url": "engrave2-hingin-SNAPSHOT-sources.jar",
          "size": 117955,
          "sha512": "ebb135cd7dfaf93abb98ea5361074cdf76ce9f05fa2b70d73d60fd6fb725b857c0cfe295c9df279a4b0489d3f9f9bffda905b4a1313da87c26bf58a29a1b973a",
          "sha256": "727ce3b55b0ea4a801631a84cfedd81d0c0fdd92b674f0f306ded8c03695e650",
          "sha1": "f45c5e3d8f4bbb9fce786bddbdddad0c8df2abe0",
          "md5": "98161ec26916e66b24fad7e745506f2a"
        }
      ]
    }
  ]
}
