{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "engrave2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1676822,
          "sha512": "d489bfb15be47cc13dcfecc75a1584800a6de62811efcc7b930108558f29e4f8ef2eba0b790ee93a3edd855da709fe0140a0ed290edbb8efb7819d0448afda63",
          "sha256": "e11c890b7f6bd61782d05b944abd878d040dab798632c4990c3bc74ce5814d93",
          "sha1": "cab1a9aae1ad36220153f842b528ffdffece17d1",
          "md5": "a0d5482dab75d3472636ee6ee1f0a7d9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1676822,
          "sha512": "d489bfb15be47cc13dcfecc75a1584800a6de62811efcc7b930108558f29e4f8ef2eba0b790ee93a3edd855da709fe0140a0ed290edbb8efb7819d0448afda63",
          "sha256": "e11c890b7f6bd61782d05b944abd878d040dab798632c4990c3bc74ce5814d93",
          "sha1": "cab1a9aae1ad36220153f842b528ffdffece17d1",
          "md5": "a0d5482dab75d3472636ee6ee1f0a7d9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT-sources.jar",
          "url": "engrave2-hingin-SNAPSHOT-sources.jar",
          "size": 117955,
          "sha512": "ebb135cd7dfaf93abb98ea5361074cdf76ce9f05fa2b70d73d60fd6fb725b857c0cfe295c9df279a4b0489d3f9f9bffda905b4a1313da87c26bf58a29a1b973a",
          "sha256": "727ce3b55b0ea4a801631a84cfedd81d0c0fdd92b674f0f306ded8c03695e650",
          "sha1": "f45c5e3d8f4bbb9fce786bddbdddad0c8df2abe0",
          "md5": "98161ec26916e66b24fad7e745506f2a"
        }
      ]
    }
  ]
}
