{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "engrave2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1682379,
          "sha512": "f2cba8cfba970c037a8e8b4ffb32636ef0366e2746babcb5bb44ca079be9842809b0f2ed1e53896f44bb7c335d86ab7244c984422c36305aa0e91df79415fca5",
          "sha256": "91a150a7fbb74417c7f6abde8d320f44493202fc2cf54bde8b90a7b9eed9a5e5",
          "sha1": "fd3c86992a771b952943a7f232150ea78a907b45",
          "md5": "73c399711f1afb5bb60b6dec3992d737"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1682379,
          "sha512": "f2cba8cfba970c037a8e8b4ffb32636ef0366e2746babcb5bb44ca079be9842809b0f2ed1e53896f44bb7c335d86ab7244c984422c36305aa0e91df79415fca5",
          "sha256": "91a150a7fbb74417c7f6abde8d320f44493202fc2cf54bde8b90a7b9eed9a5e5",
          "sha1": "fd3c86992a771b952943a7f232150ea78a907b45",
          "md5": "73c399711f1afb5bb60b6dec3992d737"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT-sources.jar",
          "url": "engrave2-hingin-SNAPSHOT-sources.jar",
          "size": 118321,
          "sha512": "78fdafff1a85ae257b5f3151e575f2bbdaa684ea89c434ab32825b0bff3e2a14ac8ccc25fd77f4443bfd4eab7c3305c8c4447d7c5be94b9bd090594b3be10e04",
          "sha256": "dcc50b914b1b6dd4a11d3ec67842aaaac7b0f748ab8defb2edaa2d05b056c5fd",
          "sha1": "480623bb16dec5c613c893ff0dee8b8a2d9f80e2",
          "md5": "4c76d73f78a44c0cb85c75d825c51ad6"
        }
      ]
    }
  ]
}
