{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "engrave2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1676255,
          "sha512": "f49918a2c23ab5a93f9464ecf60e8ef342274df80049352abc7cb83dfd09709a60c8ad529d5298911e37097704765e8774449a40b49be6833b43d7fa6c6248d1",
          "sha256": "42994dcc70fa9dd9624dc161c313b4af7c202d547b3784ace96ebffc8f4178b6",
          "sha1": "00d1b602d9f48407c6d5bbd246a750955ecbae3a",
          "md5": "60a41acbd0ec3ad55d88f9c55759e882"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1676255,
          "sha512": "f49918a2c23ab5a93f9464ecf60e8ef342274df80049352abc7cb83dfd09709a60c8ad529d5298911e37097704765e8774449a40b49be6833b43d7fa6c6248d1",
          "sha256": "42994dcc70fa9dd9624dc161c313b4af7c202d547b3784ace96ebffc8f4178b6",
          "sha1": "00d1b602d9f48407c6d5bbd246a750955ecbae3a",
          "md5": "60a41acbd0ec3ad55d88f9c55759e882"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT-sources.jar",
          "url": "engrave2-hingin-SNAPSHOT-sources.jar",
          "size": 117955,
          "sha512": "ebb135cd7dfaf93abb98ea5361074cdf76ce9f05fa2b70d73d60fd6fb725b857c0cfe295c9df279a4b0489d3f9f9bffda905b4a1313da87c26bf58a29a1b973a",
          "sha256": "727ce3b55b0ea4a801631a84cfedd81d0c0fdd92b674f0f306ded8c03695e650",
          "sha1": "f45c5e3d8f4bbb9fce786bddbdddad0c8df2abe0",
          "md5": "98161ec26916e66b24fad7e745506f2a"
        }
      ]
    }
  ]
}
