{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "engrave2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1685318,
          "sha512": "51ee9420616bccd873f156161b459e4851c708e43dafe7dc17a039e31058681cb9d88bf19846845615f565a98fa772cb3c4e4b94ab7e7ea2a3e26d9138bc4338",
          "sha256": "0c7956d0d9c72d29e39a512818f768b9e7d3b8cbb0440856098ff8a2a9de1be4",
          "sha1": "38955526c868357ef8951a1beb6f26289ebd7176",
          "md5": "f8654dce0f920c154fcf93a45fa603c4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1685318,
          "sha512": "51ee9420616bccd873f156161b459e4851c708e43dafe7dc17a039e31058681cb9d88bf19846845615f565a98fa772cb3c4e4b94ab7e7ea2a3e26d9138bc4338",
          "sha256": "0c7956d0d9c72d29e39a512818f768b9e7d3b8cbb0440856098ff8a2a9de1be4",
          "sha1": "38955526c868357ef8951a1beb6f26289ebd7176",
          "md5": "f8654dce0f920c154fcf93a45fa603c4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT-sources.jar",
          "url": "engrave2-hingin-SNAPSHOT-sources.jar",
          "size": 118669,
          "sha512": "6f7e317e7e966915e5e126570dfd87143c248df3e88364ec927c892c19a0980f16c108906c3ec970b05a2a47cba688c07e89800882af5e1c110532225332b478",
          "sha256": "4d129a8324b6aa908867383650176a1391ff8f06a2009a5ea7c669f5dca25f1c",
          "sha1": "ad7353d76b218284e3cf22c80e49771fd9e39dcd",
          "md5": "880d87a34cf6100adbf641a222e51ea2"
        }
      ]
    }
  ]
}
