{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "engrave2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1682679,
          "sha512": "fc4157102e13ff9f5756199342c746f996e46a22916ab42a53f85c09eeca97824c11919f13eae7cdd5f8b3451e5d7261f43c13886013fa48e3aacc92f67fe276",
          "sha256": "d375f339421449e7246d3954c2661485dfee25683a50ed33a338df89c8dbb026",
          "sha1": "7e2c036203d803d513cb7bb50837ea6a5a0f2c34",
          "md5": "6ba28ce28239943114b0d86a130017dd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1682679,
          "sha512": "fc4157102e13ff9f5756199342c746f996e46a22916ab42a53f85c09eeca97824c11919f13eae7cdd5f8b3451e5d7261f43c13886013fa48e3aacc92f67fe276",
          "sha256": "d375f339421449e7246d3954c2661485dfee25683a50ed33a338df89c8dbb026",
          "sha1": "7e2c036203d803d513cb7bb50837ea6a5a0f2c34",
          "md5": "6ba28ce28239943114b0d86a130017dd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT-sources.jar",
          "url": "engrave2-hingin-SNAPSHOT-sources.jar",
          "size": 118433,
          "sha512": "7337ec86aa41f1535efa44b4f2154456e043923204cbd26295cecf2b821fc55c456088596a66f78352316a9d45720604403846e4d314c9fe50c2fd58b544fc35",
          "sha256": "5bad73349da33ac2ef20692cf4f86e2d28aaa39dd33f2515a961d060f1f49b3b",
          "sha1": "301961bf0b12c72fa5be5aaf7b8fb445e1a7ad2f",
          "md5": "ef4bfa86d00528a4e5d6f1a6fcd6a328"
        }
      ]
    }
  ]
}
