{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "engrave2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1682390,
          "sha512": "eb183c04e1ed4f66072d9b963d36299776f52a2ed94b46d1a1e3916b5f4813165301ea92feb9b5b96e85282707cdb2e955c6939e83d80fec325c25b17baa845f",
          "sha256": "ac96265ea26886e16cdfa9a91ae1ad361873cc7de0a566a72409b50006b1f09d",
          "sha1": "c1bf5e7b261848996a06f849fc8e69b905842894",
          "md5": "f080d8c43774227d15c59b11026d4683"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1682390,
          "sha512": "eb183c04e1ed4f66072d9b963d36299776f52a2ed94b46d1a1e3916b5f4813165301ea92feb9b5b96e85282707cdb2e955c6939e83d80fec325c25b17baa845f",
          "sha256": "ac96265ea26886e16cdfa9a91ae1ad361873cc7de0a566a72409b50006b1f09d",
          "sha1": "c1bf5e7b261848996a06f849fc8e69b905842894",
          "md5": "f080d8c43774227d15c59b11026d4683"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT-sources.jar",
          "url": "engrave2-hingin-SNAPSHOT-sources.jar",
          "size": 118321,
          "sha512": "78fdafff1a85ae257b5f3151e575f2bbdaa684ea89c434ab32825b0bff3e2a14ac8ccc25fd77f4443bfd4eab7c3305c8c4447d7c5be94b9bd090594b3be10e04",
          "sha256": "dcc50b914b1b6dd4a11d3ec67842aaaac7b0f748ab8defb2edaa2d05b056c5fd",
          "sha1": "480623bb16dec5c613c893ff0dee8b8a2d9f80e2",
          "md5": "4c76d73f78a44c0cb85c75d825c51ad6"
        }
      ]
    }
  ]
}
