{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "engrave2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1684637,
          "sha512": "7e1ccd1fd1943e1d58c2c759e5b085fa61a94de5708cc931b6773fc23535c59ebaea0c08e218228ad202a0fc506d286f8e54faf81a6443d20ff5e08206bddaf8",
          "sha256": "140cfe8b9a8dff659d06d928fc706a9ae2b67320fd9fcb1176993f4ff3f12ef9",
          "sha1": "5ff1cfcad5da39291e20e0e11d412e0fc3f196f5",
          "md5": "84628789f8073b9bf28a7fabecd94bd9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1684637,
          "sha512": "7e1ccd1fd1943e1d58c2c759e5b085fa61a94de5708cc931b6773fc23535c59ebaea0c08e218228ad202a0fc506d286f8e54faf81a6443d20ff5e08206bddaf8",
          "sha256": "140cfe8b9a8dff659d06d928fc706a9ae2b67320fd9fcb1176993f4ff3f12ef9",
          "sha1": "5ff1cfcad5da39291e20e0e11d412e0fc3f196f5",
          "md5": "84628789f8073b9bf28a7fabecd94bd9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT-sources.jar",
          "url": "engrave2-hingin-SNAPSHOT-sources.jar",
          "size": 118583,
          "sha512": "1aff747860bb6f6e632cdacf77f246a13e0534d42056b9ca87264af70aa2a155021f907929ff8520c2a987d1ca7fdf29bc87cba204bf25669ebc69a15d07dc93",
          "sha256": "b0ba6b53f1246a3009e8a2c5e67e3ff44eaf67869d2cdbb88ba519a32f98eef6",
          "sha1": "4d61a1f237557c3db67330a6c7f395cefaa6bd3c",
          "md5": "5dce50b92152892ce048f6816c8d97d0"
        }
      ]
    }
  ]
}
