{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "engrave2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1683289,
          "sha512": "f9b29b096eb2f652fb6fbfc5d0780d14d5fe6e539779fd123c40c268f2c1159c95a77e9929c1330d1e351d725351df3a0104be16af4405c9fb675727094048f1",
          "sha256": "a3945426a81749ac40fb0b8ecf28ab4a3a306cc234098c42b0254157943fd2ce",
          "sha1": "2ffd74e580763fd76f598572107405e838b64d0f",
          "md5": "5231e4c99a709284b2242afbf52b846e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "lpDevice",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT.aar",
          "url": "engrave2-hingin-SNAPSHOT.aar",
          "size": 1683289,
          "sha512": "f9b29b096eb2f652fb6fbfc5d0780d14d5fe6e539779fd123c40c268f2c1159c95a77e9929c1330d1e351d725351df3a0104be16af4405c9fb675727094048f1",
          "sha256": "a3945426a81749ac40fb0b8ecf28ab4a3a306cc234098c42b0254157943fd2ce",
          "sha1": "2ffd74e580763fd76f598572107405e838b64d0f",
          "md5": "5231e4c99a709284b2242afbf52b846e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "engrave2-hingin-SNAPSHOT-sources.jar",
          "url": "engrave2-hingin-SNAPSHOT-sources.jar",
          "size": 118433,
          "sha512": "7337ec86aa41f1535efa44b4f2154456e043923204cbd26295cecf2b821fc55c456088596a66f78352316a9d45720604403846e4d314c9fe50c2fd58b544fc35",
          "sha256": "5bad73349da33ac2ef20692cf4f86e2d28aaa39dd33f2515a961d060f1f49b3b",
          "sha1": "301961bf0b12c72fa5be5aaf7b8fb445e1a7ad2f",
          "md5": "ef4bfa86d00528a4e5d6f1a6fcd6a328"
        }
      ]
    }
  ]
}
