{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "camerax",
    "version": "20250812",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation-ktx",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "camerax-20250812.aar",
          "url": "camerax-20250812.aar",
          "size": 212576,
          "sha512": "0cecf52a8925bfcde08b849e1508b3121565d91ff00ab1dab135dfaab448e69a8b2f1abc1200cfc6a4dea8ac79b663cd447cb5695ed81e4fbeba0eb23558ed70",
          "sha256": "2dc6defb5fb4bb5d00c29c9f6f04894d1dbad038e65207482e031f17dbe2f2a6",
          "sha1": "57d9b2aa992ac2ec5913de9a5dfdea97709e09c1",
          "md5": "91378bc1c4ee687579d9c143252a02ad"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "record",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation-ktx",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "camerax-20250812.aar",
          "url": "camerax-20250812.aar",
          "size": 212576,
          "sha512": "0cecf52a8925bfcde08b849e1508b3121565d91ff00ab1dab135dfaab448e69a8b2f1abc1200cfc6a4dea8ac79b663cd447cb5695ed81e4fbeba0eb23558ed70",
          "sha256": "2dc6defb5fb4bb5d00c29c9f6f04894d1dbad038e65207482e031f17dbe2f2a6",
          "sha1": "57d9b2aa992ac2ec5913de9a5dfdea97709e09c1",
          "md5": "91378bc1c4ee687579d9c143252a02ad"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "camerax-20250812-sources.jar",
          "url": "camerax-20250812-sources.jar",
          "size": 84011,
          "sha512": "d6b783173f12457e5ef4f4526913b3a03758c1e2bdade6385382233aa5d466c1173e6f9aa98ca47cc04e2aaeb83668f45f3d8332928a73a0b18917c577c858f2",
          "sha256": "8c3432fd13b1c55ca9f08f26126300116de2119d1c479ba8341bd441c07b9ed5",
          "sha1": "62688298d70e2f97595b5b8fa18d562fb6b8b774",
          "md5": "8fd96e06633ad6dd137957b7e7038111"
        }
      ]
    }
  ]
}
