{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "usbStorage",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "me.jahnen.libaums",
          "module": "core",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "usbStorage-hingin-SNAPSHOT.aar",
          "url": "usbStorage-hingin-SNAPSHOT.aar",
          "size": 129910,
          "sha512": "3cd8d8b7531ca2d0f46ee43c04c0723689c5632606d1fc0884a865806f8030d671a190b3415bca5982bdf0e03904bfb12c3d0e6d3b05b1304dbfbb0d9e2f8f58",
          "sha256": "fb59ef302a25a9f433f72c86c0eaed37e2982dac0b79997c0dc57f76390bcb3a",
          "sha1": "a948f628f43ea30eb915255faf53505945d44a94",
          "md5": "5b13e6d397172a721a7d8c341fd1dfb2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "me.jahnen.libaums",
          "module": "core",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "usbStorage-hingin-SNAPSHOT.aar",
          "url": "usbStorage-hingin-SNAPSHOT.aar",
          "size": 129910,
          "sha512": "3cd8d8b7531ca2d0f46ee43c04c0723689c5632606d1fc0884a865806f8030d671a190b3415bca5982bdf0e03904bfb12c3d0e6d3b05b1304dbfbb0d9e2f8f58",
          "sha256": "fb59ef302a25a9f433f72c86c0eaed37e2982dac0b79997c0dc57f76390bcb3a",
          "sha1": "a948f628f43ea30eb915255faf53505945d44a94",
          "md5": "5b13e6d397172a721a7d8c341fd1dfb2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "usbStorage-hingin-SNAPSHOT-sources.jar",
          "url": "usbStorage-hingin-SNAPSHOT-sources.jar",
          "size": 20701,
          "sha512": "2a86a06b639c8fe1c23b5829175405d4cc4afbc82aa44c8538837daa502197ed74fd3612a42202b88964a781e84c98dc15ffbc192696da560f537c178cd9cca5",
          "sha256": "0c9d3d5c657b59b104a996a0a393cb2240202c76e292b9bb982ed8b17857f143",
          "sha1": "62f317d3e9805bc832e2f8848a4d63e24fc3668b",
          "md5": "ffa0296cc5552bc1d3195530d98d742c"
        }
      ]
    }
  ]
}
