{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "usbStorage",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "me.jahnen.libaums",
          "module": "core",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "usbStorage-hingin-SNAPSHOT.aar",
          "url": "usbStorage-hingin-SNAPSHOT.aar",
          "size": 129891,
          "sha512": "60e3f889460511f6a26cc79f6539c11c749c3c7cbefb32ad1cbb755442044bf41e1124e1146e691fbb26f2ee6b138647d0f720064497931786c1c9118a7784a9",
          "sha256": "bbd8be4662151cab49192ae8a8daf503839ff13ebe7608fcbe2a0ce4772d4ccc",
          "sha1": "97a51a616a6fda9e8fe75179c79b911f31b3fe3d",
          "md5": "8d9146eab4b192f1d4f4864462471172"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "me.jahnen.libaums",
          "module": "core",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "usbStorage-hingin-SNAPSHOT.aar",
          "url": "usbStorage-hingin-SNAPSHOT.aar",
          "size": 129891,
          "sha512": "60e3f889460511f6a26cc79f6539c11c749c3c7cbefb32ad1cbb755442044bf41e1124e1146e691fbb26f2ee6b138647d0f720064497931786c1c9118a7784a9",
          "sha256": "bbd8be4662151cab49192ae8a8daf503839ff13ebe7608fcbe2a0ce4772d4ccc",
          "sha1": "97a51a616a6fda9e8fe75179c79b911f31b3fe3d",
          "md5": "8d9146eab4b192f1d4f4864462471172"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "usbStorage-hingin-SNAPSHOT-sources.jar",
          "url": "usbStorage-hingin-SNAPSHOT-sources.jar",
          "size": 20701,
          "sha512": "2a86a06b639c8fe1c23b5829175405d4cc4afbc82aa44c8538837daa502197ed74fd3612a42202b88964a781e84c98dc15ffbc192696da560f537c178cd9cca5",
          "sha256": "0c9d3d5c657b59b104a996a0a393cb2240202c76e292b9bb982ed8b17857f143",
          "sha1": "62f317d3e9805bc832e2f8848a4d63e24fc3668b",
          "md5": "ffa0296cc5552bc1d3195530d98d742c"
        }
      ]
    }
  ]
}
