{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "usbStorage",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "me.jahnen.libaums",
          "module": "core",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "usbStorage-hingin-SNAPSHOT.aar",
          "url": "usbStorage-hingin-SNAPSHOT.aar",
          "size": 129880,
          "sha512": "70c849bbc34903554ba8bc8e4a2676ab93a5e2faecf35eb0ff6be95dd031d3a1f4caf86f8d0204fb55ff7580f9984ebeb1101afb7e351f79d67db9febef296b9",
          "sha256": "444f2ebb413339d47aa6827d7740d7fbd2fc36a2d0e9744af7a84a67d14a5345",
          "sha1": "664da6dc7fcfedb9bb093ae0eee667815f08fc55",
          "md5": "8145379b81fffe2c5acc93caa6c9da81"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "me.jahnen.libaums",
          "module": "core",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "usbStorage-hingin-SNAPSHOT.aar",
          "url": "usbStorage-hingin-SNAPSHOT.aar",
          "size": 129880,
          "sha512": "70c849bbc34903554ba8bc8e4a2676ab93a5e2faecf35eb0ff6be95dd031d3a1f4caf86f8d0204fb55ff7580f9984ebeb1101afb7e351f79d67db9febef296b9",
          "sha256": "444f2ebb413339d47aa6827d7740d7fbd2fc36a2d0e9744af7a84a67d14a5345",
          "sha1": "664da6dc7fcfedb9bb093ae0eee667815f08fc55",
          "md5": "8145379b81fffe2c5acc93caa6c9da81"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "usbStorage-hingin-SNAPSHOT-sources.jar",
          "url": "usbStorage-hingin-SNAPSHOT-sources.jar",
          "size": 20701,
          "sha512": "2a86a06b639c8fe1c23b5829175405d4cc4afbc82aa44c8538837daa502197ed74fd3612a42202b88964a781e84c98dc15ffbc192696da560f537c178cd9cca5",
          "sha256": "0c9d3d5c657b59b104a996a0a393cb2240202c76e292b9bb982ed8b17857f143",
          "sha1": "62f317d3e9805bc832e2f8848a4d63e24fc3668b",
          "md5": "ffa0296cc5552bc1d3195530d98d742c"
        }
      ]
    }
  ]
}
