{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "bluetooth",
    "version": "20250812",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.Jasonchenlijian",
          "module": "FastBle",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "bluetooth-20250812.aar",
          "url": "bluetooth-20250812.aar",
          "size": 71608,
          "sha512": "79c0d60c09e181678f41c4d7d4c6e0b32191fd5f721b231ff0a2ee546fbc0b040806c98564c25df581596102b7304362b26941521e20a5cf17046990eb814ed7",
          "sha256": "c9810c875d04516f1135ea82023f133e8e6239b361d2eb4520860eee974fb025",
          "sha1": "04c453c854cc444fdacebe87f08c3ee44c2383ad",
          "md5": "cd042a3069a3a60475739c16b71218f3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.github.Jasonchenlijian",
          "module": "FastBle",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "bluetooth-20250812.aar",
          "url": "bluetooth-20250812.aar",
          "size": 71608,
          "sha512": "79c0d60c09e181678f41c4d7d4c6e0b32191fd5f721b231ff0a2ee546fbc0b040806c98564c25df581596102b7304362b26941521e20a5cf17046990eb814ed7",
          "sha256": "c9810c875d04516f1135ea82023f133e8e6239b361d2eb4520860eee974fb025",
          "sha1": "04c453c854cc444fdacebe87f08c3ee44c2383ad",
          "md5": "cd042a3069a3a60475739c16b71218f3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bluetooth-20250812-sources.jar",
          "url": "bluetooth-20250812-sources.jar",
          "size": 12401,
          "sha512": "60005aa61e677f302be20be6a606bbb4a6e3d16c2602ac858b560e82f0321b39915f244e28c3a6b896bbe1883e6fc55b8a552d84abeb2e88c7821e211d0a3f9d",
          "sha256": "31b9e36fcc0660679359fa0f65002cac09085d636d5e3748c8512497260d2ee3",
          "sha1": "5adc74d476b0e4246841ed5bd8e90bd91f8e3009",
          "md5": "23e7fbfc88471033bdd04f4438a0bcd1"
        }
      ]
    }
  ]
}
