{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "download",
    "version": "20250812",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.liulishuo.okdownload",
          "module": "okdownload",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "ktx",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "download-20250812.aar",
          "url": "download-20250812.aar",
          "size": 286085,
          "sha512": "a4fa0d4a65164eb19c0d881b1d7e87e01c01af6869c29f0fbf69c3f3e200b06ee9780c879d34bc692d88e7fedab1eff9299aa887bbe6b9f3b24bf6f4d8ebc0bb",
          "sha256": "b627daa77bdc07b21d240792b2f0fa736c03937be780caf56a5000d2a74a9229",
          "sha1": "ea2b7a40ce8938f6a6d4489668e2bee72e400317",
          "md5": "c875586feaef7ffff1eba0c754005af9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "sqlite",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "okhttp",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "okdownload",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "ktx",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "download-20250812.aar",
          "url": "download-20250812.aar",
          "size": 286085,
          "sha512": "a4fa0d4a65164eb19c0d881b1d7e87e01c01af6869c29f0fbf69c3f3e200b06ee9780c879d34bc692d88e7fedab1eff9299aa887bbe6b9f3b24bf6f4d8ebc0bb",
          "sha256": "b627daa77bdc07b21d240792b2f0fa736c03937be780caf56a5000d2a74a9229",
          "sha1": "ea2b7a40ce8938f6a6d4489668e2bee72e400317",
          "md5": "c875586feaef7ffff1eba0c754005af9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "download-20250812-sources.jar",
          "url": "download-20250812-sources.jar",
          "size": 42233,
          "sha512": "5616ea7840e726b01ee1b9432791483e06e5f2ecc208316af4dfeb2f44204ab81bfe782d087d4a4a40aca0a916fe4d8348945220635b2a3fd9704a9ad0e9f0c1",
          "sha256": "72c7d9e7255c0a64b973169f9375b60597b1a55ea06f4a17f75f14831fadd702",
          "sha1": "231480125a29a35efac0c8a3d31a2efbc997bdb8",
          "md5": "f8f5720b470bcf36b38dfcaa55128b2d"
        }
      ]
    }
  ]
}
