{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "camerax",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation-ktx",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "camerax-master-SNAPSHOT.aar",
          "url": "camerax-master-SNAPSHOT.aar",
          "size": 212529,
          "sha512": "3743d9cc24d0dfa76df6a432708af6ff846df7e71562c431f363e0950fd9c077c79255a2b9f091c85f02510c8f5f493c50d0f6e2b1e11df823072792af998811",
          "sha256": "a74c06630edfe4aad7a6d4bf7edc7736ed421826cf097a758722a31f3d2ce352",
          "sha1": "da2cc7e60103ccd85c47ce4df4be084fe52aae60",
          "md5": "4fad2d920fdd9314d2dce388c2147b55"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "record",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation-ktx",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "camerax-master-SNAPSHOT.aar",
          "url": "camerax-master-SNAPSHOT.aar",
          "size": 212529,
          "sha512": "3743d9cc24d0dfa76df6a432708af6ff846df7e71562c431f363e0950fd9c077c79255a2b9f091c85f02510c8f5f493c50d0f6e2b1e11df823072792af998811",
          "sha256": "a74c06630edfe4aad7a6d4bf7edc7736ed421826cf097a758722a31f3d2ce352",
          "sha1": "da2cc7e60103ccd85c47ce4df4be084fe52aae60",
          "md5": "4fad2d920fdd9314d2dce388c2147b55"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "camerax-master-SNAPSHOT-sources.jar",
          "url": "camerax-master-SNAPSHOT-sources.jar",
          "size": 84011,
          "sha512": "d6b783173f12457e5ef4f4526913b3a03758c1e2bdade6385382233aa5d466c1173e6f9aa98ca47cc04e2aaeb83668f45f3d8332928a73a0b18917c577c858f2",
          "sha256": "8c3432fd13b1c55ca9f08f26126300116de2119d1c479ba8341bd441c07b9ed5",
          "sha1": "62688298d70e2f97595b5b8fa18d562fb6b8b774",
          "md5": "8fd96e06633ad6dd137957b7e7038111"
        }
      ]
    }
  ]
}
