{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "guard",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "guard-master-SNAPSHOT.aar",
          "url": "guard-master-SNAPSHOT.aar",
          "size": 19750,
          "sha512": "0ea35eb372b7c8422532be22db18d2d5c72156c64c44cce34227cae60c00113e52d31681c31e1a541b6d15376877492b9e96f769d11aa45292ebf858d23defcc",
          "sha256": "d26816fc815b99215f4e30e3e51f5722056d8e66d021e883c30d6dd6e0f1a95a",
          "sha1": "5d15929b60000045ac0cafd3a1759a3b9fe4e4c2",
          "md5": "2c12f23c824beaf2fc7aca5ca7f9a3fd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "guard-master-SNAPSHOT.aar",
          "url": "guard-master-SNAPSHOT.aar",
          "size": 19750,
          "sha512": "0ea35eb372b7c8422532be22db18d2d5c72156c64c44cce34227cae60c00113e52d31681c31e1a541b6d15376877492b9e96f769d11aa45292ebf858d23defcc",
          "sha256": "d26816fc815b99215f4e30e3e51f5722056d8e66d021e883c30d6dd6e0f1a95a",
          "sha1": "5d15929b60000045ac0cafd3a1759a3b9fe4e4c2",
          "md5": "2c12f23c824beaf2fc7aca5ca7f9a3fd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "guard-master-SNAPSHOT-sources.jar",
          "url": "guard-master-SNAPSHOT-sources.jar",
          "size": 2247,
          "sha512": "c860958479a51653858def7cf6939172d870d293e9f69cf01604987dd458dd83d6897519c8c359f26c0624504f93f50c140a1b3ef4a107666cf46eea4c170cb5",
          "sha256": "50ce61e94f445bbc0a3d88e8675b871c77b6dcff5cff47c1c33489e1f9cf4cc9",
          "sha1": "e90360ab0d78f79c2850879d7a5b34f9693f6590",
          "md5": "774a760a2d78742d84829fb0aa5c8e62"
        }
      ]
    }
  ]
}
