{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "pager",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "pager-hingin-SNAPSHOT.aar",
          "url": "pager-hingin-SNAPSHOT.aar",
          "size": 113526,
          "sha512": "3c054102e2da3b02e478e8073d507711ebab9f950a7e944447c12d014ef2a18bc196d68fedaa44ee8139e51ace8da5c780acf0f0866a94f449c423a0c2355bfa",
          "sha256": "bb663fc93c76359d2852b3cac055e712acab7359c73c20e4dc3a12df9f8516a3",
          "sha1": "89ae0d3cceb81e42a65c7ce445ba1d1b5b5123a8",
          "md5": "cb9a9818bc260b3284e28cc4744d017d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "transition",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "pager-hingin-SNAPSHOT.aar",
          "url": "pager-hingin-SNAPSHOT.aar",
          "size": 113526,
          "sha512": "3c054102e2da3b02e478e8073d507711ebab9f950a7e944447c12d014ef2a18bc196d68fedaa44ee8139e51ace8da5c780acf0f0866a94f449c423a0c2355bfa",
          "sha256": "bb663fc93c76359d2852b3cac055e712acab7359c73c20e4dc3a12df9f8516a3",
          "sha1": "89ae0d3cceb81e42a65c7ce445ba1d1b5b5123a8",
          "md5": "cb9a9818bc260b3284e28cc4744d017d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pager-hingin-SNAPSHOT-sources.jar",
          "url": "pager-hingin-SNAPSHOT-sources.jar",
          "size": 27195,
          "sha512": "a5a2d3bd1ba900d128f312d5af184e71e6dc3f24217bf26ee423dd4637171aec3e3fb5113296fa0204db2a04d746aa599d73f7b3079da5b7c4f574111e10470b",
          "sha256": "7557d320da7cc7a008012fa80ffdfa0ea0cdb8d98713ca9713a7c977c253432e",
          "sha1": "837d901b476a1b5ed98001bd360fddbc4c84dfc3",
          "md5": "0aad62dded835d90ac484580ddc6bbc2"
        }
      ]
    }
  ]
}
