{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "glide",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "glide-hingin-SNAPSHOT.aar",
          "url": "glide-hingin-SNAPSHOT.aar",
          "size": 113151,
          "sha512": "ee46ec46ccb099553baaf12c7f8d370f737ac2c244bf669762026ca047ae42189ab0b5135b97df88ebc7c41f3e12a4b8c6268c665dbfe0f5ad8711048aa0a32f",
          "sha256": "c2a4feef26ee4611cdf644ad21b595278825d60978e4504c8b8638a205ee53e4",
          "sha1": "3eb9015f0be4324d07be0345349d1f3e2eb08f83",
          "md5": "9652055fa25ad31441c1b53d2af74497"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "glide-hingin-SNAPSHOT.aar",
          "url": "glide-hingin-SNAPSHOT.aar",
          "size": 113151,
          "sha512": "ee46ec46ccb099553baaf12c7f8d370f737ac2c244bf669762026ca047ae42189ab0b5135b97df88ebc7c41f3e12a4b8c6268c665dbfe0f5ad8711048aa0a32f",
          "sha256": "c2a4feef26ee4611cdf644ad21b595278825d60978e4504c8b8638a205ee53e4",
          "sha1": "3eb9015f0be4324d07be0345349d1f3e2eb08f83",
          "md5": "9652055fa25ad31441c1b53d2af74497"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "glide-hingin-SNAPSHOT-sources.jar",
          "url": "glide-hingin-SNAPSHOT-sources.jar",
          "size": 35125,
          "sha512": "561c084a971b41dd243355a3b89aa8277c056821481672dd6e7c3b9c63c13962435dd2da2eb2e0e7b12f1107b4211f812ecda6650094e2ca33394cdf3d4744b9",
          "sha256": "9771dd607e531f2f202effcf1972ec1e7f1cc7020a2525a6a01600fd07580973",
          "sha1": "7686197336ed922e9958b5fa82477200cecb44b9",
          "md5": "f6da959d53d02534f3f37ae704016be2"
        }
      ]
    }
  ]
}
