{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "glide",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "glide-hingin-SNAPSHOT.aar",
          "url": "glide-hingin-SNAPSHOT.aar",
          "size": 113140,
          "sha512": "473883716f589fa0fda9d7707e1343a699438452b06273efcd84611efbe24d61dd70fb4f91c470f5bb98f514bea9d30422f1fa34742b9a83dd5b0fa91f367e81",
          "sha256": "bebde47db6042b592dade88b9092ac5d09a32fa7ab83cd4160fdf3c8cd258fcc",
          "sha1": "e24c71791e7c95774d110dadd2ee224e4ac4919a",
          "md5": "c3a619864b3ea3899614d461ac478d4e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "glide-hingin-SNAPSHOT.aar",
          "url": "glide-hingin-SNAPSHOT.aar",
          "size": 113140,
          "sha512": "473883716f589fa0fda9d7707e1343a699438452b06273efcd84611efbe24d61dd70fb4f91c470f5bb98f514bea9d30422f1fa34742b9a83dd5b0fa91f367e81",
          "sha256": "bebde47db6042b592dade88b9092ac5d09a32fa7ab83cd4160fdf3c8cd258fcc",
          "sha1": "e24c71791e7c95774d110dadd2ee224e4ac4919a",
          "md5": "c3a619864b3ea3899614d461ac478d4e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "glide-hingin-SNAPSHOT-sources.jar",
          "url": "glide-hingin-SNAPSHOT-sources.jar",
          "size": 35125,
          "sha512": "561c084a971b41dd243355a3b89aa8277c056821481672dd6e7c3b9c63c13962435dd2da2eb2e0e7b12f1107b4211f812ecda6650094e2ca33394cdf3d4744b9",
          "sha256": "9771dd607e531f2f202effcf1972ec1e7f1cc7020a2525a6a01600fd07580973",
          "sha1": "7686197336ed922e9958b5fa82477200cecb44b9",
          "md5": "f6da959d53d02534f3f37ae704016be2"
        }
      ]
    }
  ]
}
