{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "jxl",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "net.sourceforge.jexcelapi",
          "module": "jxl",
          "version": {
            "requires": "2.6.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "jxl-hingin-SNAPSHOT.aar",
          "url": "jxl-hingin-SNAPSHOT.aar",
          "size": 19297,
          "sha512": "db36e8f73c215c12da58c2d47b38165c226d456d230b5d5679f88ce383d9a32b40c19e61da6e53714f522ea94e254514cafc0266fe90a0214e1001757bbc3363",
          "sha256": "25e76636e859f6db12cd119e3734c596cce2301bd80f8e07d7e31f63d20acc33",
          "sha1": "da5a8fb228b6d4d9e509f42819e0cc8f8c7beff0",
          "md5": "9ebaa04424ebab613a0e0feaca350063"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "net.sourceforge.jexcelapi",
          "module": "jxl",
          "version": {
            "requires": "2.6.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "jxl-hingin-SNAPSHOT.aar",
          "url": "jxl-hingin-SNAPSHOT.aar",
          "size": 19297,
          "sha512": "db36e8f73c215c12da58c2d47b38165c226d456d230b5d5679f88ce383d9a32b40c19e61da6e53714f522ea94e254514cafc0266fe90a0214e1001757bbc3363",
          "sha256": "25e76636e859f6db12cd119e3734c596cce2301bd80f8e07d7e31f63d20acc33",
          "sha1": "da5a8fb228b6d4d9e509f42819e0cc8f8c7beff0",
          "md5": "9ebaa04424ebab613a0e0feaca350063"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "jxl-hingin-SNAPSHOT-sources.jar",
          "url": "jxl-hingin-SNAPSHOT-sources.jar",
          "size": 3259,
          "sha512": "32c210de743124bb21eb3caff3b824b98a7a03f54c58ae639852be275830c6f389b61550b5e9a998a0b5360f4dc736a4e93d2e06d27a25157276b88e87a9c59c",
          "sha256": "a731507fc0c4ca6196c23848304ca40819c22c9a71cc90701c4b9ffb2c8bce98",
          "sha1": "794e80d6db4514901b0dabbb51d8f0b0e2371967",
          "md5": "dc6fc518ac7da7345ca65f58ccd40651"
        }
      ]
    }
  ]
}
