{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "dialog2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.WaytoInc",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.0.10"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "CalendarView",
          "version": {
            "requires": "3.7.1.42"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "ColorPicker",
          "version": {
            "requires": "1.1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "dialog2-hingin-SNAPSHOT.aar",
          "url": "dialog2-hingin-SNAPSHOT.aar",
          "size": 212225,
          "sha512": "7300541460baf4634e59053bcbd8cd5edf73957f051a6dd06605823fc7c54242f0a1e4ace2afa72340fac1b8b16537d8fde679c2469dc6eb2d7530c698ca1b69",
          "sha256": "f6dd9f23884b38faec689afd2490965362f1d4f40a8ffb48916bb708e68af743",
          "sha1": "741cf139780b1a81198b6fa51eea6656c793c233",
          "md5": "c9564913610096b5a6bc3c1305af2457"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.WaytoInc",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.0.10"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "CalendarView",
          "version": {
            "requires": "3.7.1.42"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "ColorPicker",
          "version": {
            "requires": "1.1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "dialog2-hingin-SNAPSHOT.aar",
          "url": "dialog2-hingin-SNAPSHOT.aar",
          "size": 212225,
          "sha512": "7300541460baf4634e59053bcbd8cd5edf73957f051a6dd06605823fc7c54242f0a1e4ace2afa72340fac1b8b16537d8fde679c2469dc6eb2d7530c698ca1b69",
          "sha256": "f6dd9f23884b38faec689afd2490965362f1d4f40a8ffb48916bb708e68af743",
          "sha1": "741cf139780b1a81198b6fa51eea6656c793c233",
          "md5": "c9564913610096b5a6bc3c1305af2457"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dialog2-hingin-SNAPSHOT-sources.jar",
          "url": "dialog2-hingin-SNAPSHOT-sources.jar",
          "size": 71919,
          "sha512": "67bb4b928ce69cd96e4382342e217ffe1ec05fdedcfd87c9700846468182f9bb5fb351fd5ef0eca4e6af038856a94690399c3027fef2d1ec07d70610b72120be",
          "sha256": "41ed39d29f3c64b12a9cbe75e0c3fb6e4d34b274cca985a23b7e077b0b1d790a",
          "sha1": "2a307a8398ae7240b50c5325aca6d77c908e9dfe",
          "md5": "d876c5706b072d396e23c0d5b9d4b23a"
        }
      ]
    }
  ]
}
