{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "dialog2",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.WaytoInc",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.0.10"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "CalendarView",
          "version": {
            "requires": "3.7.1.42"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "ColorPicker",
          "version": {
            "requires": "1.1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "dialog2-hingin-SNAPSHOT.aar",
          "url": "dialog2-hingin-SNAPSHOT.aar",
          "size": 212258,
          "sha512": "b9ac8a4967fab8443c9f40cbb6c44325e74dd1845c115763fe916dd3656ec2358e6a5693969a207aa0ec391c74c572317b6fd28bfa5444a7e68d247fc9b009bf",
          "sha256": "c540ee009cce2185e89198a8c6c0e347732350e687b052c8a6c905333587112d",
          "sha1": "48d1187ff858efd7cd82481615d9f1975aad90f1",
          "md5": "dc8b4d4c8ce15e47d71c375eb5a8e68e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.WaytoInc",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.0.10"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "CalendarView",
          "version": {
            "requires": "3.7.1.42"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "ColorPicker",
          "version": {
            "requires": "1.1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "dialog2-hingin-SNAPSHOT.aar",
          "url": "dialog2-hingin-SNAPSHOT.aar",
          "size": 212258,
          "sha512": "b9ac8a4967fab8443c9f40cbb6c44325e74dd1845c115763fe916dd3656ec2358e6a5693969a207aa0ec391c74c572317b6fd28bfa5444a7e68d247fc9b009bf",
          "sha256": "c540ee009cce2185e89198a8c6c0e347732350e687b052c8a6c905333587112d",
          "sha1": "48d1187ff858efd7cd82481615d9f1975aad90f1",
          "md5": "dc8b4d4c8ce15e47d71c375eb5a8e68e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dialog2-hingin-SNAPSHOT-sources.jar",
          "url": "dialog2-hingin-SNAPSHOT-sources.jar",
          "size": 71919,
          "sha512": "67bb4b928ce69cd96e4382342e217ffe1ec05fdedcfd87c9700846468182f9bb5fb351fd5ef0eca4e6af038856a94690399c3027fef2d1ec07d70610b72120be",
          "sha256": "41ed39d29f3c64b12a9cbe75e0c3fb6e4d34b274cca985a23b7e077b0b1d790a",
          "sha1": "2a307a8398ae7240b50c5325aca6d77c908e9dfe",
          "md5": "d876c5706b072d396e23c0d5b9d4b23a"
        }
      ]
    }
  ]
}
