{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "github",
    "version": "20250812",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bus",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "ViewPagerLayoutManager",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.github.XHGInc",
          "module": "FloatWindow",
          "version": {
            "requires": "1.0.9.5"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "ColorPicker",
          "version": {
            "requires": "1.1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "github-20250812.aar",
          "url": "github-20250812.aar",
          "size": 151178,
          "sha512": "08b2a4141f472a3138d426406ce56a0d5e69861a018f253dd7cd103d9c2085e6831cd995c819633985b66662af54b8bdf07c8e2eedebcb2e30f2b305b1d35d4c",
          "sha256": "95d6edd2c84409590893f96bb1da4529a383da3d54f5ba80b1b216db85380dd4",
          "sha1": "db7454d1290b906c6a24c380bbec32b19e9ea8d2",
          "md5": "7a58671b7f71631aa68a6a50b061d5a8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bus",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "ViewPagerLayoutManager",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.github.XHGInc",
          "module": "FloatWindow",
          "version": {
            "requires": "1.0.9.5"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.angcyo",
          "module": "ColorPicker",
          "version": {
            "requires": "1.1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "github-20250812.aar",
          "url": "github-20250812.aar",
          "size": 151178,
          "sha512": "08b2a4141f472a3138d426406ce56a0d5e69861a018f253dd7cd103d9c2085e6831cd995c819633985b66662af54b8bdf07c8e2eedebcb2e30f2b305b1d35d4c",
          "sha256": "95d6edd2c84409590893f96bb1da4529a383da3d54f5ba80b1b216db85380dd4",
          "sha1": "db7454d1290b906c6a24c380bbec32b19e9ea8d2",
          "md5": "7a58671b7f71631aa68a6a50b061d5a8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "github-20250812-sources.jar",
          "url": "github-20250812-sources.jar",
          "size": 76343,
          "sha512": "bc2334937b95328adc7d4a87c42d47b7a8e6ec7254e2496625c2f0ce0f4227a3e24daadacecde954ed67dd999845d6d198bfb4a1eb58a7942e51374fd2d55458",
          "sha256": "dfcb8cda8c9b0661f46a54bcdf692ee6867cc7aca7b313ba4e691a84a9e80793",
          "sha1": "3be5d61251853d37bf192e7a8f4957f1b93e8fb6",
          "md5": "3b1c9248a20d22bd48bf7b337048b45c"
        }
      ]
    }
  ]
}
