{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "QuickJS",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.taoweiji.quickjs",
          "module": "quickjs-android",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT.aar",
          "url": "QuickJS-hingin-SNAPSHOT.aar",
          "size": 120335,
          "sha512": "02bf194178cdbf227cfc6a971a1918b24dc2a6d3cb2a8d815376b6f54451a7068e551494d41bf6083818ed99855effe99d3f0a01411481615ab999cbe1993a83",
          "sha256": "5f4dd0162c8da0fa47d78aee9ade82ac97fddcb9a44f4acafeb62de55b0e8f41",
          "sha1": "9c094660719fb977f42d84a17df7866ca388b041",
          "md5": "51ff2a4597ff21d1f5f61c6cb4775bba"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "io.github.taoweiji.quickjs",
          "module": "quickjs-android",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT.aar",
          "url": "QuickJS-hingin-SNAPSHOT.aar",
          "size": 120335,
          "sha512": "02bf194178cdbf227cfc6a971a1918b24dc2a6d3cb2a8d815376b6f54451a7068e551494d41bf6083818ed99855effe99d3f0a01411481615ab999cbe1993a83",
          "sha256": "5f4dd0162c8da0fa47d78aee9ade82ac97fddcb9a44f4acafeb62de55b0e8f41",
          "sha1": "9c094660719fb977f42d84a17df7866ca388b041",
          "md5": "51ff2a4597ff21d1f5f61c6cb4775bba"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT-sources.jar",
          "url": "QuickJS-hingin-SNAPSHOT-sources.jar",
          "size": 40833,
          "sha512": "c8db1422a4d56ec323fed6b03c02bd1d56b15ce091c3f5a8a2aae5e3c5b229e887b0e2ae3e8bbbc84b9f9f53e7bf15ce3c223240b9ed76f4a24dff653d3fa4ee",
          "sha256": "c76f05aa7390317f9f7f956894929cf550457cd5608e8c3a68703dbd1a782f07",
          "sha1": "0f19bc3518c8095255f3a086572f649c2f445b43",
          "md5": "17e8a6b11b94aee8a9676955c27a5660"
        }
      ]
    }
  ]
}
