{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "QuickJS",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.taoweiji.quickjs",
          "module": "quickjs-android",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT.aar",
          "url": "QuickJS-hingin-SNAPSHOT.aar",
          "size": 120282,
          "sha512": "ea424c78c7a03d4331b80b8bde1dcd2bcdf1fa35c1d1904b0da0f2974134496751c717b7c757fa40b69956d709e511a0e3f5996be9169767f0310ea476350f7f",
          "sha256": "78b8c7162db5998ee1afb8d4a7586681d03064f952fa077d3149678071a9f14f",
          "sha1": "276b0efa364c018baf4095a389a5a556e47c1882",
          "md5": "44fc1e8c20c36ed5c004ed6fc1342d77"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "io.github.taoweiji.quickjs",
          "module": "quickjs-android",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT.aar",
          "url": "QuickJS-hingin-SNAPSHOT.aar",
          "size": 120282,
          "sha512": "ea424c78c7a03d4331b80b8bde1dcd2bcdf1fa35c1d1904b0da0f2974134496751c717b7c757fa40b69956d709e511a0e3f5996be9169767f0310ea476350f7f",
          "sha256": "78b8c7162db5998ee1afb8d4a7586681d03064f952fa077d3149678071a9f14f",
          "sha1": "276b0efa364c018baf4095a389a5a556e47c1882",
          "md5": "44fc1e8c20c36ed5c004ed6fc1342d77"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT-sources.jar",
          "url": "QuickJS-hingin-SNAPSHOT-sources.jar",
          "size": 40833,
          "sha512": "c8db1422a4d56ec323fed6b03c02bd1d56b15ce091c3f5a8a2aae5e3c5b229e887b0e2ae3e8bbbc84b9f9f53e7bf15ce3c223240b9ed76f4a24dff653d3fa4ee",
          "sha256": "c76f05aa7390317f9f7f956894929cf550457cd5608e8c3a68703dbd1a782f07",
          "sha1": "0f19bc3518c8095255f3a086572f649c2f445b43",
          "md5": "17e8a6b11b94aee8a9676955c27a5660"
        }
      ]
    }
  ]
}
