{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "QuickJS",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.taoweiji.quickjs",
          "module": "quickjs-android",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT.aar",
          "url": "QuickJS-hingin-SNAPSHOT.aar",
          "size": 120423,
          "sha512": "b546af316c3f053b1d5857c7b9f050a33ed4cd84400c71ecea321e1563c5a4f97f3da87f3630a2423a2a0761184a2a4b7fa490f268e3b7f004790f62253dc6de",
          "sha256": "a124f6795b010080ce5116c0ad711fd5b262460a0e08d7eeff0662a242cdd35b",
          "sha1": "709d49326c0afde14584d1146a27ed9123d13e9b",
          "md5": "12b09a1d7afc8ea49e818a4e0115f56e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "io.github.taoweiji.quickjs",
          "module": "quickjs-android",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT.aar",
          "url": "QuickJS-hingin-SNAPSHOT.aar",
          "size": 120423,
          "sha512": "b546af316c3f053b1d5857c7b9f050a33ed4cd84400c71ecea321e1563c5a4f97f3da87f3630a2423a2a0761184a2a4b7fa490f268e3b7f004790f62253dc6de",
          "sha256": "a124f6795b010080ce5116c0ad711fd5b262460a0e08d7eeff0662a242cdd35b",
          "sha1": "709d49326c0afde14584d1146a27ed9123d13e9b",
          "md5": "12b09a1d7afc8ea49e818a4e0115f56e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT-sources.jar",
          "url": "QuickJS-hingin-SNAPSHOT-sources.jar",
          "size": 40833,
          "sha512": "c8db1422a4d56ec323fed6b03c02bd1d56b15ce091c3f5a8a2aae5e3c5b229e887b0e2ae3e8bbbc84b9f9f53e7bf15ce3c223240b9ed76f4a24dff653d3fa4ee",
          "sha256": "c76f05aa7390317f9f7f956894929cf550457cd5608e8c3a68703dbd1a782f07",
          "sha1": "0f19bc3518c8095255f3a086572f649c2f445b43",
          "md5": "17e8a6b11b94aee8a9676955c27a5660"
        }
      ]
    }
  ]
}
