{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "QuickJS",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.taoweiji.quickjs",
          "module": "quickjs-android",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT.aar",
          "url": "QuickJS-hingin-SNAPSHOT.aar",
          "size": 120455,
          "sha512": "9128f10a0e4a02825978e7ad219a04122a66c3f854d98fff242a16739521dbffe3b9cb9980486176a042807f489c141160a7f0f989984a652633249aa9dda0da",
          "sha256": "18aa190032ef9702b14a47c3856ac7c1dd78232aca8596b02c85793c79928cb2",
          "sha1": "8f8b4c7aea2afad7b12355f29c32d088692533e3",
          "md5": "8f8357fc672436947952a8e9c204cf6c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "io.github.taoweiji.quickjs",
          "module": "quickjs-android",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT.aar",
          "url": "QuickJS-hingin-SNAPSHOT.aar",
          "size": 120455,
          "sha512": "9128f10a0e4a02825978e7ad219a04122a66c3f854d98fff242a16739521dbffe3b9cb9980486176a042807f489c141160a7f0f989984a652633249aa9dda0da",
          "sha256": "18aa190032ef9702b14a47c3856ac7c1dd78232aca8596b02c85793c79928cb2",
          "sha1": "8f8b4c7aea2afad7b12355f29c32d088692533e3",
          "md5": "8f8357fc672436947952a8e9c204cf6c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "QuickJS-hingin-SNAPSHOT-sources.jar",
          "url": "QuickJS-hingin-SNAPSHOT-sources.jar",
          "size": 40833,
          "sha512": "c8db1422a4d56ec323fed6b03c02bd1d56b15ce091c3f5a8a2aae5e3c5b229e887b0e2ae3e8bbbc84b9f9f53e7bf15ce3c223240b9ed76f4a24dff653d3fa4ee",
          "sha256": "c76f05aa7390317f9f7f956894929cf550457cd5608e8c3a68703dbd1a782f07",
          "sha1": "0f19bc3518c8095255f3a086572f649c2f445b43",
          "md5": "17e8a6b11b94aee8a9676955c27a5660"
        }
      ]
    }
  ]
}
