{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "work",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "work-hingin-SNAPSHOT.aar",
          "url": "work-hingin-SNAPSHOT.aar",
          "size": 22570,
          "sha512": "d6116e73ae223f55f2362af1de579067279ee747a77ce44ede86f4af4c6a3d2f6ee74899b897d014a132a69f84ee82210f92ae3e1d41295338eef490c2a13a6f",
          "sha256": "fa41e9ff8011ff200fe7c18f7b610a1ed27630e8460324cd2cb28f161abcf4e0",
          "sha1": "0bcef11e14ed7219cb2ea8988a55509ba17e1cd6",
          "md5": "1d852252aedd3ed3ddf219eafa8eea7d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "work-hingin-SNAPSHOT.aar",
          "url": "work-hingin-SNAPSHOT.aar",
          "size": 22570,
          "sha512": "d6116e73ae223f55f2362af1de579067279ee747a77ce44ede86f4af4c6a3d2f6ee74899b897d014a132a69f84ee82210f92ae3e1d41295338eef490c2a13a6f",
          "sha256": "fa41e9ff8011ff200fe7c18f7b610a1ed27630e8460324cd2cb28f161abcf4e0",
          "sha1": "0bcef11e14ed7219cb2ea8988a55509ba17e1cd6",
          "md5": "1d852252aedd3ed3ddf219eafa8eea7d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "work-hingin-SNAPSHOT-sources.jar",
          "url": "work-hingin-SNAPSHOT-sources.jar",
          "size": 6315,
          "sha512": "20c13290fd4d29f330a4771220de52f29f2cef04625dc0399e3dfe307b0b6d7b0f4882d05e336c3803dbc00d1fe423c71567d0c896e4d837c85f8199ba5af7b0",
          "sha256": "9cc7a109731e5acb7f86abe2da8f7c4dddaff3b4e27c87c05b15a69eabbaa2b9",
          "sha1": "66749bbb8beef15178fb24732d622eebec97416c",
          "md5": "e50ab8e607f822eb3d50bc9eadb65a9e"
        }
      ]
    }
  ]
}
