{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "download",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.liulishuo.okdownload",
          "module": "okdownload",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "ktx",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "download-hingin-SNAPSHOT.aar",
          "url": "download-hingin-SNAPSHOT.aar",
          "size": 286056,
          "sha512": "8f72c537f83c2f7ee3c0bb0d734fce0b5402ff6bec771200272d2e4211968dc4b112ebc2f4373ffffe731ec649c7b10659d76fbf41d9f5a2cf86fb5e5e29d3d5",
          "sha256": "699cf82c98c0fa000c842d65e7ddc5697f64e63a1f2d247135dc9381aa3d42d1",
          "sha1": "ffa4718bfc44851063d0e1f5d2d28f24afa09697",
          "md5": "c3230d901c747aa53d2464c204550613"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "sqlite",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "okhttp",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "okdownload",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "ktx",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "download-hingin-SNAPSHOT.aar",
          "url": "download-hingin-SNAPSHOT.aar",
          "size": 286056,
          "sha512": "8f72c537f83c2f7ee3c0bb0d734fce0b5402ff6bec771200272d2e4211968dc4b112ebc2f4373ffffe731ec649c7b10659d76fbf41d9f5a2cf86fb5e5e29d3d5",
          "sha256": "699cf82c98c0fa000c842d65e7ddc5697f64e63a1f2d247135dc9381aa3d42d1",
          "sha1": "ffa4718bfc44851063d0e1f5d2d28f24afa09697",
          "md5": "c3230d901c747aa53d2464c204550613"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "download-hingin-SNAPSHOT-sources.jar",
          "url": "download-hingin-SNAPSHOT-sources.jar",
          "size": 42233,
          "sha512": "5616ea7840e726b01ee1b9432791483e06e5f2ecc208316af4dfeb2f44204ab81bfe782d087d4a4a40aca0a916fe4d8348945220635b2a3fd9704a9ad0e9f0c1",
          "sha256": "72c7d9e7255c0a64b973169f9375b60597b1a55ea06f4a17f75f14831fadd702",
          "sha1": "231480125a29a35efac0c8a3d31a2efbc997bdb8",
          "md5": "f8f5720b470bcf36b38dfcaa55128b2d"
        }
      ]
    }
  ]
}
