{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "download",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.liulishuo.okdownload",
          "module": "okdownload",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "ktx",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "download-hingin-SNAPSHOT.aar",
          "url": "download-hingin-SNAPSHOT.aar",
          "size": 286074,
          "sha512": "afe11d2ee88f13045a883383c2569497d18c5f554bef002508efe9bcdad68e834a2599f95a7b1a0c52a2dd2016211a9e33a66b04308f02dc035a7908e7135ced",
          "sha256": "18a966198fba2e055ff1c881229e322f10b9bca72a6d36a4649ea9a7fbff3da7",
          "sha1": "14ad118944d8d85cf7d018ed5742d7634b0cd536",
          "md5": "8726f3fca54a1841fc5e85d86ddab8d3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "sqlite",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "okhttp",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "okdownload",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "ktx",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "download-hingin-SNAPSHOT.aar",
          "url": "download-hingin-SNAPSHOT.aar",
          "size": 286074,
          "sha512": "afe11d2ee88f13045a883383c2569497d18c5f554bef002508efe9bcdad68e834a2599f95a7b1a0c52a2dd2016211a9e33a66b04308f02dc035a7908e7135ced",
          "sha256": "18a966198fba2e055ff1c881229e322f10b9bca72a6d36a4649ea9a7fbff3da7",
          "sha1": "14ad118944d8d85cf7d018ed5742d7634b0cd536",
          "md5": "8726f3fca54a1841fc5e85d86ddab8d3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "download-hingin-SNAPSHOT-sources.jar",
          "url": "download-hingin-SNAPSHOT-sources.jar",
          "size": 42233,
          "sha512": "5616ea7840e726b01ee1b9432791483e06e5f2ecc208316af4dfeb2f44204ab81bfe782d087d4a4a40aca0a916fe4d8348945220635b2a3fd9704a9ad0e9f0c1",
          "sha256": "72c7d9e7255c0a64b973169f9375b60597b1a55ea06f4a17f75f14831fadd702",
          "sha1": "231480125a29a35efac0c8a3d31a2efbc997bdb8",
          "md5": "f8f5720b470bcf36b38dfcaa55128b2d"
        }
      ]
    }
  ]
}
