{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "canvas2_lp",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 5653205,
          "sha512": "a5f7246e0ead1603df625a13ecdf180b59811798428aab40b9d019078c103b1540dea081f374e3af7d4b72a40abb26e287187f5bd4ac395852ba20f4547eeff9",
          "sha256": "b18f0b90236e19a0df91ddbd41e0f1c68529c58a43a884c8f3085161f0490cc3",
          "sha1": "b8dc829d60c190f6fe219a823a062a7dd2681756",
          "md5": "0c4f833abc2a01414be6be93493877c2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "engrave2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "doodle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "crop",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "qrcode",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "path",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "usbStorage",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 5653205,
          "sha512": "a5f7246e0ead1603df625a13ecdf180b59811798428aab40b9d019078c103b1540dea081f374e3af7d4b72a40abb26e287187f5bd4ac395852ba20f4547eeff9",
          "sha256": "b18f0b90236e19a0df91ddbd41e0f1c68529c58a43a884c8f3085161f0490cc3",
          "sha1": "b8dc829d60c190f6fe219a823a062a7dd2681756",
          "md5": "0c4f833abc2a01414be6be93493877c2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "url": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "size": 776867,
          "sha512": "17476ba7fefeca722de8da809e6a011d7102cc47bcf5bd8d9fec7f9ff451dbf0e3775bf4b368c3641c25a5d8bdf2d2b7a33a969224e7a6364c476f6075b8e62b",
          "sha256": "5fe69d1e3dd4aaa07393a51b4c657a03d12f4d94cbb80b0e3fd8431558630316",
          "sha1": "952532946327a405820b1cbea8b2b7ff23097ba5",
          "md5": "8994587e00d23c77a44084ad618d50c9"
        }
      ]
    }
  ]
}
