{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "canvas2_lp",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 6052262,
          "sha512": "46cb9591b89d3a521ee7a137573cbb65cd07c9f0ff95c51cb9bece007b8e97a6649c6411ceb389a0cd9012ceb8ad63ebf1ef008d8fa4ed9c63d6844681c4616d",
          "sha256": "b4d4ccc89806f5c15e135eebfacafd040097c4bf622c9e4daf9c8b534b9b099c",
          "sha1": "8950025fc2c0c625173dba24aefbaa1a2fdc759a",
          "md5": "bb94dbc8b47157940673a1f8b1397100"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "engrave2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "doodle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "crop",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "qrcode",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "path",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "usbStorage",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 6052262,
          "sha512": "46cb9591b89d3a521ee7a137573cbb65cd07c9f0ff95c51cb9bece007b8e97a6649c6411ceb389a0cd9012ceb8ad63ebf1ef008d8fa4ed9c63d6844681c4616d",
          "sha256": "b4d4ccc89806f5c15e135eebfacafd040097c4bf622c9e4daf9c8b534b9b099c",
          "sha1": "8950025fc2c0c625173dba24aefbaa1a2fdc759a",
          "md5": "bb94dbc8b47157940673a1f8b1397100"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "url": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "size": 811861,
          "sha512": "5d779a7dca7fba0b26f3d12eae71d8c22efea0210c1d4ff3852c26709eb33a62939a943ff554e01dd8aeb4fc5074022e2b845e3028b2f05580b69e1aae0a8910",
          "sha256": "f8263454023460ff98d9b6e0f7d79542709c38a4d88d0d3dac2d19f8ec9c75a4",
          "sha1": "9fd04758cfc93a9eee2f0cd89970983a2090bb30",
          "md5": "b0d3cf4c19015af902d21bfbb99d3bde"
        }
      ]
    }
  ]
}
