{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "canvas2_lp",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 7240399,
          "sha512": "8b3e76959002d4dcbf3ef85ecf3ab04d686a059c2c9d040fba552d7d15aa7c675eb7bb8cc445940d996c3ab6333a1782538b03d4a982e814f621a92ac1f57284",
          "sha256": "b7a8b904bd8041674a3acc9308e8305bdd68ac06c8564b0e6fd25bf0e270ce41",
          "sha1": "a81f3cd00b48711b5aa9942314d33b5f0d960249",
          "md5": "1c5061c69858220c955c0e9337529233"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "engrave2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "doodle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "crop",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "qrcode",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "path",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "usbStorage",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 7240399,
          "sha512": "8b3e76959002d4dcbf3ef85ecf3ab04d686a059c2c9d040fba552d7d15aa7c675eb7bb8cc445940d996c3ab6333a1782538b03d4a982e814f621a92ac1f57284",
          "sha256": "b7a8b904bd8041674a3acc9308e8305bdd68ac06c8564b0e6fd25bf0e270ce41",
          "sha1": "a81f3cd00b48711b5aa9942314d33b5f0d960249",
          "md5": "1c5061c69858220c955c0e9337529233"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "url": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "size": 841925,
          "sha512": "f1fad4a7fc40d5d48bc1bdbaf4fc53b10ace19a4be7c18036c66eab3a7ef11b89002afb67a64b29968168d88e621e3901e54f512f9ce8aeb0e79368a600c76f9",
          "sha256": "f8ebc11124fc56b40ec2d30a1f93eb3c97176f1524ffcf4a2c057c1da6029056",
          "sha1": "c92fe69d70b5172a596054e632ebf0a293e66408",
          "md5": "6bf57b9df2d7ad35289e7fbc42c7f99b"
        }
      ]
    }
  ]
}
