{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "canvas2_lp",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 6448318,
          "sha512": "e351ced1e8a19318a59cb798047314dca88144c8bfe29766932ffbb41be6cc46bc2f8858de9cf896993f4d4915e5eeec5bc0bb70c6de33c45259c6a6cf5274ec",
          "sha256": "b2afd6994473b8a1d9d7cf69868e336dc70e5eb86866d7d87db1e6b35ead8c93",
          "sha1": "22930a9ae5835e001835bf95c9e117648edfb7a4",
          "md5": "bf7826e7f686f2d66168a0e47710330d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "engrave2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "doodle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "crop",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "qrcode",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "path",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "usbStorage",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 6448318,
          "sha512": "e351ced1e8a19318a59cb798047314dca88144c8bfe29766932ffbb41be6cc46bc2f8858de9cf896993f4d4915e5eeec5bc0bb70c6de33c45259c6a6cf5274ec",
          "sha256": "b2afd6994473b8a1d9d7cf69868e336dc70e5eb86866d7d87db1e6b35ead8c93",
          "sha1": "22930a9ae5835e001835bf95c9e117648edfb7a4",
          "md5": "bf7826e7f686f2d66168a0e47710330d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "url": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "size": 829681,
          "sha512": "b48e3c79fc0a3d8470bae848c6a239ef2f40c4b7ef6c900b6c5cd7b8e48e1006238918bd9b47522a343c41e3f1a440cf4f9d0d6346536301f7e1544496d90401",
          "sha256": "196ea0957d4f126493a525196bf9ba40885f218295cfb9023aa125838ec13671",
          "sha1": "593b23418aa699f01dd3c8806c6661092b1fc916",
          "md5": "c47a21968bda381309a26715867d2e8d"
        }
      ]
    }
  ]
}
