{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "canvas2_lp",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 7241813,
          "sha512": "8e69c8a9b3a5e6b1804bd3f14081f7eb578e3c1fad506a48979596e946e8bed178b8d0457d15896a3eb06404e83dbe3b746b1559ff3308cf4ec056cfdb36d10b",
          "sha256": "ec99ce31a9dc1a0ace45a9777541821b319b41ed84f744c0db1e31f6bd262ff2",
          "sha1": "23ab2131e5ee9d886d09665154544c1ea463c71b",
          "md5": "b71441e506316fbbeb4178e292861f0b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "engrave2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "component",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "doodle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "crop",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "qrcode",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "path",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "usbStorage",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "canvas2",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT.aar",
          "url": "canvas2_lp-hingin-SNAPSHOT.aar",
          "size": 7241813,
          "sha512": "8e69c8a9b3a5e6b1804bd3f14081f7eb578e3c1fad506a48979596e946e8bed178b8d0457d15896a3eb06404e83dbe3b746b1559ff3308cf4ec056cfdb36d10b",
          "sha256": "ec99ce31a9dc1a0ace45a9777541821b319b41ed84f744c0db1e31f6bd262ff2",
          "sha1": "23ab2131e5ee9d886d09665154544c1ea463c71b",
          "md5": "b71441e506316fbbeb4178e292861f0b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "url": "canvas2_lp-hingin-SNAPSHOT-sources.jar",
          "size": 842129,
          "sha512": "412e0798a77dfa7341be7a08dfb4035314e3fb0110017a7fe364230216324101e8ae934cf0bbe42d134e492e7669f6d0a30885bbfa2284b9cb2ae9add7fb8517",
          "sha256": "c6f5e0f0b41d3eea9f774c69a7b285c390fec52c5fa37a1ea4a8646ba0f762ca",
          "sha1": "0b5d4f66ff3854d474cf931fa42052d52fa5a1cd",
          "md5": "f19835edfb185b8f13a2cef5393260f0"
        }
      ]
    }
  ]
}
