{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "transition",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.transition",
          "module": "transition-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "transition-master-SNAPSHOT.aar",
          "url": "transition-master-SNAPSHOT.aar",
          "size": 36386,
          "sha512": "ddf2ca2e4a41e0f5c60610da7a94f2bcee51bcfffa13c4cb36582f214f4be9b58af6aa5c98265344bd2b2b091b50e3383299386ef6f576cb4469310d5d1d7603",
          "sha256": "26e6f69c8cc3d2df3d7454bdb0364a20ae8d8471a44af9626faef4a2c3b1ee79",
          "sha1": "c7b8c2f7d81bd04eb591aae18ceb07588ff1152d",
          "md5": "d8b1b513b3ec968c5fca7f93019da496"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "transition-master-SNAPSHOT.aar",
          "url": "transition-master-SNAPSHOT.aar",
          "size": 36386,
          "sha512": "ddf2ca2e4a41e0f5c60610da7a94f2bcee51bcfffa13c4cb36582f214f4be9b58af6aa5c98265344bd2b2b091b50e3383299386ef6f576cb4469310d5d1d7603",
          "sha256": "26e6f69c8cc3d2df3d7454bdb0364a20ae8d8471a44af9626faef4a2c3b1ee79",
          "sha1": "c7b8c2f7d81bd04eb591aae18ceb07588ff1152d",
          "md5": "d8b1b513b3ec968c5fca7f93019da496"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "transition-master-SNAPSHOT-sources.jar",
          "url": "transition-master-SNAPSHOT-sources.jar",
          "size": 7425,
          "sha512": "438f41130a6bc1b90bdb290e6a8ab1269743ead65a97ad68124c56264e822a6fb00171e475b8ffd3f9626baf214084017e3c83e78fe9b6438458b0e476c19e09",
          "sha256": "8cbdb995b99b487e345582c501bc7df4d56e4a5e247caebdf48acbc4edd04f92",
          "sha1": "c5700492c38e6ef71517e7680517c7a64b243f12",
          "md5": "a6bd6dd96e389b1fec7f8b90193a1115"
        }
      ]
    }
  ]
}
