{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "media",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "media-hingin-SNAPSHOT.aar",
          "url": "media-hingin-SNAPSHOT.aar",
          "size": 134212,
          "sha512": "72ce5d00d3aa89dac57a5d517919becfc9f4443bdcb3b63cc3b2ec8f3035fa86d8cfc206691454d118efb4f33cb7f6b66d9739b19518690cc0183273be51fb84",
          "sha256": "0fbbcf076d64dd9a1d616234c12b0c2af8fbc80ac6df4a273ac4b24511b298e3",
          "sha1": "d0054f252ed26984be320c86f5ca29cbe627e81b",
          "md5": "1590dfd08535c4207332adb73ff45a7c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "media-hingin-SNAPSHOT.aar",
          "url": "media-hingin-SNAPSHOT.aar",
          "size": 134212,
          "sha512": "72ce5d00d3aa89dac57a5d517919becfc9f4443bdcb3b63cc3b2ec8f3035fa86d8cfc206691454d118efb4f33cb7f6b66d9739b19518690cc0183273be51fb84",
          "sha256": "0fbbcf076d64dd9a1d616234c12b0c2af8fbc80ac6df4a273ac4b24511b298e3",
          "sha1": "d0054f252ed26984be320c86f5ca29cbe627e81b",
          "md5": "1590dfd08535c4207332adb73ff45a7c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "media-hingin-SNAPSHOT-sources.jar",
          "url": "media-hingin-SNAPSHOT-sources.jar",
          "size": 42437,
          "sha512": "ff1971ab58aac0969fa58e61a18e61f2b5816b5482caacff6fbde37e81780f41ee7e4ed9ef7c6dbad755cf8da11b99ab418dc2275cd751ca59aa97f36a653598",
          "sha256": "b70f3018bf5df78024f5d3c8c7d5d4049a1a01fbd96a7c46f6600bd27b35892c",
          "sha1": "c6a0f8452de56032d55a820caa0f96a66c7cf7ea",
          "md5": "3ea5df5b8821c5d14d35a60c41662a3c"
        }
      ]
    }
  ]
}
