{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "RustHandle",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "RustHandle-hingin-SNAPSHOT.aar",
          "url": "RustHandle-hingin-SNAPSHOT.aar",
          "size": 1568081,
          "sha512": "de3205c632eb9c0939ee2bb5e5f4d01dcf2308e6422f003271dd9b25755b5502a137a1f1f985476774bf98276031a7ba827204bcc5e987e098cc3aba2bf9040b",
          "sha256": "a2bd32ba01b841548589ea668c7529a3330ec04313d5366f597ccfa9a5bb09e1",
          "sha1": "3b7efd5691d2778d0ad05320077fe48395251d33",
          "md5": "5272f4f10349b98c3206ada316184d06"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "RustHandle-hingin-SNAPSHOT.aar",
          "url": "RustHandle-hingin-SNAPSHOT.aar",
          "size": 1568081,
          "sha512": "de3205c632eb9c0939ee2bb5e5f4d01dcf2308e6422f003271dd9b25755b5502a137a1f1f985476774bf98276031a7ba827204bcc5e987e098cc3aba2bf9040b",
          "sha256": "a2bd32ba01b841548589ea668c7529a3330ec04313d5366f597ccfa9a5bb09e1",
          "sha1": "3b7efd5691d2778d0ad05320077fe48395251d33",
          "md5": "5272f4f10349b98c3206ada316184d06"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "RustHandle-hingin-SNAPSHOT-sources.jar",
          "url": "RustHandle-hingin-SNAPSHOT-sources.jar",
          "size": 7225,
          "sha512": "6d4e0b504bad7b417ee7aa5aaa4f00c115690fd4b6d8ffabfb1826b323c7d734460d6a4a65e93ee313229ba0298c3d6d3411de45c6d9616e5d38d1c9acf879f9",
          "sha256": "7ee768e806b8e37ba7e4352044fbd38aaa0cc5e4a79c627ec2e419b0feb3bf54",
          "sha1": "6d878532813470eeb62aeb6809ed2174585d563c",
          "md5": "bb061a10f03593a34054e9c5aa120767"
        }
      ]
    }
  ]
}
