{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "RustHandle",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "RustHandle-hingin-SNAPSHOT.aar",
          "url": "RustHandle-hingin-SNAPSHOT.aar",
          "size": 1619691,
          "sha512": "83a0006f9198005d50dcf918bffb3afeee66fab11a8b9cfebb5a6a2faf44a8354041d9014aed57e44066602bcafedd19ff020801e64ce955f1306c528bbc3206",
          "sha256": "a70e0018483ebcb81143a1bb4e2f930f9efa126421f062b28f7c652a63da5d1c",
          "sha1": "9ec8d7b710cdac9cd7c44c1fadf648a2a94a17fb",
          "md5": "9fa81b8f1db91992b90960887627e992"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "RustHandle-hingin-SNAPSHOT.aar",
          "url": "RustHandle-hingin-SNAPSHOT.aar",
          "size": 1619691,
          "sha512": "83a0006f9198005d50dcf918bffb3afeee66fab11a8b9cfebb5a6a2faf44a8354041d9014aed57e44066602bcafedd19ff020801e64ce955f1306c528bbc3206",
          "sha256": "a70e0018483ebcb81143a1bb4e2f930f9efa126421f062b28f7c652a63da5d1c",
          "sha1": "9ec8d7b710cdac9cd7c44c1fadf648a2a94a17fb",
          "md5": "9fa81b8f1db91992b90960887627e992"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "RustHandle-hingin-SNAPSHOT-sources.jar",
          "url": "RustHandle-hingin-SNAPSHOT-sources.jar",
          "size": 7845,
          "sha512": "75b35f4f13e4e3725c0aef182b23fdd706aca4bc097961e613cfb292d49132adaac97baf90e7e235eb3e128a345c0db681f8b353094bd7f25cef7bd82c96bf02",
          "sha256": "b16f46d55b448bb8f2a1798e68141b1a0c87fd27dcfaae56115eda97bb1e9b90",
          "sha1": "18928f553f37f87b4bcd33909fbb0b8b5f3576a6",
          "md5": "303f57a95663ee3eee6ba7a37f5914dc"
        }
      ]
    }
  ]
}
