{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "andserver",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.yanzhenjie.andserver",
          "module": "api",
          "version": {
            "requires": "2.1.12"
          }
        },
        {
          "group": "javax.activation",
          "module": "javax.activation-api",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "andserver-master-SNAPSHOT.aar",
          "url": "andserver-master-SNAPSHOT.aar",
          "size": 115811,
          "sha512": "4465be3a026f6e08a95d991cf899643ec0696cade7b011b0fa2565757a222ae368c3c3cd4be25cbf689417c716f97655d2f62646d4d7c21638ef98b6abc1cff3",
          "sha256": "d8b8040cbfcc1b128995f2e7deddc4d7dd5eab9ac58b57d07a378fd6771c963e",
          "sha1": "6f75433fe02625399e9c678f142cee594877cbca",
          "md5": "4f0e5cf0255c045cc4c35edf5e54c694"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fragment",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.yanzhenjie.andserver",
          "module": "api",
          "version": {
            "requires": "2.1.12"
          }
        },
        {
          "group": "javax.activation",
          "module": "javax.activation-api",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "andserver-master-SNAPSHOT.aar",
          "url": "andserver-master-SNAPSHOT.aar",
          "size": 115811,
          "sha512": "4465be3a026f6e08a95d991cf899643ec0696cade7b011b0fa2565757a222ae368c3c3cd4be25cbf689417c716f97655d2f62646d4d7c21638ef98b6abc1cff3",
          "sha256": "d8b8040cbfcc1b128995f2e7deddc4d7dd5eab9ac58b57d07a378fd6771c963e",
          "sha1": "6f75433fe02625399e9c678f142cee594877cbca",
          "md5": "4f0e5cf0255c045cc4c35edf5e54c694"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "andserver-master-SNAPSHOT-sources.jar",
          "url": "andserver-master-SNAPSHOT-sources.jar",
          "size": 33957,
          "sha512": "6fde9d82340e6c9c8011d226e2e914bc527ece71c9e182fa35069e87b625f779ed5e11742e13c0ec75abdc2fd0ef34ed08888962754945f0393f154aab4afd36",
          "sha256": "98d83831117f631d05de71bfd6a00565dcf4b36a275d2a73337f17f8c126b09c",
          "sha1": "e89efd7b400084f179936c3b7dbb4ecc755cd346",
          "md5": "56c8ba59ed8ace51f0ac93fd1d439e14"
        }
      ]
    }
  ]
}
