{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "record",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "record-master-SNAPSHOT.aar",
          "url": "record-master-SNAPSHOT.aar",
          "size": 180909,
          "sha512": "89dfe150725ca109a74c36048bca32d664a2630281cac9e80d27f88a76d87f9ef17ae3d09ae09ebf11e7f452d40d41272747ba9dac482d0a7f517761e2b8b16d",
          "sha256": "9e922e23008403c952214de1401aad86bcf7bb6b6a8baa809dbb4ec8df8659a1",
          "sha1": "e122e950dfa15be41d0dcd8fcade1609f6222bd3",
          "md5": "2ecf44320085c38d1edd01cdfdfebb73"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "download",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "media",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "record-master-SNAPSHOT.aar",
          "url": "record-master-SNAPSHOT.aar",
          "size": 180909,
          "sha512": "89dfe150725ca109a74c36048bca32d664a2630281cac9e80d27f88a76d87f9ef17ae3d09ae09ebf11e7f452d40d41272747ba9dac482d0a7f517761e2b8b16d",
          "sha256": "9e922e23008403c952214de1401aad86bcf7bb6b6a8baa809dbb4ec8df8659a1",
          "sha1": "e122e950dfa15be41d0dcd8fcade1609f6222bd3",
          "md5": "2ecf44320085c38d1edd01cdfdfebb73"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "record-master-SNAPSHOT-sources.jar",
          "url": "record-master-SNAPSHOT-sources.jar",
          "size": 72685,
          "sha512": "29967f6a5a12b39292fcd82f1550251de70f6d7158d580890131614d7aef51f0d63f4b10caf656eefece4fcb5f3be87a4ab12ef061a793ee8ed3e63d77a1c75c",
          "sha256": "0edf9380890d618d79dc13bf494bc3c494bf954e8424c0e710495a4cdc7c8df5",
          "sha1": "dac833728da8251ec8ae3684db2e432232f8bb28",
          "md5": "418cf7b14ecb9b50b11a45d5568c06a8"
        }
      ]
    }
  ]
}
