{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "dslitem",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "dslitem-hingin-SNAPSHOT.aar",
          "url": "dslitem-hingin-SNAPSHOT.aar",
          "size": 708022,
          "sha512": "a4d74f6737da9eb94ac025b32f6b08f3e36471724d5f4c46f0818185328ab0d4dae221e61076b20a1010ed0fdb138090dd80d2350b1a7951fe48f75629cacd4e",
          "sha256": "eaf5c438fa7884890c8c1acb141d0c43982212526780b8013f46dcfc4cb995c8",
          "sha1": "6b4a545dd8d75e9b71f60788c6ba869ecb713877",
          "md5": "334af8802080837eb68c15550f64c2e8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "dslitem-hingin-SNAPSHOT.aar",
          "url": "dslitem-hingin-SNAPSHOT.aar",
          "size": 708022,
          "sha512": "a4d74f6737da9eb94ac025b32f6b08f3e36471724d5f4c46f0818185328ab0d4dae221e61076b20a1010ed0fdb138090dd80d2350b1a7951fe48f75629cacd4e",
          "sha256": "eaf5c438fa7884890c8c1acb141d0c43982212526780b8013f46dcfc4cb995c8",
          "sha1": "6b4a545dd8d75e9b71f60788c6ba869ecb713877",
          "md5": "334af8802080837eb68c15550f64c2e8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dslitem-hingin-SNAPSHOT-sources.jar",
          "url": "dslitem-hingin-SNAPSHOT-sources.jar",
          "size": 218325,
          "sha512": "e1c85686ddb6f051c71cbe2c5a1280fe72bb888351e181d3080206570907d64ee81a213ea1f293ec822332f42a060d9dc9c3e9c8e2d7aa0c95713cdacb85f52d",
          "sha256": "21b8af0c974ca5d2eb2bf296bae38d30a83d61e0b8332155bf18555e352b67fe",
          "sha1": "20efe966e02b596f67d2365c10f1f235d64a8b5f",
          "md5": "5aac956a07379929ab88c908bdfd29b0"
        }
      ]
    }
  ]
}
