{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "dslitem",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "dslitem-hingin-SNAPSHOT.aar",
          "url": "dslitem-hingin-SNAPSHOT.aar",
          "size": 708003,
          "sha512": "ab3a81c49d8e5f041b4fa38d78ba721e8f18594f9f40df52bbf8259544977d0fb9b96f826d4e19c22e64eefe2ce9f607a110930524b3d987214c23e158e91c8b",
          "sha256": "bede788120034dbaf1fe1bde2c2820b8ca40301db587299cb12642d8e0a29452",
          "sha1": "31fb6a0a53ef3f3d9923b403b113cf52381a985e",
          "md5": "71cfddd4a0388140bd567b0a59a3150b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "dslitem-hingin-SNAPSHOT.aar",
          "url": "dslitem-hingin-SNAPSHOT.aar",
          "size": 708003,
          "sha512": "ab3a81c49d8e5f041b4fa38d78ba721e8f18594f9f40df52bbf8259544977d0fb9b96f826d4e19c22e64eefe2ce9f607a110930524b3d987214c23e158e91c8b",
          "sha256": "bede788120034dbaf1fe1bde2c2820b8ca40301db587299cb12642d8e0a29452",
          "sha1": "31fb6a0a53ef3f3d9923b403b113cf52381a985e",
          "md5": "71cfddd4a0388140bd567b0a59a3150b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "dslitem-hingin-SNAPSHOT-sources.jar",
          "url": "dslitem-hingin-SNAPSHOT-sources.jar",
          "size": 218325,
          "sha512": "e1c85686ddb6f051c71cbe2c5a1280fe72bb888351e181d3080206570907d64ee81a213ea1f293ec822332f42a060d9dc9c3e9c8e2d7aa0c95713cdacb85f52d",
          "sha256": "21b8af0c974ca5d2eb2bf296bae38d30a83d61e0b8332155bf18555e352b67fe",
          "sha1": "20efe966e02b596f67d2365c10f1f235d64a8b5f",
          "md5": "5aac956a07379929ab88c908bdfd29b0"
        }
      ]
    }
  ]
}
