{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "doodle",
    "version": "20250812",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "doodle-20250812.aar",
          "url": "doodle-20250812.aar",
          "size": 283750,
          "sha512": "568bce466cf1a3927f321d32394dff212c13876d5f61e859478b74978cba8c9b4bf52bd454b090505c7832a96f51c17d20e6a78a1d5bf25e0748cdce6cc0665c",
          "sha256": "c758345779241504d6cba798c3b8df8dac4abff3bd4d4a8401e7a61832f24510",
          "sha1": "2c3817ce3781c81e7b1d5f645b0bbcf0c3e66aff",
          "md5": "0862c78e050995eb87e24087f848b3c5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "com.angcyo",
          "module": "image",
          "version": {
            "requires": "20250812"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "doodle-20250812.aar",
          "url": "doodle-20250812.aar",
          "size": 283750,
          "sha512": "568bce466cf1a3927f321d32394dff212c13876d5f61e859478b74978cba8c9b4bf52bd454b090505c7832a96f51c17d20e6a78a1d5bf25e0748cdce6cc0665c",
          "sha256": "c758345779241504d6cba798c3b8df8dac4abff3bd4d4a8401e7a61832f24510",
          "sha1": "2c3817ce3781c81e7b1d5f645b0bbcf0c3e66aff",
          "md5": "0862c78e050995eb87e24087f848b3c5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "doodle-20250812-sources.jar",
          "url": "doodle-20250812-sources.jar",
          "size": 104243,
          "sha512": "72cd704291a05ff3a2070e9c0d37226e15f23f7bdf3b64bb65a5860ac9bceb53dbd3eef20392fb5ee80b88c1771cd3c52cf54ba4fb5c0f5580069efe60ebf4cb",
          "sha256": "ab39a98e325759b8dc3a027622e9cce275e6d8d457fcfa0c6087ca775c4b03d0",
          "sha1": "2aacd2d5a64e1c4b1513fd514fb0b2b108e1dcc1",
          "md5": "03e4f014a5f1136191738e432c3fac2b"
        }
      ]
    }
  ]
}
