{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "bmob",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.bmob",
          "module": "android-sdk",
          "version": {
            "requires": "3.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-master-SNAPSHOT.aar",
          "url": "bmob-master-SNAPSHOT.aar",
          "size": 161662,
          "sha512": "4a251539790dc1233283666a06b7e28963d39a7b51e2688eaaef25ada9e5dcc9d4bef7dce52d548ef3ca7514ad0419fa64e43029f15e4d29dc2063a78cd44058",
          "sha256": "ed8f2cc992e236e5667b2c82a646d0ccefcf82d28a2d1441836a4bdba1902795",
          "sha1": "4ccc547af6aa9917301b326f86e98391b5d8ef76",
          "md5": "afa958888e92813fc00b5cdb5ed9f316"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dialog",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "io.github.bmob",
          "module": "android-sdk",
          "version": {
            "requires": "3.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-master-SNAPSHOT.aar",
          "url": "bmob-master-SNAPSHOT.aar",
          "size": 161662,
          "sha512": "4a251539790dc1233283666a06b7e28963d39a7b51e2688eaaef25ada9e5dcc9d4bef7dce52d548ef3ca7514ad0419fa64e43029f15e4d29dc2063a78cd44058",
          "sha256": "ed8f2cc992e236e5667b2c82a646d0ccefcf82d28a2d1441836a4bdba1902795",
          "sha1": "4ccc547af6aa9917301b326f86e98391b5d8ef76",
          "md5": "afa958888e92813fc00b5cdb5ed9f316"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "bmob-master-SNAPSHOT-sources.jar",
          "url": "bmob-master-SNAPSHOT-sources.jar",
          "size": 33307,
          "sha512": "820d1824af43b9150ccf2bdd0dc9f0ed148b6eb8fa5973a60d5e76005c01eba76739beea39d7e4219c3ca6d6b152dd1b80aeca380b472acdcbc05302201d97f6",
          "sha256": "a66abe2989e27e4f15b8179084d584cb62d3a52b50e198cc2606b14b954219b1",
          "sha1": "1db2c37eb8b881fc5ef9b195e298d637ea4c396f",
          "md5": "9fde481d82bcac9a9d467ede6d4383e5"
        }
      ]
    }
  ]
}
