{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "widget",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "AnimatedSvgView",
          "version": {
            "requires": "1.0.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "widget-hingin-SNAPSHOT.aar",
          "url": "widget-hingin-SNAPSHOT.aar",
          "size": 2029510,
          "sha512": "47a2f499044e8b6266ea5ccf3308e0455f68694bd12794839bfb180611e2b75a337d47267bb02681060d59600315add19c419c4ba275c530d1d7aba333693fb8",
          "sha256": "00f45eab2a6f8d7259f112ab4f86ce635b60122b05637f0f2b31e6b15be0955a",
          "sha1": "4afd80784d5721f69926375afb96f930cc936d42",
          "md5": "fd4970a8b7c3c381ebbecda3c817ea44"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "AnimatedSvgView",
          "version": {
            "requires": "1.0.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "widget-hingin-SNAPSHOT.aar",
          "url": "widget-hingin-SNAPSHOT.aar",
          "size": 2029510,
          "sha512": "47a2f499044e8b6266ea5ccf3308e0455f68694bd12794839bfb180611e2b75a337d47267bb02681060d59600315add19c419c4ba275c530d1d7aba333693fb8",
          "sha256": "00f45eab2a6f8d7259f112ab4f86ce635b60122b05637f0f2b31e6b15be0955a",
          "sha1": "4afd80784d5721f69926375afb96f930cc936d42",
          "md5": "fd4970a8b7c3c381ebbecda3c817ea44"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "widget-hingin-SNAPSHOT-sources.jar",
          "url": "widget-hingin-SNAPSHOT-sources.jar",
          "size": 1060453,
          "sha512": "9f7e6a9d4d118c68b978ecd3f33b7aacd929d5ce76a514671bceaf0cf8363b6343cc2a6993f3e05a95a1fcf1e573c6e56d26ddfebcfe21fb90360b7fe8676483",
          "sha256": "744d793d585640210ec15becec69163141f5769cc47f4ed47ea5a174c5735569",
          "sha1": "43d3ebde7f7bc91b5b2a9fe1f839a3b6b012f94e",
          "md5": "dc2e7e38d46792a7938b05fc0fd025a2"
        }
      ]
    }
  ]
}
