{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "widget",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "AnimatedSvgView",
          "version": {
            "requires": "1.0.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "widget-hingin-SNAPSHOT.aar",
          "url": "widget-hingin-SNAPSHOT.aar",
          "size": 1914493,
          "sha512": "f3d59c06b6882fd8546c2613f669d043c106a01b96a5a7702e55da43a3136f927159a3c96db68da87c1b67f41a97d8b87f91f353020719fbfdc7baa5b0a1e6c6",
          "sha256": "37546ad2baf24672c651ce1990adcf262b0951925408386223a975e4dbb7af4a",
          "sha1": "ccb12735339ae5b25a0641529ae6310b23d3564f",
          "md5": "d44b0a81abd17be1a279516cde26fef2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "AnimatedSvgView",
          "version": {
            "requires": "1.0.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "widget-hingin-SNAPSHOT.aar",
          "url": "widget-hingin-SNAPSHOT.aar",
          "size": 1914493,
          "sha512": "f3d59c06b6882fd8546c2613f669d043c106a01b96a5a7702e55da43a3136f927159a3c96db68da87c1b67f41a97d8b87f91f353020719fbfdc7baa5b0a1e6c6",
          "sha256": "37546ad2baf24672c651ce1990adcf262b0951925408386223a975e4dbb7af4a",
          "sha1": "ccb12735339ae5b25a0641529ae6310b23d3564f",
          "md5": "d44b0a81abd17be1a279516cde26fef2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "widget-hingin-SNAPSHOT-sources.jar",
          "url": "widget-hingin-SNAPSHOT-sources.jar",
          "size": 969729,
          "sha512": "4bd8fd3769247650b0b1f971dbe9fe90d7474992dfa648daa4d7114c1e37e2a28a181ff9da59b6b6c4d9b4d5e6b94bad831bbb1387920d4a8619cc9f58d7f1e8",
          "sha256": "342d85783affb9f6bef8f5ad320f879eea0abb685d1bb31e8d0ba2421034ce8e",
          "sha1": "9db4ec21751b427f9dc507034da69eae57341d3d",
          "md5": "6d33ba010fb231ea06ae00c5e29cae9d"
        }
      ]
    }
  ]
}
