{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "umeng_apm",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "umeng",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "umeng_apm-hingin-SNAPSHOT.aar",
          "url": "umeng_apm-hingin-SNAPSHOT.aar",
          "size": 15781,
          "sha512": "52bfc247d7fbde25279c643cf2c5241c9c8d7be702d3ede151d52d26ec35f8def59242b3da5f83436e0ce47915550c5fd5a288652716fd6d3b544afdbc809abc",
          "sha256": "1048c405deca0ffd63bc722d69f247d9192f5561fd9c9838b3bf9be1d125a6f3",
          "sha1": "65d2ca81ce0ea1a25a59d6ba93f953ac85ec3a4a",
          "md5": "79c84d1d90e6b96d6267dad978c9c967"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "umeng",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "umeng_apm-hingin-SNAPSHOT.aar",
          "url": "umeng_apm-hingin-SNAPSHOT.aar",
          "size": 15781,
          "sha512": "52bfc247d7fbde25279c643cf2c5241c9c8d7be702d3ede151d52d26ec35f8def59242b3da5f83436e0ce47915550c5fd5a288652716fd6d3b544afdbc809abc",
          "sha256": "1048c405deca0ffd63bc722d69f247d9192f5561fd9c9838b3bf9be1d125a6f3",
          "sha1": "65d2ca81ce0ea1a25a59d6ba93f953ac85ec3a4a",
          "md5": "79c84d1d90e6b96d6267dad978c9c967"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "umeng_apm-hingin-SNAPSHOT-sources.jar",
          "url": "umeng_apm-hingin-SNAPSHOT-sources.jar",
          "size": 1687,
          "sha512": "d9b327dea237dd7583b5528be486732fbfcb3a5c7f73102a0744c5eb79e97bef5504db4de1737cd84af82df0597b8b2878bf987caa7acd4a460b914fb6b7dcb1",
          "sha256": "a0c066cebdc91d8e0269c724dbe5c1fe8f201cd06c3f2d0549f06a35afebe7fb",
          "sha1": "6fbb8c8783530754f579f356f831a6a973c856a7",
          "md5": "10fcb7a704b1fdb5c2558769d483ef0a"
        }
      ]
    }
  ]
}
