{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "lpDevice",
    "version": "2025081203",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "250722"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-2025081203.aar",
          "url": "lpDevice-2025081203.aar",
          "size": 11267761,
          "sha512": "a2b7ece3491cf2c2246653ef47a2e3ed229e8fb7298e345c546553a3c75fd15ee942efb86187c5259b1f39d52856ccc75b7683540f80884b40849b20aedbbad3",
          "sha256": "529ba9b7835543f678d91fc7b59b2fc12f21fe392f6cc166ca0e9e693bb70524",
          "sha1": "b81c404e4f470d9c4f3b449057dc0a039ce54c2e",
          "md5": "d5a457e32574076e531c03d5eec19e9f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "glide",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "pager",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.angcyo",
          "module": "fsc",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bitmapHandle",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "RustHandle",
          "version": {
            "requires": "250722"
          }
        },
        {
          "group": "com.angcyo",
          "module": "imageProcess",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "objectbox_lp",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "vector",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "com.angcyo",
          "module": "jxl",
          "version": {
            "requires": "2025081203"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "lpDevice-2025081203.aar",
          "url": "lpDevice-2025081203.aar",
          "size": 11267761,
          "sha512": "a2b7ece3491cf2c2246653ef47a2e3ed229e8fb7298e345c546553a3c75fd15ee942efb86187c5259b1f39d52856ccc75b7683540f80884b40849b20aedbbad3",
          "sha256": "529ba9b7835543f678d91fc7b59b2fc12f21fe392f6cc166ca0e9e693bb70524",
          "sha1": "b81c404e4f470d9c4f3b449057dc0a039ce54c2e",
          "md5": "d5a457e32574076e531c03d5eec19e9f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lpDevice-2025081203-sources.jar",
          "url": "lpDevice-2025081203-sources.jar",
          "size": 281721,
          "sha512": "c61653309d6cc1a4727088dfc2769d94eba3af881b27dbfca3da25ae42e50b1b0315d029d91bd3385cf8b8dc89ab1d7d64ecd43fcfa73d3a67bd3ddbf95967ce",
          "sha256": "e3fb9501add407336c2af00bcca66692d018d8dca07cd0707d99c0064d12026b",
          "sha1": "122fb71639dfb479332cb53da2be7ec004664856",
          "md5": "e40d48dfdafc7f5f948b3ec32c6b9d0a"
        }
      ]
    }
  ]
}
