{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1101667,
          "sha512": "71098ae3a4ff85cf7f6edb0f357f4469b8484f2608fdf253ec1adb794f186872af5b59a6cee522502f34cff64aef55f3e31ae96558be559355e4a7db4353f80a",
          "sha256": "6ccc37b224e77090a3ad6c45f7aeaa25724aa22e8fd57483c4bda82881c5847b",
          "sha1": "8ac18caadd776d6dba97ada99f588bbed7a8e9c1",
          "md5": "75b9340e642925d0bd921493e3a2d593"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1101667,
          "sha512": "71098ae3a4ff85cf7f6edb0f357f4469b8484f2608fdf253ec1adb794f186872af5b59a6cee522502f34cff64aef55f3e31ae96558be559355e4a7db4353f80a",
          "sha256": "6ccc37b224e77090a3ad6c45f7aeaa25724aa22e8fd57483c4bda82881c5847b",
          "sha1": "8ac18caadd776d6dba97ada99f588bbed7a8e9c1",
          "md5": "75b9340e642925d0bd921493e3a2d593"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 294485,
          "sha512": "3fa185fed9511e0f1c92f3f6185517afdac03567018de587b2a22f1227eed4a8d307a19c7d30ef5c8282915889ceefd20a4b013454a57000907d1fb715e058aa",
          "sha256": "590750238c2fb5344a16ed20ee5a381925ce19be6e05121d4a889539f31e449f",
          "sha1": "2be5c133e1db6e8c3ceb66b00d1d7236f43d443c",
          "md5": "7357fed0466b30c24f861e5b148ce4e3"
        }
      ]
    }
  ]
}
