{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1172626,
          "sha512": "8c3254f8f0175870adaf45b6727ff8899e51b09334561289ccf1f9cbef84e670e57f9c4574c59ea748b936b9de127a7212a57dbbabea127263ef6644dfd855dc",
          "sha256": "9ab3cb25337dfc392173f43e28785fd5f40f6274aac2e11dd8ce22883f3d926e",
          "sha1": "1da2e7633decabcd1c28980db6366ddd949c5469",
          "md5": "378458158c075a16fdf0417e269b0914"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1172626,
          "sha512": "8c3254f8f0175870adaf45b6727ff8899e51b09334561289ccf1f9cbef84e670e57f9c4574c59ea748b936b9de127a7212a57dbbabea127263ef6644dfd855dc",
          "sha256": "9ab3cb25337dfc392173f43e28785fd5f40f6274aac2e11dd8ce22883f3d926e",
          "sha1": "1da2e7633decabcd1c28980db6366ddd949c5469",
          "md5": "378458158c075a16fdf0417e269b0914"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 314901,
          "sha512": "7a4994b3fe6b0d8bf42268d25fbc4adbfcf9a46d0c342888574b0c78e68c96c6508124d83cba739b161856cfbe907a03fec770fc0c2a57d61687cf6907fd270f",
          "sha256": "92a73c25982a9bde03f588dd9fef3162afd67e69bb0a518fc8f80b511916e3a9",
          "sha1": "e618ff536368c83fc811f55a2e1bdfcbfb047857",
          "md5": "89800e48cc6abd3d4ab12df2deb75e0f"
        }
      ]
    }
  ]
}
