{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1215295,
          "sha512": "6ca4e1748aba2808c2d14f6d60a6b8233b6ff7fa72d9f962533d0be6ce41cefc48b2a47561bae75df68aef125918e942c434fe4abb470821cf00644f512cfc62",
          "sha256": "2ea619dcb72d6f212dc0428bb7c24f1afc7666579da03d6e04fc65346ef16efd",
          "sha1": "34287f6c389c0c57a116037cdce07e1641a824c9",
          "md5": "3e10232e597dbaa70db71c4da748066a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1215295,
          "sha512": "6ca4e1748aba2808c2d14f6d60a6b8233b6ff7fa72d9f962533d0be6ce41cefc48b2a47561bae75df68aef125918e942c434fe4abb470821cf00644f512cfc62",
          "sha256": "2ea619dcb72d6f212dc0428bb7c24f1afc7666579da03d6e04fc65346ef16efd",
          "sha1": "34287f6c389c0c57a116037cdce07e1641a824c9",
          "md5": "3e10232e597dbaa70db71c4da748066a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 331327,
          "sha512": "8a2b264220279bbe20802dbd32c24336709bb87446fadd8880e93dccbea3decebb3f85841c5978477fb39c1f7da24507863ef8c0e0753d854fb87304946e15ff",
          "sha256": "db6fab8e704349dd87b9fb8df6ffc914e515af5d8cc3776bf08a2d4498951397",
          "sha1": "c855d4a008692ffbc0d1b224b9c4e9d00a063236",
          "md5": "95d8528d4e7cf95f9c66883dbd7d027e"
        }
      ]
    }
  ]
}
