{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1219769,
          "sha512": "612739155db312d531ba620fcfbeaf80c40f86d68a3f83558425f6e212e5964f37c9980e680c901cde165e72b17e1768194a8afc7c95020000513bbb30535d10",
          "sha256": "0b624b131e3fd4b56fca45f8e7a99a618724cd0214dd669b0df0f433a88edf07",
          "sha1": "331df0d7ad5af29274bedf84a646f11857d035ea",
          "md5": "da2a4c71df663b933189c4ef7da6e170"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1219769,
          "sha512": "612739155db312d531ba620fcfbeaf80c40f86d68a3f83558425f6e212e5964f37c9980e680c901cde165e72b17e1768194a8afc7c95020000513bbb30535d10",
          "sha256": "0b624b131e3fd4b56fca45f8e7a99a618724cd0214dd669b0df0f433a88edf07",
          "sha1": "331df0d7ad5af29274bedf84a646f11857d035ea",
          "md5": "da2a4c71df663b933189c4ef7da6e170"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 332055,
          "sha512": "c5e015e93e5e8bfc11b8611cad6adfe4f4e51172f4649b32061e6a1bd7875fbd0b7d0c04e001fef6e009145ef46aec88d0e46e886afdbb3b8d3e2c7e734992fa",
          "sha256": "e897ac755b7e4ce24b4290e6af0c6cd527ae1feb45d89679aa194f8133bfe5c9",
          "sha1": "6e7e0fa7e65e5ec1580264a97d3265ca8c824f00",
          "md5": "31f3a67ed5729d0baeb2e1bfd1befb11"
        }
      ]
    }
  ]
}
