{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1245689,
          "sha512": "4ba1165cdef47ffc16b5e4622a6242e3dedb463f43029d22dc4cdd42ed71d74d4690f48b60bb8618367c66cd49b6c3e8bd16b62d27f9f5bbce0a46eca7b10807",
          "sha256": "3083a038747bb02c2f1394fa535534017afd043809938d71090cbd0aca677937",
          "sha1": "dbefe26a679623af9e46631b525cf5952701ee64",
          "md5": "00d14c88c6bac443d40f73e63be2eae5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1245689,
          "sha512": "4ba1165cdef47ffc16b5e4622a6242e3dedb463f43029d22dc4cdd42ed71d74d4690f48b60bb8618367c66cd49b6c3e8bd16b62d27f9f5bbce0a46eca7b10807",
          "sha256": "3083a038747bb02c2f1394fa535534017afd043809938d71090cbd0aca677937",
          "sha1": "dbefe26a679623af9e46631b525cf5952701ee64",
          "md5": "00d14c88c6bac443d40f73e63be2eae5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 334671,
          "sha512": "45e462748500fba1cd4c234d24288ad60d04f548b6cb739c34cd3be7b6edb5245bff9ce4097965fb5f0c2fbedd5420271d6d7c122be4a11256951d90503f7eb5",
          "sha256": "58e84927b0a8a0158d4326c26cd957bca521e01fa152f839a1a1425aaa22a7ef",
          "sha1": "772581a77d4903b26a5437ac569d9e7e550b8af6",
          "md5": "3e3d74a53e6ad3e987ca29ebb68b29f9"
        }
      ]
    }
  ]
}
