{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1245711,
          "sha512": "8b3b9faf8a003e5c180e70f355cdb0663c79eadf3fa82d26efbf80e345390509a4e54790d434e180ac41454543e640f7beb2047877e492516828706187844d5b",
          "sha256": "70b96a3fadcdb37eaac5f1531200c228cd614939f74990da5be810e3f5f49b97",
          "sha1": "2e27ef4db5e9a83e7db6f1d1751f0c4a4e9e4c46",
          "md5": "4b075cdfa9439d07ff2cf5eddb60d6d3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1245711,
          "sha512": "8b3b9faf8a003e5c180e70f355cdb0663c79eadf3fa82d26efbf80e345390509a4e54790d434e180ac41454543e640f7beb2047877e492516828706187844d5b",
          "sha256": "70b96a3fadcdb37eaac5f1531200c228cd614939f74990da5be810e3f5f49b97",
          "sha1": "2e27ef4db5e9a83e7db6f1d1751f0c4a4e9e4c46",
          "md5": "4b075cdfa9439d07ff2cf5eddb60d6d3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 334845,
          "sha512": "b0f80eaa0d4bde76feaaea3a93139ec8a4c09e7080c979307ba436d4de899a62794b584abb6192fcf26c568f51b6f7f72b97c5b6d6436c168a319c8e9a611fa0",
          "sha256": "91a0bbd5f3b988ba982fc38914744660e4a5daa5de0063f18caa1d26c07ee445",
          "sha1": "f3ab258dbd1814ec9cf264d3778d5813f8b0e0f6",
          "md5": "b8ae90a82de42b8efe4bc5bc5142ddce"
        }
      ]
    }
  ]
}
