{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1111111,
          "sha512": "5b1b7d6a5febacd7651ff4a1a7be2e228d7394f6276387c1ee3f667d0e6c6b818a26d167e5248c050598ed0f20128572c7e51752b2620afd72db15c7e8e7f26b",
          "sha256": "30637acf17e61732c37f505eac309c3075bdfccddb52b2a06889c4f01a1d4b99",
          "sha1": "17a200114c38e885492718c014f4d7346dfd0acd",
          "md5": "b131bdaaa8d3e1f4cc56229528e178c2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1111111,
          "sha512": "5b1b7d6a5febacd7651ff4a1a7be2e228d7394f6276387c1ee3f667d0e6c6b818a26d167e5248c050598ed0f20128572c7e51752b2620afd72db15c7e8e7f26b",
          "sha256": "30637acf17e61732c37f505eac309c3075bdfccddb52b2a06889c4f01a1d4b99",
          "sha1": "17a200114c38e885492718c014f4d7346dfd0acd",
          "md5": "b131bdaaa8d3e1f4cc56229528e178c2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 299311,
          "sha512": "f5127975cb6ed8360a475898351188f6bf92e54b676f3a82ae0afedd1b66c86b61f7c0375bf2960af057f1ac34e829e017511130f89f680e43beb5581de40f04",
          "sha256": "fb45c870fdd715562df90b9eabdec3006e37a088218c8e06be1ca87615976588",
          "sha1": "cb5502a9ee1615747a53493759e668eaee734c9e",
          "md5": "dec41783593afac29cfded1eaa92ab39"
        }
      ]
    }
  ]
}
