{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1263468,
          "sha512": "7f31ccd473e80a143d674e0a92056c86a46be94f0e439992238ef8cd6fe7968fc638aa8aa19d5b2b82e94e8e508e52bbf4c57700a7362c8d673618630912de4e",
          "sha256": "88a98380efe34bdc59a8c2050e80a1380532a1c426efc7332bbb60ef48a8ab97",
          "sha1": "d68c7db7360e4636cb4e457665318b5c9c607990",
          "md5": "bb0aa658e6fef1d7b5da2106594f3f32"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1263468,
          "sha512": "7f31ccd473e80a143d674e0a92056c86a46be94f0e439992238ef8cd6fe7968fc638aa8aa19d5b2b82e94e8e508e52bbf4c57700a7362c8d673618630912de4e",
          "sha256": "88a98380efe34bdc59a8c2050e80a1380532a1c426efc7332bbb60ef48a8ab97",
          "sha1": "d68c7db7360e4636cb4e457665318b5c9c607990",
          "md5": "bb0aa658e6fef1d7b5da2106594f3f32"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 336359,
          "sha512": "f388c722eb8ac2745b1868f090eaa78781d370b2895e580e513eab3d6221ebe8fbbc2c8961e86abe9380a0c32922fc2dad9f39f14be6c4c20fb4b32ca3765f9f",
          "sha256": "bce88b066c8e9ed159183534cb392c45c5a3014b89cd02288b9e01cd8da39d97",
          "sha1": "b3d6cb16eb3b504b9c8bf1fd243c92263165a371",
          "md5": "58efdd6c3a9a44d1660c7d5dc62f31a7"
        }
      ]
    }
  ]
}
