{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1262940,
          "sha512": "6d4810032b133f9355ced95f7005b7fff323732dba91fcf07607c9ae3c9600ba83e999b79b222afa2f6e0ad6c2feec2ca0cc4d78678b8a5521517691a503f7c1",
          "sha256": "f7e37f6090af8ab18040ef7ce8a13de501ccf1ab7aaf3700d25b91dc99c4d504",
          "sha1": "c714a3be056fc598fca41dad2963f5ad83963451",
          "md5": "8497e8b11d85a59cc9801718b1f881e3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1262940,
          "sha512": "6d4810032b133f9355ced95f7005b7fff323732dba91fcf07607c9ae3c9600ba83e999b79b222afa2f6e0ad6c2feec2ca0cc4d78678b8a5521517691a503f7c1",
          "sha256": "f7e37f6090af8ab18040ef7ce8a13de501ccf1ab7aaf3700d25b91dc99c4d504",
          "sha1": "c714a3be056fc598fca41dad2963f5ad83963451",
          "md5": "8497e8b11d85a59cc9801718b1f881e3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 336161,
          "sha512": "dad11eb9a98183a38dbf47ac4dda84b6878349163725ace5a8f56bc61018e86af0f7cc962c7d5dfd7306044204290726346ca48d84f5e2c08e0561f03239304b",
          "sha256": "d57e6e1c09defaa3f543094b0912ff147cfca704e0b1076e45b74fd83cae822b",
          "sha1": "72e4b14793628ce1b5cf61f55e18917c61a5ec24",
          "md5": "34b0f7a610e076e7a5869c481d079ce9"
        }
      ]
    }
  ]
}
