{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1211656,
          "sha512": "03f0bf70b09969420f857ab99154da95f4f8330643d036f856269f257a5476e49f41a5b91c901c60b55a97fe15f9df57e64127d1462f38aff2de4fc80e7011f4",
          "sha256": "e3f1adba3c9bc9d013ee3b26ec41df03d0a16d425c6206977e4f04a170f92bf2",
          "sha1": "c04e8013bce2a86fee1acfaf25c493c38659d28a",
          "md5": "5662f1f2e8221ccaf8f660fb10633341"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1211656,
          "sha512": "03f0bf70b09969420f857ab99154da95f4f8330643d036f856269f257a5476e49f41a5b91c901c60b55a97fe15f9df57e64127d1462f38aff2de4fc80e7011f4",
          "sha256": "e3f1adba3c9bc9d013ee3b26ec41df03d0a16d425c6206977e4f04a170f92bf2",
          "sha1": "c04e8013bce2a86fee1acfaf25c493c38659d28a",
          "md5": "5662f1f2e8221ccaf8f660fb10633341"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 330119,
          "sha512": "ea9e0437257e18d04ffbcd977e12f3b6ffa0d016169a49291f0e0ac04deb156a2517062dff7087ea13060175a2d31bcb5ad37cc85cb417f31560ad784fa6c0e2",
          "sha256": "2b051d89254453b8ed2819caef290456b6223f34ba204ff7aef79946edc11e03",
          "sha1": "c5a00fd0edba93d545e65f6986e03ce3c7109054",
          "md5": "2dd2bfec203d5c0c8305c89654416b26"
        }
      ]
    }
  ]
}
