{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1166565,
          "sha512": "432546778ca447119d3b5ce64ccc865b8bdb3589ffa4788b30ea01b54553aa66ff827add324ff5f0b9abe35e589379d12b07669ac91fe1c57a2a6c853ac190b5",
          "sha256": "0d41dac28815c59c2716eaeb2f532bfcd7b0fe88cfb9211c986334cf2b38c3d9",
          "sha1": "b47c6686407ad6f5399bd3e69a198d06b481e449",
          "md5": "0611045f7944b7dc2834ef57bcff7344"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1166565,
          "sha512": "432546778ca447119d3b5ce64ccc865b8bdb3589ffa4788b30ea01b54553aa66ff827add324ff5f0b9abe35e589379d12b07669ac91fe1c57a2a6c853ac190b5",
          "sha256": "0d41dac28815c59c2716eaeb2f532bfcd7b0fe88cfb9211c986334cf2b38c3d9",
          "sha1": "b47c6686407ad6f5399bd3e69a198d06b481e449",
          "md5": "0611045f7944b7dc2834ef57bcff7344"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 314245,
          "sha512": "582f152eded44b5f3c2089c3447f72e4ff953411ba77a02bde9a83d40a8e172150f50be99a35ec3ea3717fa1ec4ad69c266388802aa01b9f97d39290984fa0f6",
          "sha256": "6ede231113d5e0cb6afa3e0d0759f20deb46d291cea417ea916162646f360031",
          "sha1": "5e360694d93e27a0e260d9f127549584c1023d6b",
          "md5": "bacd47adb797c3fe2d04dfc02ea08745"
        }
      ]
    }
  ]
}
