{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1249684,
          "sha512": "be4da9bf99dd59817597f60489f933850e555f60d27b0ef24025d4c893723e268cae5059bd8ed3fa23dcf05d74e174fda81495ef85cc4ef7199afaa920a06a85",
          "sha256": "66f1f92edfb96c99b955fd3ae1f88a3e2b0279a12298ff0edb5ccc5c74174c20",
          "sha1": "5c442cf3d7b7bfd1443a7ec310a61b6ed304d43f",
          "md5": "19442d00efdc0583b55e0a32af7ada42"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1249684,
          "sha512": "be4da9bf99dd59817597f60489f933850e555f60d27b0ef24025d4c893723e268cae5059bd8ed3fa23dcf05d74e174fda81495ef85cc4ef7199afaa920a06a85",
          "sha256": "66f1f92edfb96c99b955fd3ae1f88a3e2b0279a12298ff0edb5ccc5c74174c20",
          "sha1": "5c442cf3d7b7bfd1443a7ec310a61b6ed304d43f",
          "md5": "19442d00efdc0583b55e0a32af7ada42"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 334851,
          "sha512": "b344900b74f3d9ed0eb60d1167d45473ef7e8bfa83eea727b2dee7cb0e938c278cf1c74d183c0704d1873555c3554eed2def47cc072c8da988e96cb4dd801422",
          "sha256": "53b4c8274e8141d1f3f29060e2ac72432573a004985f06cd14a634bf6b516b4f",
          "sha1": "eeba5c811b5fac13abf64a09dfa9a0d438a9b083",
          "md5": "2f869e7277f72ca611e1167703ac8398"
        }
      ]
    }
  ]
}
