{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1245954,
          "sha512": "025beddeaac73072f8aa1502d5ce0692b3c6e1644ba2e76393dd0f7b38c38b591ede2f5142ee92aac6142a735e489ff275a3194b53c5f070d82d1c86b55c3bda",
          "sha256": "5b74ef6a5ca45a9339e6262369ff501ea5b8d2545e0371dc93fc4bf2158b3bcb",
          "sha1": "68af36d2d002819398643f87735c9efcf0473c0f",
          "md5": "430ded5f4e89419daea9bbf38cbdaf2a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1245954,
          "sha512": "025beddeaac73072f8aa1502d5ce0692b3c6e1644ba2e76393dd0f7b38c38b591ede2f5142ee92aac6142a735e489ff275a3194b53c5f070d82d1c86b55c3bda",
          "sha256": "5b74ef6a5ca45a9339e6262369ff501ea5b8d2545e0371dc93fc4bf2158b3bcb",
          "sha1": "68af36d2d002819398643f87735c9efcf0473c0f",
          "md5": "430ded5f4e89419daea9bbf38cbdaf2a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 334669,
          "sha512": "b5902e3cb32dd8c3b22e19a9da73197483552429ecce4a5d8de3feb0b7ce1a652d5ce0c1b44fd8f0306ba15c9c5ebc3dc758055e1f8bd31f4d9df7a5de4f68fb",
          "sha256": "ccdabae051169b078f9df39f314b3417b5ef45adcbd3e6195c01b5d509203ba2",
          "sha1": "c879fad40c85357e1903045c6bd8fb82d9f38e77",
          "md5": "804908e6e68852695b7f5a2c6f3dc982"
        }
      ]
    }
  ]
}
