{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1101522,
          "sha512": "f93d3d3ee58a55353d8f3c9274100bca931ed88d9de6739865c67c1ba8e5fd9ebb1b0d0a56267c0346d6c53040367b1d871fe3cb03bcfa5600aa487e523dfeb4",
          "sha256": "8761da5e238e317cee8922aef0b4c217939d5a26c93a55fbedddcdfecb13ab68",
          "sha1": "4cf0534dad1215890e1da09cf084497af2c807cd",
          "md5": "58772503ab6a813e8e55b31bcfbc1b6d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1101522,
          "sha512": "f93d3d3ee58a55353d8f3c9274100bca931ed88d9de6739865c67c1ba8e5fd9ebb1b0d0a56267c0346d6c53040367b1d871fe3cb03bcfa5600aa487e523dfeb4",
          "sha256": "8761da5e238e317cee8922aef0b4c217939d5a26c93a55fbedddcdfecb13ab68",
          "sha1": "4cf0534dad1215890e1da09cf084497af2c807cd",
          "md5": "58772503ab6a813e8e55b31bcfbc1b6d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 294315,
          "sha512": "52877fb84f997d65ff3e70cce3c876448a79e554f9e0961f65b3ee137daffb047dc85d81285d097909a3feb0a627dab43e898b8fcdded477685fd7fba32fda37",
          "sha256": "252b8c03570917a1d22b853443f58cb44cdd6a8e7f8ab87619bfb20f62735328",
          "sha1": "e7cc8c31b8fe4ce7c85de35e15c8a1b6ac3e4afb",
          "md5": "2bf030e5e3812ef53dbb64fd24dba646"
        }
      ]
    }
  ]
}
