{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1185956,
          "sha512": "616a24e8ab7858729709e3a7a86132895984cd70dc7564c9a894fc831069d816d19d830552233555bf1aa6a8f88d78f9608a744cda9e3ce69c6948e309a1ad9f",
          "sha256": "5b36d01d698b2a9f30f9c456c9ee369687906c516a8d359b4badc090ca1fb283",
          "sha1": "05fd92bcea64a0576555350971aacf6ba7913173",
          "md5": "7cbc9abbd20d1e354f9934a4f5d9357a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1185956,
          "sha512": "616a24e8ab7858729709e3a7a86132895984cd70dc7564c9a894fc831069d816d19d830552233555bf1aa6a8f88d78f9608a744cda9e3ce69c6948e309a1ad9f",
          "sha256": "5b36d01d698b2a9f30f9c456c9ee369687906c516a8d359b4badc090ca1fb283",
          "sha1": "05fd92bcea64a0576555350971aacf6ba7913173",
          "md5": "7cbc9abbd20d1e354f9934a4f5d9357a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 322687,
          "sha512": "46cddadf15cd1ed96fe77a6e0b7ae499f536f7cbe6de601a953d857fad87e53ca45be5eb928ba8601a09f9b0ad1ecf99420e2902fd72eed045433b3577786226",
          "sha256": "95c079d7a451e895774bf32ac087e0b423c7bd82468d7ad178c069d42cac0dcd",
          "sha1": "74a8e54355691d064944a057a5e6d3d9b58268e0",
          "md5": "14e7285476bddec8d6018d4484b1c12e"
        }
      ]
    }
  ]
}
