{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1217085,
          "sha512": "8602797310f118f34d308c74f43f3924c2cb669435079ab9936c0e3dadfa376881c2e847103cb1db4df6afeaf7f9c735a48ba2d4ceb43fcc500de1dca5430d74",
          "sha256": "3a14c389dd7272ed0e617a55ea8baeb45b3ee77248a5f434e81debe37637e6a4",
          "sha1": "c3819d8877d617af2a528f7da334098479171b70",
          "md5": "0ccbb2f88a56a95fddee589821cec123"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1217085,
          "sha512": "8602797310f118f34d308c74f43f3924c2cb669435079ab9936c0e3dadfa376881c2e847103cb1db4df6afeaf7f9c735a48ba2d4ceb43fcc500de1dca5430d74",
          "sha256": "3a14c389dd7272ed0e617a55ea8baeb45b3ee77248a5f434e81debe37637e6a4",
          "sha1": "c3819d8877d617af2a528f7da334098479171b70",
          "md5": "0ccbb2f88a56a95fddee589821cec123"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 332057,
          "sha512": "76ff96beb8c2fac2233640c1a87e2426f1602d866c7e7a4606ae3446c44f0d7f0fde94e23097a36eb35500c25ae1f5894d74a3c5b0d89ce63069b1c56a30404b",
          "sha256": "049da05563b07ac791142b42d430afb44a915ea09255a9ed587ff930bf8fe00c",
          "sha1": "c84df8b00e41b748c13cb78ada89c434347b46e9",
          "md5": "30fa008e87b5669303232a828720eebb"
        }
      ]
    }
  ]
}
