{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1146084,
          "sha512": "07004469224fbd710a3cb25e8308aba855000726d12591562ab448ada46f4511bc138e070509bc822ec13c4dd8cb1193a55e867df1c93f0a4654ee49f9811598",
          "sha256": "466290282cc276fc900e3ccca04959f58c9ad7280b79e50f38a53900f365656d",
          "sha1": "2e29683f85f5f13626b4d9f5a07c1e43ea59b932",
          "md5": "6cb3116de02ddfbba3d85520eb5274ee"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1146084,
          "sha512": "07004469224fbd710a3cb25e8308aba855000726d12591562ab448ada46f4511bc138e070509bc822ec13c4dd8cb1193a55e867df1c93f0a4654ee49f9811598",
          "sha256": "466290282cc276fc900e3ccca04959f58c9ad7280b79e50f38a53900f365656d",
          "sha1": "2e29683f85f5f13626b4d9f5a07c1e43ea59b932",
          "md5": "6cb3116de02ddfbba3d85520eb5274ee"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 311351,
          "sha512": "c8eaa9d7698be531b749fbd1ccd2905c971eca2e5cafaeeb02b633123dcca2fd753748b1bec805059058292ae04a48b285511f01de677dac8a67797b90ca7b7d",
          "sha256": "69feae7138fd33fe485ba1665ff8f622bb24e076d99e4e37651b930f47512c74",
          "sha1": "06316b54c22c8847f423f3c8d4a45f990922a345",
          "md5": "adab83bf9dade7e3111449cbab1994e9"
        }
      ]
    }
  ]
}
