{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1204511,
          "sha512": "9932d08775230d7544dd03a7f54a9483a754f31bff90a2b30aab8ee23a15a8090d84b897389ec9da4e21dfd5bf467e39a783f4eb4c79f894015af3fe1b3fec51",
          "sha256": "7e7b09d4d984cbe3ac42fcb9ee06758de1d8f2bd895a939b19dcaa2a06182d87",
          "sha1": "8619f0ec53df8e06f80875dba9608475922e9b22",
          "md5": "27652969efe363903c5eaea3ed693d59"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1204511,
          "sha512": "9932d08775230d7544dd03a7f54a9483a754f31bff90a2b30aab8ee23a15a8090d84b897389ec9da4e21dfd5bf467e39a783f4eb4c79f894015af3fe1b3fec51",
          "sha256": "7e7b09d4d984cbe3ac42fcb9ee06758de1d8f2bd895a939b19dcaa2a06182d87",
          "sha1": "8619f0ec53df8e06f80875dba9608475922e9b22",
          "md5": "27652969efe363903c5eaea3ed693d59"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 327965,
          "sha512": "6f916af4fc8c172ee3f619c268c18773fdba1533b2d1eb6ce53308ddd9532b1a57f7d294a8544db2e92b476ccedbef4e4af9df0ff31524227446c602495b6a0c",
          "sha256": "bbae4603b820b2f2e5f6adf84dfa6e394fe3050f1e30d313f289e9fe44e9a0b3",
          "sha1": "17681ea983e8e4f8ef39a41b0391c4b54b732ee5",
          "md5": "0d601615ea3285ad89539d5461d20bef"
        }
      ]
    }
  ]
}
