{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1204888,
          "sha512": "8df4cd36f8a555a1c708c58c0083291d5921952d99b08f82b0f8e8448f5c3af5df29cf406faf1915e27e760fd39cc95768245ad7941495180f2366b4ab6d717a",
          "sha256": "87b73cdf9fe8af9b263ac45c6c5bb6e7ad7507a694ea54569214a40be0138db3",
          "sha1": "54d48347201466d1102d37b193c9943cffbca097",
          "md5": "7affbd3f9af5d479068795b5c49272c1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1204888,
          "sha512": "8df4cd36f8a555a1c708c58c0083291d5921952d99b08f82b0f8e8448f5c3af5df29cf406faf1915e27e760fd39cc95768245ad7941495180f2366b4ab6d717a",
          "sha256": "87b73cdf9fe8af9b263ac45c6c5bb6e7ad7507a694ea54569214a40be0138db3",
          "sha1": "54d48347201466d1102d37b193c9943cffbca097",
          "md5": "7affbd3f9af5d479068795b5c49272c1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 328161,
          "sha512": "fdbf00d13968be03307282bc8ab570dffaeba20fcd538d9e18474beed643c52b25e677be4f6cd654afd51029dd9e583f836f57ccdcbe0fe9884ec07b6f153f5c",
          "sha256": "2b16280f0f9e349705268bc679a26411885e54e51cefca42419ead13f1fb5ffd",
          "sha1": "d499dc369977d86987260a990adb67d7763e13d0",
          "md5": "866e366d92bb8e61d5c1b7246e16747c"
        }
      ]
    }
  ]
}
