{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1166280,
          "sha512": "03f297aeb576112a437e321ebd386c84af3b0137860b9afebff9b3b8fbf9711cba904349d9c0e2dcb3f8b6dd67524385adf7c5a8daec28abddc91215e20754b7",
          "sha256": "01504b23e8a80fd80faf8178caa9b2979a8a0b72cad92162fda623713e36a418",
          "sha1": "6ecbb014dcb370fe7775777f0f1eae3f564b52ef",
          "md5": "7242c2c3c3b6c435cd6fd3b08ee7e493"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1166280,
          "sha512": "03f297aeb576112a437e321ebd386c84af3b0137860b9afebff9b3b8fbf9711cba904349d9c0e2dcb3f8b6dd67524385adf7c5a8daec28abddc91215e20754b7",
          "sha256": "01504b23e8a80fd80faf8178caa9b2979a8a0b72cad92162fda623713e36a418",
          "sha1": "6ecbb014dcb370fe7775777f0f1eae3f564b52ef",
          "md5": "7242c2c3c3b6c435cd6fd3b08ee7e493"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 314245,
          "sha512": "582f152eded44b5f3c2089c3447f72e4ff953411ba77a02bde9a83d40a8e172150f50be99a35ec3ea3717fa1ec4ad69c266388802aa01b9f97d39290984fa0f6",
          "sha256": "6ede231113d5e0cb6afa3e0d0759f20deb46d291cea417ea916162646f360031",
          "sha1": "5e360694d93e27a0e260d9f127549584c1023d6b",
          "md5": "bacd47adb797c3fe2d04dfc02ea08745"
        }
      ]
    }
  ]
}
