{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "fsc",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1113192,
          "sha512": "305a717d5fce43ad831f7a8364898d6dfa864de083fd5d0e1f75cf1563e618ad8cd7ddb60e764cf36760f0f3621d510c02b4a98e4e0b212e4a4ffd43466b928d",
          "sha256": "0c004216ad52abf78348aba41235be0d0017a2a1e52531b61edc0b758b3921e3",
          "sha1": "2c5e6dd99462a345246080d96f3576818a12362f",
          "md5": "840a67343150ee2fafd3fad2ea199769"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "core",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "bluetooth",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "websocket",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT.aar",
          "url": "fsc-hingin-SNAPSHOT.aar",
          "size": 1113192,
          "sha512": "305a717d5fce43ad831f7a8364898d6dfa864de083fd5d0e1f75cf1563e618ad8cd7ddb60e764cf36760f0f3621d510c02b4a98e4e0b212e4a4ffd43466b928d",
          "sha256": "0c004216ad52abf78348aba41235be0d0017a2a1e52531b61edc0b758b3921e3",
          "sha1": "2c5e6dd99462a345246080d96f3576818a12362f",
          "md5": "840a67343150ee2fafd3fad2ea199769"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fsc-hingin-SNAPSHOT-sources.jar",
          "url": "fsc-hingin-SNAPSHOT-sources.jar",
          "size": 300363,
          "sha512": "902c0095e594a420c87fab02e53e8135eebb1eeb4c7f0b6cd2fea92bcbf927f32e8e92daafd2e3ddf17e65cac5f7ee5d022891c572d5e40273b39423d71fe0c3",
          "sha256": "a8d122a837c6dbe7f248563045156ca1f633cb8262839f61a720833a3d01f5b5",
          "sha1": "8e604b8b240633ff08088283f1270bf8edbcbd72",
          "md5": "80876912265841921dba73679e41725c"
        }
      ]
    }
  ]
}
