{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "vector",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.LaserPeckerIst",
          "module": "sharp",
          "version": {
            "requires": "1.1.3.28"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "Android-Kabeja",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vector-hingin-SNAPSHOT.aar",
          "url": "vector-hingin-SNAPSHOT.aar",
          "size": 123220,
          "sha512": "faa7bdfe791659d6e3177866ed1fc239ca321ceb0ff5a54630fc9297df7741c75d379071a2581a38303b05d39c63baf367f6eded87306e36b8c3051ff9602b7d",
          "sha256": "b4620a590002fd473eac26dabe2a3fa20f66b27cdc3976915fe2b47fab7856c7",
          "sha1": "4cde110d22ecb10a15bfad376d13b9c7bba5064a",
          "md5": "a38a84317905bf58863064623d5e54e5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "sharp",
          "version": {
            "requires": "1.1.3.28"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "Android-Kabeja",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vector-hingin-SNAPSHOT.aar",
          "url": "vector-hingin-SNAPSHOT.aar",
          "size": 123220,
          "sha512": "faa7bdfe791659d6e3177866ed1fc239ca321ceb0ff5a54630fc9297df7741c75d379071a2581a38303b05d39c63baf367f6eded87306e36b8c3051ff9602b7d",
          "sha256": "b4620a590002fd473eac26dabe2a3fa20f66b27cdc3976915fe2b47fab7856c7",
          "sha1": "4cde110d22ecb10a15bfad376d13b9c7bba5064a",
          "md5": "a38a84317905bf58863064623d5e54e5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "vector-hingin-SNAPSHOT-sources.jar",
          "url": "vector-hingin-SNAPSHOT-sources.jar",
          "size": 76781,
          "sha512": "814f0f319169284854e002896658cc7ef1d8f66fd6a50dd505ee3482c19d5d1c80b30d7f64fe75a1aa8b9c7f14e0ee4c5129a889d529a2f660a4297d199def08",
          "sha256": "927ca8d930ea398d40a05753227cd201a537567af897f4b5fcee29233cb0c6ff",
          "sha1": "8e2ea39660a06049548df9da17ef7f09258235ee",
          "md5": "85617266dc591d5b52651cba363d1630"
        }
      ]
    }
  ]
}
