{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "vector",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.LaserPeckerIst",
          "module": "sharp",
          "version": {
            "requires": "1.1.3.28"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "Android-Kabeja",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vector-hingin-SNAPSHOT.aar",
          "url": "vector-hingin-SNAPSHOT.aar",
          "size": 107951,
          "sha512": "cc6e383fc1e99b3defe6b00fe1148d27863e19d3ae422d76396f186f8236c2f92f2b83bf353929b6941ac1ac7579bcc4c63d71019c57578dc8c6a4236a0ad6ce",
          "sha256": "3c058a22b19659a989e1a1e714c577ccb883413fff3bc57781fbb928cd479b9d",
          "sha1": "972f4962325a99bf2bf67ca7cc8b8f3039a67820",
          "md5": "2b421697d1c87e1acd02d3ee97143dd6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "sharp",
          "version": {
            "requires": "1.1.3.28"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "Android-Kabeja",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vector-hingin-SNAPSHOT.aar",
          "url": "vector-hingin-SNAPSHOT.aar",
          "size": 107951,
          "sha512": "cc6e383fc1e99b3defe6b00fe1148d27863e19d3ae422d76396f186f8236c2f92f2b83bf353929b6941ac1ac7579bcc4c63d71019c57578dc8c6a4236a0ad6ce",
          "sha256": "3c058a22b19659a989e1a1e714c577ccb883413fff3bc57781fbb928cd479b9d",
          "sha1": "972f4962325a99bf2bf67ca7cc8b8f3039a67820",
          "md5": "2b421697d1c87e1acd02d3ee97143dd6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "vector-hingin-SNAPSHOT-sources.jar",
          "url": "vector-hingin-SNAPSHOT-sources.jar",
          "size": 66385,
          "sha512": "51de4e21cd4317e735bb7853f2587af1344c4132790e35e9befaf9378cca43e729f9708c22fca49fec4aedc0730b7389778b0a65441134116efde56daf591588",
          "sha256": "3724ca4f3a2d15972f351968db0a646aaaa0800f6d9d9a2009d2c53a16a92bda",
          "sha1": "e941acf250134168eb87fcc03c449a23f4eccf76",
          "md5": "e04ede4ac7f0ca22cb51c2a415e3ddee"
        }
      ]
    }
  ]
}
